import {Head,router} from '@inertiajs/react';
import {ChangeEvent,FormEvent,useState} from 'react';
type Item={id:number;title:string;category:string;status:string;institution?:string|null;faculty?:string|null;department?:string|null;course_code?:string|null;course_title?:string|null;education_level?:string|null;semester?:string|null;academic_session?:string|null;exam_body?:string|null;exam_type?:string|null;subject?:string|null;exam_year?:number|null;description?:string|null;is_free:boolean;price_minor:number;currency:string;file_name:string;downloads_count:number;purchases_count:number};
type Props={items:{data:Item[];links?:{url:string|null;label:string;active:boolean}[]};filters?:Record<string,string|null>};
export default function PastQuestions({items,filters={}}:Props){
 const [form,setForm]=useState({category:'school_past_question',title:'',institution:'',faculty:'',department:'',course_code:'',course_title:'',education_level:'',semester:'',academic_session:'',exam_body:'',exam_type:'',subject:'',exam_year:'',description:'',is_free:true,price_minor:'0',currency:'NGN',file:null as File|null,preview_file:null as File|null});
 const [q,setQ]=useState(filters.q||''); const [editingId,setEditingId]=useState<number|null>(null);
 const updateFile=(e:ChangeEvent<HTMLInputElement>)=>setForm({...form,file:e.target.files?.[0]||null});
 const updatePreview=(e:ChangeEvent<HTMLInputElement>)=>setForm({...form,preview_file:e.target.files?.[0]||null});
 const resetForm=()=>{setEditingId(null);setForm({category:'school_past_question',title:'',institution:'',faculty:'',department:'',course_code:'',course_title:'',education_level:'',semester:'',academic_session:'',exam_body:'',exam_type:'',subject:'',exam_year:'',description:'',is_free:true,price_minor:'0',currency:'NGN',file:null,preview_file:null});};
 const edit=(item:Item)=>{setEditingId(item.id);setForm({category:item.category,title:item.title,institution:item.institution||'',faculty:item.faculty||'',department:item.department||'',course_code:item.course_code||'',course_title:item.course_title||'',education_level:item.education_level||'',semester:item.semester||'',academic_session:item.academic_session||'',exam_body:item.exam_body||'',exam_type:item.exam_type||'',subject:item.subject||'',exam_year:item.exam_year?String(item.exam_year):'',description:item.description||'',is_free:item.is_free,price_minor:String(item.price_minor),currency:item.currency,file:null,preview_file:null});};
 const submit=(e:FormEvent)=>{e.preventDefault();const data=new FormData();Object.entries(form).forEach(([key,value])=>{if(value!==null)data.append(key,typeof value==='boolean'?(value?'1':'0'):value instanceof File?value:String(value));});if(editingId)data.append('_method','PUT');router.post(editingId?'/admin/education/past-questions/'+editingId:'/admin/education/past-questions',data,{forceFormData:true,onSuccess:resetForm});};
 return <><Head title="Admin · Education Library"/><main className="space-y-6 p-5 md:p-8"><header><h1 className="text-3xl font-bold">Education Library</h1><p className="mt-2 opacity-70">Upload and publish school and examination past questions. New uploads stay private until published.</p></header>
 <section className="rounded-2xl border p-5"><h2 className="mb-4 text-xl font-semibold">{editingId?'Edit resource':'Upload a resource'}</h2><form onSubmit={submit} className="grid gap-3 md:grid-cols-3">
 <select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="rounded-lg border bg-transparent p-3"><option value="school_past_question">School Past Questions</option><option value="exam_past_question">Exam Past Questions</option></select>
 <input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Resource title" className="rounded-lg border bg-transparent p-3"/>
 <input required={!editingId} type="file" accept=".pdf,.doc,.docx" onChange={updateFile} className="rounded-lg border p-3"/><input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={updatePreview} className="rounded-lg border p-3" aria-label="Optional preview PDF or image"/>
 {([['institution','Institution / school'],['faculty','Faculty'],['department','Department'],['course_code','Course code'],['course_title','Course title'],['education_level','Level'],['semester','Semester'],['academic_session','Academic session'],['exam_body','Exam body (WAEC/NECO/JAMB...)'],['exam_type','Exam type'],['subject','Subject'],['exam_year','Exam year'],['currency','Currency (e.g. NGN)']] as const).map(([key,label])=><input key={key} value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})} placeholder={label} className="rounded-lg border bg-transparent p-3"/>)}
 <textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Description / notes" className="rounded-lg border bg-transparent p-3 md:col-span-2"/>
 <label className="flex items-center gap-2 rounded-lg border p-3"><input type="checkbox" checked={form.is_free} onChange={e=>setForm({...form,is_free:e.target.checked,price_minor:e.target.checked?'0':form.price_minor})}/>Free download</label>
 <input type="number" min="0" value={form.price_minor} disabled={form.is_free} onChange={e=>setForm({...form,price_minor:e.target.value})} placeholder="Price in minor units (kobo)" className="rounded-lg border bg-transparent p-3"/>
 <button className="rounded-lg bg-black px-4 py-3 text-white md:col-span-3">{editingId?'Save changes':'Upload as draft'}</button>{editingId&&<button type="button" onClick={resetForm} className="rounded-lg border px-4 py-3 md:col-span-3">Cancel editing</button>}</form><p className="mt-3 text-xs opacity-60">PDF, DOC or DOCX · Maximum 20 MB · Price is entered in minor units (kobo for NGN).</p></section>
 <section className="rounded-2xl border p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold">Library resources</h2><form onSubmit={e=>{e.preventDefault();router.get('/admin/education/past-questions',{q},{preserveState:true,replace:true});}} className="flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search resources" className="rounded-lg border bg-transparent p-2"/><button className="rounded-lg border px-3">Search</button></form></div>
 <div className="space-y-3">{items?.data?.map(item=><article key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4"><div><h3 className="font-semibold">{item.title}</h3><p className="text-sm opacity-70">{item.category==='school_past_question'?'School Past Questions':'Exam Past Questions'} · {item.institution||item.exam_body||item.subject||'No category metadata'} · {item.status} · {item.is_free?'Free':item.currency+' '+(item.price_minor/100).toFixed(2)}</p><p className="text-xs opacity-60">{item.file_name} · {item.downloads_count} downloads · {item.purchases_count} purchases</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>edit(item)} className="rounded-lg border px-3 py-2 text-sm">Edit</button>{item.status!=='published'&&<button onClick={()=>router.post('/admin/education/past-questions/'+item.id+'/publish')} className="rounded-lg border px-3 py-2 text-sm">Publish</button>}{item.status!=='archived'&&<button onClick={()=>router.post('/admin/education/past-questions/'+item.id+'/archive')} className="rounded-lg border px-3 py-2 text-sm">Archive</button>}{!item.purchases_count&&<button onClick={()=>router.delete('/admin/education/past-questions/'+item.id)} className="rounded-lg border px-3 py-2 text-sm">Delete</button>}</div></article>)}</div>
 {!items?.data?.length&&<p className="p-8 text-center opacity-70">No resources uploaded yet.</p>}
 <nav className="mt-4 flex flex-wrap gap-2">{items?.links?.map((link,i)=><button key={i} disabled={!link.url} onClick={()=>link.url&&router.get(link.url,{}, {preserveState:true,preserveScroll:true})} className={'rounded-lg border px-3 py-2 text-sm '+(link.active?'bg-black text-white':'')} dangerouslySetInnerHTML={{__html:link.label}} />)}</nav>
 </section></main></>;
}
