import {Head,router} from '@inertiajs/react';
import {FormEvent,useState} from 'react';
type Entry={id:number;kind:string;category:string|null;name:string;short_name:string|null;state:string|null;country:string|null;official_url:string|null;source_url:string|null;is_active:boolean};
type Category={id:number;kind:string;name:string;slug:string;description:string|null;sort_order:number;is_active:boolean};
type Props={entries:{data:Entry[];links?:{url:string|null;label:string;active:boolean}[]};filters:Record<string,string|null>;categories:Category[];categoryOptions:string[];flash?:{success?:string|null;error?:string|null};validationErrors?:Record<string,string[]>};
const kinds=[['school','School / institution'],['exam_body','Examination body'],['exam_type','Exam type']];
export default function ReferenceCatalogue({entries,filters={},categories=[],categoryOptions=[],flash={},validationErrors={}}:Props){
 const [kind,setKind]=useState('school'),[name,setName]=useState(''),[category,setCategory]=useState('federal_university'),[shortName,setShortName]=useState(''),[state,setState]=useState(''),[country,setCountry]=useState('Nigeria'),[officialUrl,setOfficialUrl]=useState(''),[sourceUrl,setSourceUrl]=useState('');
 const [newCategoryKind,setNewCategoryKind]=useState('school'),[newCategoryName,setNewCategoryName]=useState(''),[description,setDescription]=useState('');
 const [csvFile,setCsvFile]=useState<File|null>(null);
 const importCsv=(e:FormEvent)=>{e.preventDefault();if(!csvFile)return;router.post('/admin/education/references/import-csv',{file:csvFile},{forceFormData:true,onSuccess:()=>setCsvFile(null)});};
 const submit=(e:FormEvent)=>{e.preventDefault();router.post('/admin/education/references',{kind,name,category:kind==='school'?category:(category||null),short_name:shortName||null,state:state||null,country:country||null,official_url:officialUrl||null,source_url:sourceUrl||null},{onSuccess:()=>{setName('');setShortName('');setState('');setOfficialUrl('');setSourceUrl('');}});};
 const addCategory=(e:FormEvent)=>{e.preventDefault();router.post('/admin/education/references/categories',{kind:newCategoryKind,name:newCategoryName,description},{onSuccess:()=>{setNewCategoryName('');setDescription('');}});};
 const search=(e:FormEvent)=>{e.preventDefault();const data=new FormData(e.currentTarget as HTMLFormElement);router.get('/admin/education/references',Object.fromEntries(data.entries()) as Record<string,string>,{preserveState:true,replace:true});};
 const categoryList=[...new Set([...categoryOptions,...categories.filter(c=>c.kind==='school'&&c.is_active).map(c=>c.slug)])].sort();
 return <><Head title="Education Reference Catalogue"/><main className="mx-auto max-w-7xl space-y-6 p-4 md:p-8"><header><h1 className="text-2xl font-bold">Education Reference Catalogue</h1><p className="mt-1 text-sm opacity-70">Manage schools, exam bodies, exam types and categories. New entries appear in catalogue suggestions.</p></header>
 {flash.success&&<div role="status" className="rounded-xl border border-emerald-300 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{flash.success}</div>}
 {flash.error&&<div role="alert" className="rounded-xl border border-red-300 bg-red-50 p-4 text-sm font-semibold text-red-800">{flash.error}</div>}
 {Object.values(validationErrors).flat().length>0&&<div role="alert" className="rounded-xl border border-red-300 bg-red-50 p-4 text-sm text-red-800"><p className="font-bold">Please check the following:</p><ul className="mt-1 list-disc pl-5">{Object.values(validationErrors).flat().map((message,i)=><li key={i}>{message}</li>)}</ul></div>}
 <section className="rounded-xl border p-4 md:p-6"><h2 className="mb-2 text-lg font-semibold">Bulk import references from CSV</h2><p className="mb-4 text-sm opacity-70">Import up to 2,000 rows per file (5 MB maximum). Required headers: kind,name,category. Optional: short_name,state,country,official_url,source_url. Kind must be school, exam_body, or exam_type. Existing entries are skipped.</p><form onSubmit={importCsv} className="flex flex-col gap-3 sm:flex-row sm:items-center"><input type="file" accept=".csv,text/csv" required onChange={e=>setCsvFile(e.target.files?.[0]||null)} className="min-w-0 flex-1 rounded-lg border p-3"/><button disabled={!csvFile} className="rounded-lg bg-indigo-600 px-4 py-3 font-semibold text-white disabled:opacity-50">Import CSV</button></form></section>
 <section className="rounded-xl border p-4 md:p-6"><h2 className="mb-4 text-lg font-semibold">Add a school or exam reference</h2><form onSubmit={submit} className="grid gap-3 md:grid-cols-3">
 <select value={kind} onChange={e=>{setKind(e.target.value);setCategory(e.target.value==='school'?'federal_university':'general');}} className="rounded-lg border bg-transparent p-3">{kinds.map(k=><option key={k[0]} value={k[0]}>{k[1]}</option>)}</select>
 <input required value={name} onChange={e=>setName(e.target.value)} placeholder="Full name" className="rounded-lg border bg-transparent p-3"/>
 {kind==='school'?<select required value={category} onChange={e=>setCategory(e.target.value)} className="rounded-lg border bg-transparent p-3">{categoryList.map(c=><option key={c} value={c}>{c.replaceAll('_',' ')}</option>)}</select>:<input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Category / exam family (optional)" className="rounded-lg border bg-transparent p-3"/>}
 <input value={shortName} onChange={e=>setShortName(e.target.value)} placeholder="Short name / acronym" className="rounded-lg border bg-transparent p-3"/>
 <input value={state} onChange={e=>setState(e.target.value)} placeholder="State (schools)" className="rounded-lg border bg-transparent p-3"/>
 <input value={country} onChange={e=>setCountry(e.target.value)} placeholder="Country" className="rounded-lg border bg-transparent p-3"/>
 <input value={officialUrl} onChange={e=>setOfficialUrl(e.target.value)} placeholder="Official website URL" className="rounded-lg border bg-transparent p-3"/>
 <input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="Source / regulator URL" className="rounded-lg border bg-transparent p-3"/>
 <button className="rounded-lg bg-slate-900 px-4 py-3 font-semibold text-white">Add reference</button>
 </form></section>
 <section className="rounded-xl border p-4 md:p-6"><h2 className="mb-4 text-lg font-semibold">Add a reusable category</h2><form onSubmit={addCategory} className="grid gap-3 md:grid-cols-4"><select value={newCategoryKind} onChange={e=>setNewCategoryKind(e.target.value)} className="rounded-lg border bg-transparent p-3">{kinds.map(k=><option key={k[0]} value={k[0]}>{k[1]}</option>)}</select><input required value={newCategoryName} onChange={e=>setNewCategoryName(e.target.value)} placeholder="Category name" className="rounded-lg border bg-transparent p-3"/><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description (optional)" className="rounded-lg border bg-transparent p-3"/><button className="rounded-lg border px-4 py-3 font-semibold">Create category</button></form><div className="mt-3 space-y-2">{categories.map(c=><div key={c.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border p-3 text-sm"><span>{c.name} · {c.kind.replaceAll('_',' ')} · {c.is_active?'Active':'Inactive'}</span><button type="button" onClick={()=>router.put('/admin/education/references/categories/'+c.id,{name:c.name,description:c.description,sort_order:c.sort_order,is_active:!c.is_active})} className="rounded border px-3 py-1">{c.is_active?'Deactivate':'Activate'}</button></div>)}</div></section>
 <section className="rounded-xl border p-4 md:p-6"><form onSubmit={search} className="mb-4 grid gap-3 md:grid-cols-4"><select name="kind" defaultValue={filters.kind||''} className="rounded-lg border bg-transparent p-3"><option value="">All reference types</option>{kinds.map(k=><option key={k[0]} value={k[0]}>{k[1]}</option>)}</select><input name="q" defaultValue={filters.q||''} placeholder="Search references" className="rounded-lg border bg-transparent p-3"/><select name="category" defaultValue={filters.category||''} className="rounded-lg border bg-transparent p-3"><option value="">All categories</option>{categoryList.map(c=><option key={c} value={c}>{c.replaceAll('_',' ')}</option>)}</select><button className="rounded-lg border p-3">Filter catalogue</button></form>
 <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="border-b"><th className="p-3">Name</th><th className="p-3">Type / category</th><th className="p-3">Location / acronym</th><th className="p-3">Official link</th><th className="p-3">Action</th></tr></thead><tbody>{entries.data.map(item=><tr key={item.id} className="border-b align-top"><td className="p-3 font-medium">{item.name}<div className="text-xs opacity-60">{item.is_active?'Active':'Inactive'}</div></td><td className="p-3">{item.kind.replaceAll('_',' ')}<div className="text-xs opacity-60">{(item.category||'').replaceAll('_',' ')}</div></td><td className="p-3">{[item.short_name,item.state,item.country].filter(Boolean).join(' · ')}</td><td className="p-3">{item.official_url?<a className="underline" href={item.official_url} target="_blank" rel="noreferrer">Open</a>:'—'}</td><td className="p-3"><div className="flex gap-2"><button onClick={()=>router.put('/admin/education/references/'+item.id,{name:item.name,category:item.category,short_name:item.short_name,state:item.state,country:item.country,official_url:item.official_url,source_url:item.source_url,is_active:!item.is_active})} className="rounded border px-3 py-1">{item.is_active?'Deactivate':'Activate'}</button><button onClick={()=>{const next=window.confirm('Remove this reference?');if(next)router.delete('/admin/education/references/'+item.id);}} className="rounded border px-3 py-1">Remove</button></div></td></tr>)}</tbody></table></div>
 <nav className="mt-4 flex flex-wrap gap-2">{entries.links?.map((link,i)=><button key={i} disabled={!link.url} onClick={()=>link.url&&router.visit(link.url)} className={'rounded border px-3 py-2 '+(link.active?'font-bold':'')}>{link.label.replace('&laquo;','«').replace('&raquo;','»')}</button>)}</nav>
 </section></main></>;
}
