import {Head,router} from '@inertiajs/react'; import {FormEvent,useState} from 'react';
type Any={id:number;name:string;[k:string]:any};
export default function SchoolAdmission({institutions=[],units=[],departments=[],programmes=[],sessions=[],admissionRoutes=[],admissions}:any){
 const [tab,setTab]=useState('structure'); const [form,setForm]=useState<any>({});
 const post=(url:string,e:FormEvent)=>{e.preventDefault();router.post(url,form,{onSuccess:()=>setForm({})});}; const unitsFor=()=>units.filter((x:Any)=>String(x.institution_id)===String(form.institution_id)); const departmentsFor=()=>departments.filter((x:Any)=>String(x.institution_id)===String(form.institution_id) && (!form.academic_unit_id || String(x.academic_unit_id)===String(form.academic_unit_id)));
 const input=(k:string,l:string)=><input value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={l} className="rounded-lg border p-3"/>;
 return <><Head title="Admin · School Admission"/><main className="space-y-6 p-6"><header><h1 className="text-2xl font-bold">School Admission</h1><p className="text-sm opacity-70">Research and manage institution → academic unit → department → programme → session → requirements.</p></header>
 <nav className="flex flex-wrap gap-2">{['structure','programmes','sessions','admissions'].map(x=><button onClick={()=>setTab(x)} className={`rounded-lg border px-4 py-2 ${tab===x?'bg-black text-white':''}`}>{x}</button>)}</nav>
 {tab==='structure'&&<div className="grid gap-5 md:grid-cols-3"><section className="rounded-xl border p-5"><h2 className="font-semibold mb-3">Academic Unit</h2><form onSubmit={e=>post('/admin/education/school-admission/academic-units',e)} className="space-y-3"><select className="w-full rounded-lg border p-3" value={form.institution_id||''} onChange={e=>setForm({...form,institution_id:e.target.value})}><option value="">Institution</option>{institutions.map((x:Any)=><option value={x.id}>{x.name}</option>)}</select>{input('unit_type','Faculty / School / College / Institute')}{input('name','Name')}{input('source_url','Official source URL')}<button className="rounded-lg bg-black px-4 py-3 text-white">Create unit</button></form></section>
 <section className="rounded-xl border p-5"><h2 className="font-semibold mb-3">Department</h2><form onSubmit={e=>post('/admin/education/school-admission/departments',e)} className="space-y-3"><select className="w-full rounded-lg border p-3" value={form.institution_id||''} onChange={e=>setForm({...form,institution_id:e.target.value})}><option value="">Institution</option>{institutions.map((x:Any)=><option value={x.id}>{x.name}</option>)}</select><select className="w-full rounded-lg border p-3" value={form.academic_unit_id||''} onChange={e=>setForm({...form,academic_unit_id:e.target.value})}><option value="">Academic Unit</option>{unitsFor().map((x:Any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select>{input('name','Department name')}{input('source_url','Official source URL')}<button className="rounded-lg bg-black px-4 py-3 text-white">Create department</button></form></section>
 <section className="rounded-xl border p-5"><h2 className="font-semibold mb-3">Programme</h2><form onSubmit={e=>post('/admin/education/school-admission/programmes',e)} className="space-y-3"><select className="w-full rounded-lg border p-3" value={form.institution_id||''} onChange={e=>setForm({...form,institution_id:e.target.value})}><option value="">Institution</option>{institutions.map((x:Any)=><option value={x.id}>{x.name}</option>)}</select><select className="w-full rounded-lg border p-3" value={form.academic_unit_id||''} onChange={e=>setForm({...form,academic_unit_id:e.target.value,department_id:''})}><option value="">Academic Unit</option>{unitsFor().map((x:Any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="w-full rounded-lg border p-3" value={form.department_id||''} onChange={e=>setForm({...form,department_id:e.target.value})}><option value="">Department</option>{departmentsFor().map((x:Any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select>{input('name','Programme / Course')}{input('award_type','Award e.g. B.Sc.')}{input('source_url','Official source URL')}<button className="rounded-lg bg-black px-4 py-3 text-white">Create programme</button></form></section></div>}
 {tab==='sessions'&&<section className="rounded-xl border p-5"><h2 className="font-semibold mb-3">Academic Sessions</h2><form onSubmit={e=>post('/admin/education/school-admission/sessions',e)} className="flex flex-wrap gap-3">{input('name','2026/2027')}{input('start_year','Start year')}{input('end_year','End year')}<button className="rounded-lg bg-black px-4 py-3 text-white">Add session</button></form><div className="mt-5 space-y-2">{sessions.map((s:Any)=><div className="rounded-lg border p-3">{s.name}</div>)}</div></section>}
 {tab==='admissions'&&<section className="rounded-xl border p-5"><h2 className="font-semibold mb-3">Programme Admission Research Record</h2><form onSubmit={e=>post('/admin/education/school-admission/programme-admissions',e)} className="grid gap-3 md:grid-cols-2"><select className="w-full rounded-lg border p-3" value={form.programme_id||''} onChange={e=>setForm({...form,programme_id:e.target.value})}><option value="">Programme</option>{programmes.map((x:Any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="w-full rounded-lg border p-3" value={form.academic_session_id||''} onChange={e=>setForm({...form,academic_session_id:e.target.value})}><option value="">Academic Session</option>{sessions.map((x:Any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select>{input('source_title','Official source title')}{input('official_source_url','Official source URL')}<label><input type="checkbox" checked={!!form.utme_available} onChange={e=>setForm({...form,utme_available:e.target.checked})}/> UTME available</label><label><input type="checkbox" checked={!!form.direct_entry_available} onChange={e=>setForm({...form,direct_entry_available:e.target.checked})}/> Direct Entry available</label><button className="rounded-lg bg-black px-4 py-3 text-white">Save as researched</button></form><p className="mt-4 text-sm opacity-70">Requirements, subject combinations, DE qualifications, cut-offs, screening rules, special rules, documents and sources are stored separately from past questions.</p></section>}
 </main></>;
}