import { Head, router } from '@inertiajs/react';
import { FormEvent, useState } from 'react';

type Any = { id:number; name:string; [k:string]:any };

export default function SchoolAdmission({institutions=[],units=[],departments=[],programmes=[],sessions=[],admissionRoutes=[],admissions}:any) {
 const [tab,setTab]=useState('structure');
 const [form,setForm]=useState<any>({});
 const post=(url:string,e:FormEvent)=>{e.preventDefault();router.post(url,form,{preserveScroll:true,onSuccess:()=>setForm({})});};
 const set=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v}));
 const unitsFor=()=>units.filter((x:Any)=>String(x.institution_id)===String(form.institution_id));
 const departmentsFor=()=>departments.filter((x:Any)=>String(x.institution_id)===String(form.institution_id)&&(!form.academic_unit_id||String(x.academic_unit_id)===String(form.academic_unit_id)));
 const programmeLabel=(x:Any)=>[x.name,x.institution?.name].filter(Boolean).join(' · ');
 const admissionLabel=(x:Any)=>[x.programme?.name,x.academicSession?.name].filter(Boolean).join(' · ');
 const input=(k:string,l:string,type='text')=><input type={type} value={form[k]??''} onChange={e=>set(k,e.target.value)} placeholder={l} className="w-full rounded-lg border p-3"/>;
 const select=(k:string,l:string,items:Any[],label=(x:Any)=>x.name)=><select className="w-full rounded-lg border p-3" value={form[k]??''} onChange={e=>set(k,e.target.value)}><option value="">{l}</option>{items.map((x:Any)=><option key={x.id} value={x.id}>{label(x)}</option>)}</select>;
 const bool=(k:string,l:string)=><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!form[k]} onChange={e=>set(k,e.target.checked)}/>{l}</label>;
 return <><Head title="Admin · School Admission"/><main className="space-y-6 p-6">
  <header><h1 className="text-2xl font-bold">School Admission</h1><p className="text-sm opacity-70">Research-first admission data: institution → academic unit → department → programme → session → requirements → verification → publication.</p></header>
  <nav className="flex flex-wrap gap-2">{['structure','sessions','admissions','requirements','cutoffs','screening'].map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-lg border px-4 py-2 ${tab===x?'bg-black text-white':''}`}>{x}</button>)}</nav>

  {tab==='structure'&&<div className="grid gap-5 md:grid-cols-3">
   <section className="rounded-xl border p-5"><h2 className="mb-3 font-semibold">Academic Unit</h2><form onSubmit={e=>post('/admin/education/school-admission/academic-units',e)} className="space-y-3">{select('institution_id','Institution',institutions)}{input('unit_type','Faculty / School / College / Institute')}{input('name','Name')}{input('source_title','Official source title')}{input('source_url','Official source URL')}<button className="rounded-lg bg-black px-4 py-3 text-white">Create unit</button></form></section>
   <section className="rounded-xl border p-5"><h2 className="mb-3 font-semibold">Department</h2><form onSubmit={e=>post('/admin/education/school-admission/departments',e)} className="space-y-3">{select('institution_id','Institution',institutions)}{select('academic_unit_id','Academic Unit',unitsFor())}{input('name','Department name')}{input('source_title','Official source title')}{input('source_url','Official source URL')}<button className="rounded-lg bg-black px-4 py-3 text-white">Create department</button></form></section>
   <section className="rounded-xl border p-5"><h2 className="mb-3 font-semibold">Programme</h2><form onSubmit={e=>post('/admin/education/school-admission/programmes',e)} className="space-y-3">{select('institution_id','Institution',institutions)}{select('academic_unit_id','Academic Unit',unitsFor())}{select('department_id','Department',departmentsFor())}{input('name','Programme / Course')}{input('official_title','Official programme title')}{input('award_type','Award e.g. B.Sc.')}{input('source_title','Official source title')}{input('source_url','Official source URL')}<button className="rounded-lg bg-black px-4 py-3 text-white">Create programme</button></form></section>
  </div>}

  {tab==='sessions'&&<section className="rounded-xl border p-5"><h2 className="mb-3 font-semibold">Academic Sessions</h2><form onSubmit={e=>post('/admin/education/school-admission/sessions',e)} className="grid gap-3 md:grid-cols-4">{input('name','2026/2027')}{input('start_year','Start year','number')}{input('end_year','End year','number')}<button className="rounded-lg bg-black px-4 py-3 text-white">Add session</button></form><div className="mt-5 grid gap-2 md:grid-cols-3">{sessions.map((s:Any)=><div key={s.id} className="rounded-lg border p-3"><b>{s.name}</b><div className="text-sm opacity-70">{s.start_year}–{s.end_year} · {s.status}</div></div>)}</div></section>}

  {tab==='admissions'&&<section className="space-y-5 rounded-xl border p-5"><div><h2 className="font-semibold">Programme Admission Research Record</h2><p className="text-sm opacity-70">Create a session-specific record. Publication is blocked until structured requirements are researched, sourced and verified.</p></div>
   <form onSubmit={e=>post('/admin/education/school-admission/programme-admissions',e)} className="grid gap-3 md:grid-cols-2">{select('programme_id','Programme',programmes,programmeLabel)}{select('academic_session_id','Academic Session',sessions)}{input('source_title','Official source title')}{input('official_source_url','Official source URL')}{input('source_published_at','Source publication date','date')}{input('effective_from','Effective from','date')}{input('effective_until','Effective until','date')}{bool('utme_available','UTME available')}{bool('direct_entry_available','Direct Entry available')}{bool('first_choice_required','First choice required')}<textarea value={form.general_notes??''} onChange={e=>set('general_notes',e.target.value)} placeholder="General official admission notes" className="min-h-24 rounded-lg border p-3 md:col-span-2"/><button className="rounded-lg bg-black px-4 py-3 text-white md:col-span-2">Save as researched</button></form>
   <div className="space-y-2">{(admissions?.data??[]).map((a:Any)=><div key={a.id} className="rounded-lg border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><b>{admissionLabel(a)}</b><div className="text-sm opacity-70">{a.verification_status} · {a.admission_status} · requirements: {a.requirements_count??'—'}</div></div><div className="flex flex-wrap gap-2">{a.verification_status!=='verified'&&a.verification_status!=='published'&&<button onClick={()=>router.post(`/admin/education/school-admission/programme-admissions/${a.id}/verify`)} className="rounded border px-3 py-2 text-sm">Verify</button>}{a.verification_status==='verified'&&<button onClick={()=>router.post(`/admin/education/school-admission/programme-admissions/${a.id}/publish`)} className="rounded bg-black px-3 py-2 text-sm text-white">Publish</button>}{a.verification_status!=='archived'&&<button onClick={()=>router.post(`/admin/education/school-admission/programme-admissions/${a.id}/archive`)} className="rounded border px-3 py-2 text-sm">Archive</button>}</div></div></div>)}</div>
  </section>}

  {tab==='requirements'&&<section className="rounded-xl border p-5"><h2 className="mb-1 font-semibold">Structured Admission Requirements</h2><p className="mb-4 text-sm opacity-70">Enter only researched facts from an official source. Comma-separated fields are stored as structured child records, not past questions.</p><form onSubmit={e=>post('/admin/education/school-admission/requirements',e)} className="grid gap-3 md:grid-cols-2">
   {select('programme_admission_id','Programme admission',admissions?.data??[],admissionLabel)}{select('admission_route_id','Admission route',admissionRoutes)}
   {input('candidate_type','Candidate type e.g. UTME / DE')}{input('minimum_age','Minimum age','number')}{input('maximum_age','Maximum age','number')}{input('age_reference_date','Age reference date','date')}{input('minimum_utme_score','Minimum UTME score','number')}{input('minimum_o_level_credit_count','Minimum O-Level credits','number')}{input('maximum_o_level_sittings','Maximum O-Level sittings','number')}{input('post_utme_minimum_score','Minimum Post-UTME score','number')}
   {bool('awaiting_result_allowed','Awaiting result allowed')}{bool('post_utme_required','Post-UTME required')}{bool('screening_required','Screening required')}
   <textarea value={form.olevel_subjects??''} onChange={e=>set('olevel_subjects',e.target.value)} placeholder="O-Level required subjects, comma-separated" className="min-h-20 rounded-lg border p-3 md:col-span-2"/>
   <textarea value={form.utme_subjects??''} onChange={e=>set('utme_subjects',e.target.value)} placeholder="UTME subjects, comma-separated" className="min-h-20 rounded-lg border p-3 md:col-span-2"/>
   <textarea value={form.direct_entry_qualifications??''} onChange={e=>set('direct_entry_qualifications',e.target.value)} placeholder="Direct Entry qualification types, comma-separated" className="min-h-20 rounded-lg border p-3 md:col-span-2"/>
   <textarea value={form.result_bodies??''} onChange={e=>set('result_bodies',e.target.value)} placeholder="Accepted result bodies, comma-separated" className="min-h-20 rounded-lg border p-3 md:col-span-2"/>
   {input('source_title','Official requirement source title')}{input('source_url','Official requirement source URL')}{input('source_published_at','Source publication date','date')}
   <textarea value={form.notes??''} onChange={e=>set('notes',e.target.value)} placeholder="Research notes / special conditions" className="min-h-20 rounded-lg border p-3 md:col-span-2"/>
   <button className="rounded-lg bg-black px-4 py-3 text-white md:col-span-2">Save researched requirement</button>
  </form></section>}

  {tab==='cutoffs'&&<section className="rounded-xl border p-5"><h2 className="mb-1 font-semibold">Admission Cut-offs</h2><p className="mb-4 text-sm opacity-70">Store official published cut-off values with their source; never invent departmental or aggregate scores.</p><form onSubmit={e=>post('/admin/education/school-admission/cutoffs',e)} className="grid gap-3 md:grid-cols-2">{select('programme_admission_id','Programme admission',admissions?.data??[],admissionLabel)}{input('cutoff_type','Cut-off type e.g. UTME / departmental')}{input('score','Score','number')}{input('score_scale','Score scale','number')}{input('candidate_category','Candidate category')}{input('source_title','Official source title')}{input('source_url','Official source URL')}<textarea value={form.notes??''} onChange={e=>set('notes',e.target.value)} placeholder="Notes" className="rounded-lg border p-3 md:col-span-2"/><button className="rounded-lg bg-black px-4 py-3 text-white md:col-span-2">Save cut-off</button></form></section>}

  {tab==='screening'&&<section className="rounded-xl border p-5"><h2 className="mb-1 font-semibold">Screening Rules</h2><p className="mb-4 text-sm opacity-70">Capture official post-UTME/screening requirements and dates only when supported by the cited source.</p><form onSubmit={e=>post('/admin/education/school-admission/screening',e)} className="grid gap-3 md:grid-cols-2">{select('programme_admission_id','Programme admission',admissions?.data??[],admissionLabel)}{input('screening_type','Screening type')}{input('minimum_score','Minimum score','number')}{input('screening_url','Official screening URL')}{input('start_date','Start date','date')}{input('end_date','End date','date')}{bool('required','Screening required')}{bool('registration_required','Registration required')}{bool('first_choice_required','First choice required')}{bool('result_upload_required','Result upload required')}{input('source_title','Official source title')}{input('source_url','Official source URL')}<textarea value={form.notes??''} onChange={e=>set('notes',e.target.value)} placeholder="Notes" className="rounded-lg border p-3 md:col-span-2"/><button className="rounded-lg bg-black px-4 py-3 text-white md:col-span-2">Save screening rule</button></form></section>}
 </main></>;
}
