import { Head } from '@inertiajs/react';
import { useState } from 'react';

type Promotion={id:number;advertiser_name?:string|null;package_name?:string|null;target_label?:string|null;target_type:string;target_id:number;status:string;payment_status:string;price_minor:string|number;currency:string;created_at:string;advertiser_note?:string|null;admin_note?:string|null};
type Package={id:number;key:string;name:string;description?:string|null;duration_days:number;price_minor:string|number;currency:string;priority_weight:number;is_active:boolean|number};
type Props={promotions:Promotion[];packages:Package[]};
function csrf(){const c=document.cookie.split('; ').find(v=>v.startsWith('XSRF-TOKEN='));return c?decodeURIComponent(c.split('=').slice(1).join('=')):'';}
async function send(url:string,method:string,body:unknown){return fetch(url,{method,credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/json','X-XSRF-TOKEN':csrf()},body:JSON.stringify(body)});}
function money(v:string|number,currency='NGN'){return new Intl.NumberFormat('en-NG',{style:'currency',currency,maximumFractionDigits:2}).format(Number(v||0)/100);}
export default function Promotions({promotions,packages}:Props){
 const [message,setMessage]=useState('');const [busy,setBusy]=useState<number|null>(null);const [packageBusy,setPackageBusy]=useState(false);
 const [form,setForm]=useState({key:'',name:'',description:'',duration_days:7,price_minor:'500000',currency:'NGN',priority_weight:1,is_active:false});
 const review=async(id:number,decision:'approve'|'reject'|'pause')=>{const note=window.prompt('Enter a review note (minimum 5 characters):');if(!note||note.trim().length<5){setMessage('A review note is required.');return;}setBusy(id);setMessage('');try{const res=await send('/admin/ads/promotions/'+id+'/review','POST',{decision,admin_note:note});const d=await res.json();setMessage(d.message||'Review saved');if(res.ok)window.location.reload();}catch{setMessage('Could not save review.');}finally{setBusy(null);}};
 const create=async()=>{if(!form.key.trim()||!form.name.trim()){setMessage('Package key and name are required.');return;}setPackageBusy(true);setMessage('');try{const res=await send('/admin/ads/promotions/packages','POST',{...form,price_minor:Number(form.price_minor)});const d=await res.json();setMessage(d.message||'Package saved');if(res.ok)window.location.reload();}catch{setMessage('Could not create package.');}finally{setPackageBusy(false);}};
 const toggle=async(p:Package)=>{setMessage('');try{const res=await send('/admin/ads/promotions/packages/'+p.id,'PATCH',{name:p.name,description:p.description||'',duration_days:p.duration_days,price_minor:Number(p.price_minor),priority_weight:p.priority_weight,is_active:!Boolean(p.is_active)});const d=await res.json();setMessage(d.message||'Package updated');if(res.ok)window.location.reload();}catch{setMessage('Could not update package.');}};
 const edit=async(p:Package)=>{const name=window.prompt('Package name',p.name);if(name===null)return;const duration=window.prompt('Duration in days',String(p.duration_days));if(duration===null)return;const price=window.prompt('Price in minor units (100 NGN = 10000)',String(p.price_minor));if(price===null)return;const priority=window.prompt('Priority weight (1-100)',String(p.priority_weight));if(priority===null)return;const description=window.prompt('Description',p.description||'');if(description===null)return;const values={name:name.trim(),duration_days:Number(duration),price_minor:Number(price),priority_weight:Number(priority),description,is_active:Boolean(p.is_active)};if(!values.name||!Number.isInteger(values.duration_days)||values.duration_days<1||values.duration_days>365||!Number.isInteger(values.price_minor)||values.price_minor<1||!Number.isInteger(values.priority_weight)||values.priority_weight<1||values.priority_weight>100){setMessage('Invalid package values. Duration must be 1–365 days, price must be positive, and priority must be 1–100.');return;}try{const res=await send('/admin/ads/promotions/packages/'+p.id,'PATCH',values);const d=await res.json();setMessage(d.message||'Package updated');if(res.ok)window.location.reload();}catch{setMessage('Could not edit package.');}};
 return <><Head title="Marketplace Boosts"/><main className="mx-auto max-w-7xl space-y-6 p-4 md:p-6">
 <header><p className="text-sm font-semibold uppercase tracking-wide text-slate-500">SEMIZZY ONE · Ads & Monetization</p><h1 className="mt-1 text-2xl font-bold">Marketplace Boosts</h1><p className="mt-2 text-sm text-slate-500">Manage seller requests and configure promotion packages. An unpaid boost cannot be approved for delivery.</p><a href="/admin/ads" className="mt-3 inline-block text-sm underline">← Back to Ads & Monetization</a></header>
 {message&&<div role="status" className="rounded-lg border p-3 text-sm">{message}</div>}
 <section className="space-y-3 rounded-xl border p-4 md:p-5"><h2 className="text-lg font-bold">Seller boost requests ({promotions.length})</h2>{promotions.length===0?<p className="text-sm text-slate-500">No boost requests submitted yet.</p>:<div className="space-y-3">{promotions.map(p=><article key={p.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{p.target_label||'Marketplace listing'}</h3><p className="mt-1 text-xs text-slate-500">Seller: {p.advertiser_name||('User #'+p.id)} · Package: {p.package_name||'Unavailable'} · Target #{p.target_id}</p></div><div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full border px-2 py-1">{p.status.replaceAll('_',' ')}</span><span className="rounded-full border px-2 py-1">Payment: {p.payment_status}</span></div></div><div className="mt-3 flex flex-wrap gap-4 text-sm"><p>Price: <b>{money(p.price_minor,p.currency)}</b></p><p>Submitted: {new Date(p.created_at).toLocaleString()}</p><p>Target type: {p.target_type}</p></div>{p.advertiser_note&&<p className="mt-2 text-sm text-slate-500">Seller note: {p.advertiser_note}</p>}{p.admin_note&&<p className="mt-2 text-sm text-slate-500">Admin note: {p.admin_note}</p>}<div className="mt-3 flex flex-wrap gap-2">{p.status==='pending_review'&&<><button disabled={busy===p.id||p.payment_status!=='paid'} title={p.payment_status!=='paid'?'Payment settlement is required first':''} onClick={()=>review(p.id,'approve')} className="rounded-lg bg-slate-950 px-3 py-2 text-xs font-semibold text-white disabled:opacity-40">Approve (paid only)</button><button disabled={busy===p.id} onClick={()=>review(p.id,'reject')} className="rounded-lg border px-3 py-2 text-xs font-semibold">Reject</button></>}{['approved','active'].includes(p.status)&&<button disabled={busy===p.id} onClick={()=>review(p.id,'pause')} className="rounded-lg border px-3 py-2 text-xs font-semibold">Pause</button>}</div></article>)}</div>}</section>
 <section className="space-y-4 rounded-xl border p-4 md:p-5"><h2 className="text-lg font-bold">Promotion package manager</h2><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="p-2">Package</th><th className="p-2">Duration</th><th className="p-2">Price</th><th className="p-2">Priority</th><th className="p-2">Status</th><th className="p-2">Action</th></tr></thead><tbody>{packages.map(p=><tr key={p.id} className="border-b last:border-0"><td className="p-2"><b>{p.name}</b><div className="text-xs text-slate-500">{p.key}</div></td><td className="p-2">{p.duration_days} days</td><td className="p-2">{money(p.price_minor,p.currency)}</td><td className="p-2">{p.priority_weight}</td><td className="p-2">{Boolean(p.is_active)?'Available':'Disabled'}</td><td className="p-2"><div className="flex gap-2"><button onClick={()=>edit(p)} className="rounded-lg border px-3 py-2 text-xs font-semibold">Edit</button><button onClick={()=>toggle(p)} className="rounded-lg border px-3 py-2 text-xs font-semibold">{Boolean(p.is_active)?'Disable':'Enable'}</button></div></td></tr>)}{packages.length===0&&<tr><td colSpan={6} className="p-4 text-slate-500">No packages configured.</td></tr>}</tbody></table></div>
 <h3 className="font-semibold">Add package</h3><div className="grid gap-3 md:grid-cols-2"><label className="text-sm">Unique key<input value={form.key} onChange={e=>setForm({...form,key:e.target.value})} maxLength={80} placeholder="boost_7_days" className="mt-1 min-h-10 w-full rounded-lg border px-3"/></label><label className="text-sm">Package name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} maxLength={140} placeholder="7-day boost" className="mt-1 min-h-10 w-full rounded-lg border px-3"/></label><label className="text-sm">Duration (days)<input type="number" min={1} max={365} value={form.duration_days} onChange={e=>setForm({...form,duration_days:Number(e.target.value)})} className="mt-1 min-h-10 w-full rounded-lg border px-3"/></label><label className="text-sm">Price in minor units (₦100 = 10000)<input type="number" min={1} value={form.price_minor} onChange={e=>setForm({...form,price_minor:e.target.value})} className="mt-1 min-h-10 w-full rounded-lg border px-3"/></label><label className="text-sm">Priority weight<input type="number" min={1} max={100} value={form.priority_weight} onChange={e=>setForm({...form,priority_weight:Number(e.target.value)})} className="mt-1 min-h-10 w-full rounded-lg border px-3"/></label><label className="text-sm">Description<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} maxLength={1000} className="mt-1 min-h-10 w-full rounded-lg border px-3"/></label></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/>Make package available to sellers immediately</label><button disabled={packageBusy} onClick={create} className="rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{packageBusy?'Saving…':'Create package'}</button>
 </section><p className="text-xs text-slate-500">Package prices are stored as NGN minor units. Payment settlement, automated expiry, and live sponsored-listing delivery remain separate integrations and must be completed before paid boosts go live.</p>
 </main></>;
}
