import { Head } from '@inertiajs/react';
import { useState } from 'react';

type AdType = {
 id:number; key:string; name:string; description?:string|null; format_family:string;
 pricing_models:string[]|string; eligible_surfaces?:string[]|string|null;
 requires_creative:boolean|number; supports_targeting:boolean|number;
 requires_integration:boolean|number; integration_key?:string|null;
 is_system:boolean|number; is_active:boolean|number;
};
type Props={adTypes:AdType[]};
const families=['native','banner','listing','video','message','external','custom'];
const pricing=['cpc','cpm','flat','cpa','free'];
function csrf(){const c=document.cookie.split('; ').find(v=>v.startsWith('XSRF-TOKEN='));return c?decodeURIComponent(c.split('=').slice(1).join('=')):'';}
async function send(url:string,method:string,body:unknown){return fetch(url,{method,credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/json','X-XSRF-TOKEN':csrf()},body:JSON.stringify(body)});}
function parseList(v:string[]|string|null|undefined):string[]{if(Array.isArray(v))return v;if(typeof v==='string'){try{const x=JSON.parse(v);return Array.isArray(x)?x:[];}catch{return [];}}return [];}
export default function Types({adTypes}:Props){
 const [message,setMessage]=useState('');
 const [busy,setBusy]=useState(false);
 const [form,setForm]=useState({key:'',name:'',description:'',format_family:'native',pricing_models:['flat'],eligible_surfaces:'marketplace,home',requires_creative:true,supports_targeting:false,requires_integration:false,integration_key:''});
 const togglePrice=(p:string)=>setForm(s=>({...s,pricing_models:s.pricing_models.includes(p)?s.pricing_models.filter(x=>x!==p):[...s.pricing_models,p]}));
 const create=async()=>{if(!form.key.trim()||!form.name.trim()||form.pricing_models.length===0){setMessage('Enter a unique key, name and at least one pricing model.');return;}setBusy(true);setMessage('');try{const res=await send('/admin/ads/types','POST',{...form,eligible_surfaces:form.eligible_surfaces.split(',').map(x=>x.trim()).filter(Boolean)});const d=await res.json();setMessage(d.message||'Saved');if(res.ok)window.location.reload();}catch{setMessage('Could not save this ad type.');}finally{setBusy(false);}};
 const toggle=async(t:AdType)=>{const body={name:t.name,description:t.description||'',format_family:t.format_family,pricing_models:parseList(t.pricing_models),eligible_surfaces:parseList(t.eligible_surfaces),requires_creative:Boolean(t.requires_creative),supports_targeting:Boolean(t.supports_targeting),requires_integration:Boolean(t.requires_integration),integration_key:t.integration_key||'',is_active:!Boolean(t.is_active)};try{const res=await send('/admin/ads/types/'+t.id,'PATCH',body);const d=await res.json();setMessage(d.message||'Updated');if(res.ok)window.location.reload();}catch{setMessage('Could not update this ad type.');}};
 return <><Head title="Ad Types & Formats"/><main className="mx-auto max-w-6xl space-y-6 p-4 md:p-6">
 <header><p className="text-sm font-semibold uppercase tracking-wide text-slate-500">SEMIZZY ONE · Ads & Monetization</p><h1 className="mt-1 text-2xl font-bold">Ad Types & Formats</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">Extensible registry for current and future advertising formats. Add a format without changing the database schema; keep new formats disabled until delivery, billing and reporting support have been implemented and verified.</p><a href="/admin/ads" className="mt-3 inline-block text-sm underline">← Back to Ads & Monetization</a></header>
 {message&&<div role="status" className="rounded-lg border p-3 text-sm">{message}</div>}
 <section className="space-y-3 rounded-xl border p-4 md:p-5"><h2 className="text-lg font-bold">Registered ad types ({adTypes.length})</h2><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="p-2">Type</th><th className="p-2">Family</th><th className="p-2">Billing</th><th className="p-2">Integration</th><th className="p-2">Status</th><th className="p-2">Action</th></tr></thead><tbody>{adTypes.map(t=><tr key={t.id} className="border-b last:border-0"><td className="p-2"><b>{t.name}</b><div className="text-xs text-slate-500">{t.key}{Boolean(t.is_system)?' · Built-in':''}</div>{t.description&&<div className="mt-1 max-w-xs text-xs text-slate-500">{t.description}</div>}</td><td className="p-2">{t.format_family}</td><td className="p-2">{parseList(t.pricing_models).join(', ')||'Not set'}</td><td className="p-2">{Boolean(t.requires_integration)?(t.integration_key||'Required'): 'Not required'}</td><td className="p-2">{Boolean(t.is_active)?'Enabled':'Disabled'}</td><td className="p-2"><button onClick={()=>toggle(t)} className="rounded-lg border px-3 py-2 text-xs font-semibold">{Boolean(t.is_active)?'Disable':'Enable'}</button></td></tr>)}{adTypes.length===0&&<tr><td colSpan={6} className="p-4 text-slate-500">No ad types yet.</td></tr>}</tbody></table></div></section>
 <section className="space-y-4 rounded-xl border p-4 md:p-5"><div><h2 className="text-lg font-bold">Add a future ad type</h2><p className="text-sm text-slate-500">New types are created disabled and require review before they can be used in placements.</p></div>
 <div className="grid gap-3 md:grid-cols-2"><label className="text-sm">Unique key<input value={form.key} onChange={e=>setForm({...form,key:e.target.value})} maxLength={100} placeholder="sponsored_newsletter" className="mt-1 min-h-10 w-full rounded-lg border px-3"/></label><label className="text-sm">Display name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} maxLength={160} placeholder="Sponsored newsletter" className="mt-1 min-h-10 w-full rounded-lg border px-3"/></label><label className="text-sm">Format family<select value={form.format_family} onChange={e=>setForm({...form,format_family:e.target.value})} className="mt-1 min-h-10 w-full rounded-lg border px-3">{families.map(f=><option key={f} value={f}>{f}</option>)}</select></label><label className="text-sm">Eligible surfaces (comma-separated)<input value={form.eligible_surfaces} onChange={e=>setForm({...form,eligible_surfaces:e.target.value})} placeholder="home,marketplace,search" className="mt-1 min-h-10 w-full rounded-lg border px-3"/></label><label className="text-sm md:col-span-2">Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={2} maxLength={2000} className="mt-1 w-full rounded-lg border p-3"/></label></div>
 <fieldset><legend className="mb-2 text-sm font-semibold">Allowed pricing models</legend><div className="flex flex-wrap gap-3">{pricing.map(p=><label key={p} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.pricing_models.includes(p)} onChange={()=>togglePrice(p)}/>{p.toUpperCase()}</label>)}</div></fieldset>
 <div className="flex flex-wrap gap-4">{[['requires_creative','Requires ad creative'],['supports_targeting','Supports audience targeting'],['requires_integration','Needs a delivery integration']].map(([k,label])=><label key={k} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(form[k as keyof typeof form])} onChange={e=>setForm({...form,[k]:e.target.checked})}/>{label}</label>)}</div>
 {form.requires_integration&&<label className="block text-sm">Integration identifier<input value={form.integration_key} onChange={e=>setForm({...form,integration_key:e.target.value})} required maxLength={120} placeholder="newsletter.provider.v1" className="mt-1 min-h-10 w-full rounded-lg border px-3"/></label>}
 <button disabled={busy} onClick={create} className="rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy?'Saving…':'Add ad type (disabled)'}</button>
 </section><p className="text-xs text-slate-500">Registry configuration alone does not implement delivery. Custom/video/external formats must not serve ads or bill advertisers until their delivery adapter, consent handling, moderation and genuine event tracking are implemented.</p>
 </main></>;
}
