import { Head } from '@inertiajs/react';
import { useState } from 'react';

export default function Conversions({ requests, conversionSettings={}, conversionTypes={} }: { requests?: any; conversionSettings?: Record<string,{label?:string;rate_percent?:number|null;fee_minor?:string}>; conversionTypes?: Record<string,string> }) {
  const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
  const [account,setAccount]=useState('');
  const [settings,setSettings]=useState<Record<string,{rate_percent:string;fee:string}>>(()=>Object.fromEntries(Object.entries(conversionSettings).map(([k,v])=>[k,{rate_percent:String(v.rate_percent??''),fee:String((Number(v.fee_minor||0)/100)||0)}]))); const [selected,setSelected]=useState<number|null>(null);
  const csrf=()=>((document.querySelector('meta[name="csrf-token"]') as HTMLMetaElement|null)?.content||'');
  const saveSettings=async()=>{setBusy(true);setMessage('');try{const res=await fetch('/admin/vtu/conversions/settings',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':csrf()},body:JSON.stringify({settings})});const json=await res.json();if(!res.ok)throw new Error(json.message||'Settings could not be saved.');setMessage('Conversion rates saved.');}catch(e){setMessage(e instanceof Error?e.message:'Settings could not be saved.')}finally{setBusy(false)}};
  const act=async(path:string,body:Record<string,string>)=>{
    setBusy(true); setMessage('');
    try { const res=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':csrf()},body:JSON.stringify(body)}); const json=await res.json(); if(!res.ok) throw new Error(json.message||'Action failed.'); setMessage('Updated '+(json.data?.reference||'request')); location.reload(); }
    catch(e){setMessage(e instanceof Error?e.message:'Action failed.');} finally{setBusy(false);}
  };
  const rows=requests?.data||[];
  return <main className="min-h-screen bg-slate-50 p-6"><Head title="VTU Conversions" /><div className="mx-auto max-w-7xl">
    <h1 className="text-3xl font-black">Manual VTU Conversions</h1><p className="mt-2 text-sm text-slate-600">Verify the incoming airtime/data before any wallet credit. No provider API is required.</p>
    <div className="mt-6 rounded-2xl bg-white p-5 ring-1 ring-slate-200"><h2 className="text-xl font-black">Conversion rates & fees</h2><p className="mt-1 text-sm text-slate-500">Rates are server-authoritative. Users cannot submit their own rate or fee.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(conversionTypes).map(([key,label])=><div key={key} className="rounded-xl border p-4"><p className="font-bold">{label}</p><label className="mt-3 block text-xs font-bold">Rate %<input value={settings[key]?.rate_percent??''} onChange={e=>setSettings(s=>({...s,[key]:{...(s[key]||{fee:'0'}),rate_percent:e.target.value}}))} className="mt-1 w-full rounded-lg border p-2"/></label><label className="mt-2 block text-xs font-bold">Fee ₦<input value={settings[key]?.fee??'0'} onChange={e=>setSettings(s=>({...s,[key]:{...(s[key]||{rate_percent:''}),fee:e.target.value}}))} className="mt-1 w-full rounded-lg border p-2"/></label></div>)}</div><button disabled={busy} onClick={saveSettings} className="mt-4 rounded-xl bg-indigo-600 px-4 py-3 font-bold text-white disabled:opacity-50">Save conversion settings</button></div>
    {message&&<p className="mt-3 rounded-xl bg-white p-3 text-sm font-semibold ring-1 ring-slate-200">{message}</p>}
    <div className="mt-6 overflow-x-auto rounded-2xl bg-white ring-1 ring-slate-200"><table className="min-w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Reference</th><th className="p-3">User</th><th className="p-3">Type</th><th className="p-3">Source</th><th className="p-3">Target</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id} className="border-b"><td className="p-3 font-semibold">{r.reference}</td><td className="p-3">{r.user?.name||r.user?.username||r.user_id}</td><td className="p-3">{r.conversion_type}</td><td className="p-3">{r.source_amount_minor}</td><td className="p-3">{r.target_amount_minor}</td><td className="p-3">{r.status}</td><td className="p-3">{r.status==='pending'&&<button disabled={busy} onClick={()=>{setSelected(r.id); setAccount('');}} className="rounded-lg bg-slate-900 px-3 py-2 text-white">Verify</button>}{r.status==='verified'&&<button disabled={busy} onClick={()=>act('/admin/vtu/conversions/'+r.id+'/approve',{})} className="rounded-lg bg-emerald-600 px-3 py-2 text-white">Approve & Credit</button>}</td></tr>)}</tbody></table></div>
    {selected&&<div className="fixed inset-0 grid place-items-center bg-black/40 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-5"><h2 className="text-xl font-black">Verify receiving account</h2><input value={account} onChange={e=>setAccount(e.target.value)} placeholder="Receiving number/account" className="mt-4 w-full rounded-xl border p-3"/><div className="mt-4 flex gap-2"><button onClick={()=>setSelected(null)} className="flex-1 rounded-xl border p-3">Cancel</button><button disabled={busy||!account} onClick={async()=>{await act('/admin/vtu/conversions/'+selected+'/verify',{receiving_account:account});setSelected(null)}} className="flex-1 rounded-xl bg-slate-950 p-3 font-bold text-white">Verify</button></div></div></div>}
  </div></main>;
}