import { Head, Link } from '@inertiajs/react';

type Tx={id:number;reference:string;status:string;amount_minor:string;currency:string;service?:{name:string}|null;product?:{name:string}|null;user?:{name:string;email:string}|null};
type Provider={id:number;display_name:string;priority:number;enabled:boolean;paused:boolean;verification_status:string;integration_status:string;enabled_mappings_count:number};
type Props={metrics:Record<string,number>;catalogue:Record<string,number>;providers:Record<string,number>;attention:Record<string,number>;recentTransactions:Tx[];providerHealth:Provider[]};
const statusClass=(s:string)=>({successful:'bg-emerald-50 text-emerald-700',failed:'bg-red-50 text-red-700',pending:'bg-amber-50 text-amber-700',processing:'bg-blue-50 text-blue-700',reversed:'bg-violet-50 text-violet-700'}[s]??'bg-slate-100 text-slate-700');
const providerState=(p:Provider)=>p.paused?'Paused':!p.enabled?'Disabled':p.verification_status!=='live_verified'||p.integration_status!=='live_verified'?'Verification required':'Ready';
const money=(minor:string,currency='NGN')=>{const n=Number(minor);return Number.isFinite(n)?new Intl.NumberFormat(undefined,{style:'currency',currency}).format(n/100):'—'};
export default function Dashboard({metrics,catalogue,providers,attention,recentTransactions,providerHealth}:Props){const stats=[['Transactions',metrics.total],['Successful',metrics.successful],['Pending / Processing',metrics.pending],['Failed',metrics.failed],['Reversed',metrics.reversed],['Today',metrics.today]];return <><Head title="VTU Control Dashboard"/><div className="space-y-6 p-4 md:p-6">
<div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-slate-500">VTU & Digital Services</p><h1 className="mt-1 text-2xl font-bold md:text-3xl">Control Dashboard</h1><p className="mt-1 text-sm text-slate-500">Live operational view of catalogue, providers, transactions and reconciliation.</p></div><div className="flex flex-wrap gap-2">{[['Services','/admin/vtu/services'],['Products','/admin/vtu/products'],['Mappings','/admin/vtu/mappings'],['Transactions','/admin/vtu/transactions'],['Bulk','/admin/vtu/bulk']].map(([l,u])=><Link key={u} href={u} className="rounded-lg border bg-white px-3 py-2 text-xs font-bold">{l}</Link>)}</div></div>
<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{stats.map(([l,v])=><div key={l} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="text-xs font-bold uppercase tracking-wide text-slate-500">{l}</div><div className="mt-2 text-2xl font-bold">{v}</div></div>)}</div>
<div className="grid gap-4 lg:grid-cols-3"><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between"><h2 className="font-bold">Catalogue</h2><Link href="/admin/vtu/services" className="text-xs font-bold text-blue-600">Manage</Link></div><div className="mt-4 grid grid-cols-2 gap-3">{[['Active services',catalogue.services_active+'/'+catalogue.services_total],['Active products',catalogue.products_active+'/'+catalogue.products_total],['Active mappings',catalogue.mappings_active]].map(([l,v])=><div key={l} className="rounded-xl bg-slate-50 p-3"><div className="text-xs text-slate-500">{l}</div><div className="mt-1 font-bold">{v}</div></div>)}</div></section>
<section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between"><h2 className="font-bold">Provider Network</h2><Link href="/admin/providers" className="text-xs font-bold text-blue-600">Manage</Link></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-emerald-50 p-3"><div className="text-xs text-emerald-700">Eligible</div><div className="mt-1 font-bold">{providers.eligible}</div></div><div className="rounded-xl bg-slate-50 p-3"><div className="text-xs text-slate-500">Total</div><div className="mt-1 font-bold">{providers.total}</div></div><div className="rounded-xl bg-amber-50 p-3"><div className="text-xs text-amber-700">Paused</div><div className="mt-1 font-bold">{providers.paused}</div></div><div className="rounded-xl bg-red-50 p-3"><div className="text-xs text-red-700">Attention</div><div className="mt-1 font-bold">{providers.needs_attention}</div></div></div></section>
<section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold">Operational Attention</h2><div className="mt-4 space-y-2">{[['Pending transactions',attention.pending_transactions,'/admin/vtu/transactions'],['Failed last 24h',attention.failed_last_24h,'/admin/vtu/transactions'],['Refund reconciliation',attention.refund_reconciliation,'/admin/vtu/transactions'],['Bulk operations',attention.bulk_operations,'/admin/vtu/bulk']].map(([l,v,u])=><Link key={l} href={u as string} className="flex items-center justify-between rounded-xl border p-3"><span className="text-sm text-slate-600">{l}</span><span className={Number(v)>0?'font-bold text-red-600':'font-bold text-emerald-600'}>{v}</span></Link>)}</div></section></div>
<div className="grid gap-4 xl:grid-cols-5"><section className="overflow-hidden rounded-2xl border bg-white shadow-sm xl:col-span-3"><div className="flex justify-between border-b p-5"><div><h2 className="font-bold">Recent Transactions</h2><p className="text-xs text-slate-500">Real records only.</p></div><Link href="/admin/vtu/transactions" className="text-xs font-bold text-blue-600">View all</Link></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Reference</th><th className="p-3">Service</th><th className="p-3">Amount</th><th className="p-3">Status</th></tr></thead><tbody>{recentTransactions.map(t=><tr key={t.id} className="border-t"><td className="p-3"><div className="font-mono text-xs font-bold">{t.reference}</div><div className="text-xs text-slate-500">{t.user?.name??t.user?.email??'—'}</div></td><td className="p-3">{t.product?.name??t.service?.name??'—'}</td><td className="p-3 font-medium">{money(t.amount_minor,t.currency)}</td><td className="p-3"><span className={'rounded-full px-2 py-1 text-xs font-bold '+statusClass(t.status)}>{t.status}</span></td></tr>)}</tbody></table>{!recentTransactions.length&&<div className="p-10 text-center text-sm text-slate-500">No VTU transactions yet.</div>}</div></section>
<section className="overflow-hidden rounded-2xl border bg-white shadow-sm xl:col-span-2"><div className="border-b p-5"><h2 className="font-bold">Provider Health</h2><p className="text-xs text-slate-500">Operational state only; credentials are never exposed.</p></div><div className="divide-y">{providerHealth.map(p=>{const s=providerState(p);return <div key={p.id} className="flex items-center justify-between gap-3 p-4"><div className="min-w-0"><div className="truncate text-sm font-bold">{p.display_name}</div><div className="text-xs text-slate-500">P{p.priority} · {p.enabled_mappings_count} mapping(s)</div></div><span className={'rounded-full px-2 py-1 text-xs font-bold '+(s==='Ready'?'bg-emerald-50 text-emerald-700':s==='Paused'?'bg-amber-50 text-amber-700':'bg-red-50 text-red-700')}>{s}</span></div>})}{!providerHealth.length&&<div className="p-8 text-center text-sm text-slate-500">No providers configured.</div>}</div></section></div>
</div></>}