<?php

return [
    'identifier'=>'vtu.digital-services',
    'name'=>'VTU & Digital Services',
    'version'=>'1.2.0',
    'compatibility'=>'>=2.0.0',
    'dependencies'=>[],
    'permissions'=>['vtu.view','vtu.services.manage','vtu.products.manage','vtu.providers.manage','vtu.mappings.manage','vtu.transactions.view','vtu.transactions.manage','vtu.bulk.manage','vtu.requery','vtu.refunds.manage','vtu.settings.manage','vtu.conversions.view','vtu.conversions.manage'],
    'navigation'=>[
        ['id'=>'vtu-control','label'=>'VTU Control Center','url'=>'/admin/vtu','icon'=>'server','permission'=>'vtu.view','section'=>'addons','order'=>10],
        ['id'=>'vtu-services','label'=>'VTU Services','url'=>'/admin/vtu/services','icon'=>'catalogue','permission'=>'vtu.services.manage','section'=>'addons','order'=>11],
        ['id'=>'vtu-products','label'=>'VTU Products','url'=>'/admin/vtu/products','icon'=>'catalogue','permission'=>'vtu.products.manage','section'=>'addons','order'=>12],
        ['id'=>'vtu-mappings','label'=>'VTU Mappings','url'=>'/admin/vtu/mappings','icon'=>'catalogue','permission'=>'vtu.mappings.manage','section'=>'addons','order'=>13],
        ['id'=>'vtu-transactions','label'=>'VTU Transactions','url'=>'/admin/vtu/transactions','icon'=>'audit','permission'=>'vtu.transactions.view','section'=>'addons','order'=>14],
        ['id'=>'vtu-bulk','label'=>'VTU Bulk Operations','url'=>'/admin/vtu/bulk','icon'=>'settings','permission'=>'vtu.bulk.manage','section'=>'addons','order'=>15],
        ['id'=>'vtu-conversions','label'=>'Manual Conversions','url'=>'/admin/vtu/conversions','icon'=>'exchange','permission'=>'vtu.conversions.view','section'=>'addons','order'=>16],
    ],
    'settings'=>[],
    'migrations'=>['2026_10_05_000026_create_vtu_addon_tables.php','2026_10_05_000027_add_vtu_bulk_idempotency.php','2026_10_08_090000_create_vtu_conversion_requests.php'],
    'installer'=>'App\\Services\\Vtu\\VtuAddonInstaller',
    'web_route_files'=>['addons/vtu.digital-services/routes/web.php','addons/vtu.digital-services/routes/admin.php'],
    'api_route_files'=>['addons/vtu.digital-services/routes/api.php'],
    'routes'=>['/vtu','/vtu/conversions'],
    'api_routes'=>['/api/v1/vtu'],
    'services'=>['airtime','data','airtime_to_cash','airtime_to_data','data_to_cash','data_to_airtime','bulk_airtime','bulk_data','broadband_isp','international_airtime','international_data','electricity','cable_tv','digital_subscriptions','gaming','education_digital_products','data_plan_catalogue','provider_requery','refunds','transaction_tracking'],
    'capabilities'=>[
        ['name'=>'airtime_purchase','execution_mode'=>'api_or_provider','api_exposed'=>true],
        ['name'=>'data_purchase','execution_mode'=>'api_or_provider','api_exposed'=>true],
        ['name'=>'airtime_to_cash','execution_mode'=>'manual_verification','api_exposed'=>false],
        ['name'=>'airtime_to_data','execution_mode'=>'manual_verification','api_exposed'=>false],
        ['name'=>'data_to_cash','execution_mode'=>'manual_verification','api_exposed'=>false],
        ['name'=>'data_to_airtime','execution_mode'=>'manual_verification','api_exposed'=>false],
        ['name'=>'bulk_airtime','execution_mode'=>'api_or_provider','api_exposed'=>true],
        ['name'=>'bulk_data','execution_mode'=>'api_or_provider','api_exposed'=>true],
        ['name'=>'broadband_isp','execution_mode'=>'api_or_provider','api_exposed'=>true],
        ['name'=>'international_airtime','execution_mode'=>'api_or_provider','api_exposed'=>true],
        ['name'=>'international_data','execution_mode'=>'api_or_provider','api_exposed'=>true],
        ['name'=>'electricity','execution_mode'=>'api_or_manual','api_exposed'=>true],
        ['name'=>'cable_tv','execution_mode'=>'api_or_manual','api_exposed'=>true],
        ['name'=>'digital_subscriptions','execution_mode'=>'api_or_manual','api_exposed'=>true],
        ['name'=>'gaming','execution_mode'=>'api_or_manual','api_exposed'=>true],
        ['name'=>'education_digital_products','execution_mode'=>'api_or_manual','api_exposed'=>true],
        ['name'=>'data_plan_catalogue','execution_mode'=>'provider_api','api_exposed'=>true],
        ['name'=>'transaction_requery','execution_mode'=>'provider_api','api_exposed'=>true],
        ['name'=>'refund','execution_mode'=>'provider_or_manual','api_exposed'=>true],
        ['name'=>'transaction_tracking','execution_mode'=>'core','api_exposed'=>true],
    ],
    'provider_integrations'=>['Core ProviderManager'],
    'scheduled_tasks'=>['pending transaction reconciliation'],
    'events'=>['vtu.transaction.created','vtu.transaction.completed','vtu.transaction.failed','vtu.transaction.refunded','vtu.conversion.submitted','vtu.conversion.verified','vtu.conversion.completed','vtu.conversion.rejected'],
];