<?php

return [
    'identifier' => 'api.provider-platform',
    'name' => 'Developer & API Provider Platform',
    'version' => '0.2.0',
    'description' => 'Phase A: service-by-service oversight of SEMIZZY ONE outbound API providers using the existing Core provider engine. The separate inbound Developer API Platform is reserved for Phase B.',
    'category' => 'Platform Infrastructure',
    'autoload_namespace' => 'Semizzy\\Addons\\ApiProviderPlatform',
    'compatibility' => '>=2.0.0',
    'dependencies' => [],
    'permissions' => ['provider_platform.view', 'provider_platform.manage'],
    'role_permissions' => [
        'ADMIN' => ['provider_platform.view', 'provider_platform.manage'],
        'STAFF' => ['provider_platform.view'],
        'SUPPORT' => ['provider_platform.view'],
        'USER' => [],
    ],
    'admin_navigation' => [[
        'id' => 'admin-api-provider-platform',
        'label' => 'API Provider Coverage',
        'url' => '/admin/provider-platform',
        'icon' => 'network',
        'permission' => 'provider_platform.view',
        'section' => 'addons',
        'order' => 170,
    ]],
    'settings' => [['key' => 'enabled', 'type' => 'boolean', 'default' => false]],
    'migrations' => [],
    'web_route_files' => ['addons/api.provider-platform/routes/admin.php'],
    'api_route_files' => [],
    'routes' => ['/admin/provider-platform', '/admin/provider-platform/catalogue/review', '/admin/provider-platform/catalogue', '/admin/provider-platform/catalogue/{providerService}/select', '/admin/provider-platform/products/{product}/publish', '/admin/provider-platform/products/{product}/unpublish'],
    'api_routes' => [],
    'provider_integrations' => [
        'Core ApiProvider registry',
        'Core ProviderServiceMapping',
        'Core ProviderServiceProduct',
        'Core ProviderManager and capability registry',
        'Core provider health, operation logs and audit services',
    ],
    'provider_capabilities' => [],
    'capabilities' => [
        'outbound_provider_coverage',
        'service_by_service_verification_visibility',
        'provider_gap_reporting',
        'guarded_product_publication',
        'audited_product_publish_unpublish',
        'live_provider_and_tier_price_readiness_checks',
    ],
];
