<?php
namespace Semizzy\Addons\AIChatbot\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Services\Audit\AuditLogger;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use Inertia\Inertia;
use Semizzy\Addons\AIChatbot\Services\AIProviderService;
class AIChatbotAdminController extends Controller {
 public function index(){return Inertia::render('Admin/AIChatbot',['settings'=>$this->settings(),'providers'=>DB::table('ai_chatbot_providers')->orderBy('priority')->get()->map(fn($p)=>['id'=>$p->id,'name'=>$p->name,'driver'=>$p->driver,'model'=>$p->model,'enabled'=>(bool)$p->enabled,'priority'=>$p->priority,'hasKey'=>(bool)$p->api_key_encrypted,'lastTestStatus'=>$p->last_test_status,'lastTestMessage'=>$p->last_test_message]),'knowledge'=>DB::table('ai_chatbot_knowledge')->orderByDesc('updated_at')->limit(50)->get(),'stats'=>['conversations'=>DB::table('ai_chatbot_conversations')->count(),'messages'=>DB::table('ai_chatbot_messages')->count(),'knowledgeItems'=>DB::table('ai_chatbot_knowledge')->count(),'enabledProviders'=>DB::table('ai_chatbot_providers')->where('enabled',true)->count()]]);}
 public function storeProvider(Request $r,AuditLogger $audit){$d=$r->validate(['name'=>['required','string','max:120'],'driver'=>['required',Rule::in(['openai','anthropic','gemini'])],'model'=>['required','string','max:160'],'api_key'=>['required','string','max:4096'],'enabled'=>['sometimes','boolean'],'priority'=>['nullable','integer','min:1','max:10000'],'timeout_seconds'=>['nullable','integer','min:5','max:60'],'max_output_tokens'=>['nullable','integer','min:32','max:4000']]);$id=DB::table('ai_chatbot_providers')->insertGetId(['name'=>$d['name'],'driver'=>$d['driver'],'model'=>$d['model'],'api_key_encrypted'=>Crypt::encryptString($d['api_key']),'enabled'=>(bool)($d['enabled']??false),'priority'=>$d['priority']??100,'timeout_seconds'=>$d['timeout_seconds']??20,'max_output_tokens'=>$d['max_output_tokens']??600,'created_at'=>now(),'updated_at'=>now()]);try{$audit->record('ai_chatbot.provider.created',null,['provider_id'=>$id,'driver'=>$d['driver']],$r);}catch(\Throwable $e){report($e);}return back()->with('success','Provider added. Test the connection before relying on it.');}
 public function updateProvider(Request $r,int $provider,AuditLogger $audit){abort_unless(DB::table('ai_chatbot_providers')->where('id',$provider)->exists(),404);$d=$r->validate(['name'=>['sometimes','required','string','max:120'],'driver'=>['sometimes','required',Rule::in(['openai','anthropic','gemini'])],'model'=>['sometimes','required','string','max:160'],'api_key'=>['nullable','string','max:4096'],'enabled'=>['sometimes','boolean'],'priority'=>['sometimes','integer','min:1','max:10000'],'timeout_seconds'=>['sometimes','integer','min:5','max:60'],'max_output_tokens'=>['sometimes','integer','min:32','max:4000']]);$changes=[];foreach(['name','driver','model','enabled','priority','timeout_seconds','max_output_tokens'] as $k)if(array_key_exists($k,$d))$changes[$k]=$d[$k];if(!empty($d['api_key']))$changes['api_key_encrypted']=Crypt::encryptString($d['api_key']);$changes['updated_at']=now();DB::table('ai_chatbot_providers')->where('id',$provider)->update($changes);try{$audit->record('ai_chatbot.provider.updated',null,['provider_id'=>$provider,'fields'=>array_keys($changes)],$r);}catch(\Throwable $e){report($e);}return back()->with('success','Provider settings saved.');}
 public function testProvider(int $provider,AIProviderService $service){$p=DB::table('ai_chatbot_providers')->find($provider);abort_unless($p,404);$result=$service->test((array)$p);DB::table('ai_chatbot_providers')->where('id',$provider)->update(['last_tested_at'=>now(),'last_test_status'=>$result['ok']?'success':'failed','last_test_message'=>$result['message'],'updated_at'=>now()]);return back()->with($result['ok']?'success':'error',$result['message']);}
 public function deleteProvider(int $provider,Request $r,AuditLogger $audit){$p=DB::table('ai_chatbot_providers')->find($provider);abort_unless($p,404);DB::table('ai_chatbot_providers')->where('id',$provider)->delete();try{$audit->record('ai_chatbot.provider.deleted',null,['provider_id'=>$provider,'driver'=>$p->driver],$r);}catch(\Throwable $e){report($e);}return back()->with('success','Provider removed.');}
 public function saveSettings(Request $r,AuditLogger $audit){$d=$r->validate(['enabled'=>['required','boolean'],'public_enabled'=>['required','boolean'],'assistant_name'=>['required','string','max:80'],'welcome_message'=>['required','string','max:500'],'allowed_paths'=>['required','array','max:50'],'allowed_paths.*'=>['string','max:255'],'excluded_paths'=>['required','array','max:50'],'excluded_paths.*'=>['string','max:255'],'retention_days'=>['required','integer','min:1','max:3650'],'max_message_chars'=>['required','integer','min:100','max:4000'],'max_context_messages'=>['required','integer','min:2','max:30']]);foreach($d as $k=>$v)DB::table('ai_chatbot_settings')->updateOrInsert(['key'=>$k],['value'=>json_encode($v),'created_at'=>now(),'updated_at'=>now()]);try{$audit->record('ai_chatbot.settings.updated',null,['keys'=>array_keys($d)],$r);}catch(\Throwable $e){report($e);}return back()->with('success','AI chatbot settings saved.');}
 public function storeKnowledge(Request $r){$d=$r->validate(['title'=>['required','string','max:180'],'category'=>['nullable','string','max:100'],'content'=>['required','string','max:30000'],'source_url'=>['nullable','url','max:2048'],'published'=>['sometimes','boolean']]);DB::table('ai_chatbot_knowledge')->insert(['title'=>$d['title'],'category'=>$d['category']??'general','content'=>$d['content'],'source_url'=>$d['source_url']??null,'published'=>(bool)($d['published']??false),'created_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Knowledge item saved.');}
 public function updateKnowledge(Request $r,int $item){abort_unless(DB::table('ai_chatbot_knowledge')->where('id',$item)->exists(),404);$d=$r->validate(['title'=>['sometimes','required','string','max:180'],'category'=>['sometimes','nullable','string','max:100'],'content'=>['sometimes','required','string','max:30000'],'source_url'=>['sometimes','nullable','url','max:2048'],'published'=>['sometimes','boolean']]);DB::table('ai_chatbot_knowledge')->where('id',$item)->update([...$d,'updated_at'=>now()]);return back()->with('success','Knowledge item updated.');}
 public function deleteKnowledge(int $item){abort_unless(DB::table('ai_chatbot_knowledge')->where('id',$item)->exists(),404);DB::table('ai_chatbot_knowledge')->where('id',$item)->delete();return back()->with('success','Knowledge item deleted.');}
 public function conversations(){ $rows=DB::table('ai_chatbot_conversations as c')->leftJoin('users as u','u.id','=','c.user_id')->leftJoin('ai_chatbot_messages as m',function($join){$join->on('m.conversation_id','=','c.id')->whereRaw('m.id = (select max(m2.id) from ai_chatbot_messages m2 where m2.conversation_id = c.id)');})->select('c.uuid','c.title','c.status','c.support_ticket_id','c.created_at','c.last_message_at','u.name as user_name','u.email as user_email','m.content as last_message')->orderByDesc('c.last_message_at')->paginate(30)->through(fn($row)=>['uuid'=>$row->uuid,'title'=>$row->title,'status'=>$row->status,'supportTicketId'=>$row->support_ticket_id,'createdAt'=>$row->created_at,'lastMessageAt'=>$row->last_message_at,'userName'=>$row->user_name,'userEmail'=>$row->user_email,'lastMessage'=>$row->last_message]); return Inertia::render('Admin/AIChatbotConversations',['conversations'=>$rows]); }
 public function conversation(string $uuid){$c=DB::table('ai_chatbot_conversations as c')->leftJoin('users as u','u.id','=','c.user_id')->where('c.uuid',$uuid)->select('c.*','u.name as user_name','u.email as user_email')->first();abort_unless($c,404);$messages=DB::table('ai_chatbot_messages')->where('conversation_id',$c->id)->orderBy('id')->limit(500)->get(['id','role','content','provider','model','input_tokens','output_tokens','created_at'])->map(fn($m)=>['id'=>$m->id,'role'=>$m->role,'content'=>$m->content,'provider'=>$m->provider,'model'=>$m->model,'inputTokens'=>$m->input_tokens,'outputTokens'=>$m->output_tokens,'createdAt'=>$m->created_at]);return Inertia::render('Admin/AIChatbotConversation',['conversation'=>['uuid'=>$c->uuid,'title'=>$c->title,'status'=>$c->status,'supportTicketId'=>$c->support_ticket_id,'createdAt'=>$c->created_at,'lastMessageAt'=>$c->last_message_at,'userName'=>$c->user_name,'userEmail'=>$c->user_email],'messages'=>$messages]);}
 private function settings():array{$d=['enabled'=>false,'public_enabled'=>true,'assistant_name'=>'SEMIZZY ONE Assistant','welcome_message'=>'Hello! How can I help you today?','allowed_paths'=>['/','/services','/pricing','/help','/dashboard'],'excluded_paths'=>['/login','/register','/wallet','/payments','/admin'],'retention_days'=>90,'max_message_chars'=>4000,'max_context_messages'=>12];foreach(DB::table('ai_chatbot_settings')->get() as $r)$d[$r->key]=json_decode((string)$r->value,true)??$r->value;return $d;}
}
