<?php

return [
    'identifier' => 'payments.gateway',
    'name' => 'Payments & Funding',
    'version' => '1.0.0',
    'compatibility' => '>=2.0.0',
    'dependencies' => [],
    'role_permissions' => [
        'ADMIN' => ['payments.view', 'payments.manage', 'payments.providers.manage', 'payments.refunds.manage', 'payments.webhooks.manage', 'payments.settings.manage', 'payments.manual_deposits.manage'],
        'STAFF' => ['payments.view', 'payments.refunds.manage'],
        'SUPPORT' => ['payments.view'],
        'USER' => ['payments.view', 'payments.create', 'payments.manual_deposits.create'],
    ],
    'permissions' => [
        'payments.view',
        'payments.create',
        'payments.manage',
        'payments.providers.manage',
        'payments.refunds.manage',
        'payments.webhooks.manage',
        'payments.settings.manage',
        'payments.manual_deposits.manage',
        'payments.manual_deposits.create',
    ],
    'navigation' => [
        [
            'id' => 'payments',
            'label' => 'Payments & Funding',
            'url' => '/admin/payments',
            'icon' => 'wallet',
            'permission' => 'payments.view',
            'section' => 'addons',
            'order' => 30,
        ],
        [
            'id' => 'manual-deposits',
            'label' => 'Manual NGN Deposits',
            'url' => '/admin/payments/manual-deposits',
            'icon' => 'banknote',
            'permission' => 'payments.manual_deposits.manage',
            'section' => 'addons',
            'order' => 31,
        ],
    ],
    'settings' => [
        ['key' => 'default_currency', 'type' => 'string', 'default' => 'NGN'],
        ['key' => 'payment_expiry_minutes', 'type' => 'integer', 'default' => 30],
        ['key' => 'auto_credit_verified_payments', 'type' => 'boolean', 'default' => true],
        ['key' => 'require_webhook_signature', 'type' => 'boolean', 'default' => true],
    ],
    'migrations' => [
        '2026_10_06_000300_create_payment_intents.php',
        '2026_10_06_000301_create_payment_webhook_events.php',
        '2026_10_06_000302_seed_payments_service.php',
        '2026_10_08_002000_create_payment_gateway_providers.php',
        '2026_10_08_002001_seed_payment_gateway_providers.php',
        '2026_10_08_002002_correct_payment_gateway_capabilities.php',
        '2026_10_08_002003_configure_ngn_gateway_adapters.php',
        '2026_10_08_002004_configure_flutterwave_adapter.php',
        '2026_10_08_002005_configure_opay_adapter.php',
        '2026_10_08_002006_configure_kora_adapter.php',
        '2026_10_08_002007_configure_squad_adapter.php',
        '2026_10_08_002008_harden_ngn_gateway_capabilities.php',
        '2026_10_08_002009_correct_opay_refund_capability.php',
        '2026_10_08_002010_add_reconciliation_metadata_to_payment_intents.php',
        '2026_10_08_002011_create_manual_deposit_tables.php',
    ],
    'web_route_files' => [
        'addons/payments.gateway/routes/web.php',
        'addons/payments.gateway/routes/admin.php',
    ],
    'api_route_files' => [
        'addons/payments.gateway/routes/api.php',
    ],
    'routes' => ['/payments'],
    'api_routes' => ['/api/v1/payments'],
    'services' => [
        'payment intent lifecycle',
        'wallet funding',
        'provider checkout integration',
        'separate payment gateway provider engine',
        'unlimited admin-addable payment gateway providers',
        'provider capability-based routing and automatic failover',
        'single and bulk payout support where a provider allows it',
        'webhook verification and idempotency',
        'refund and reconciliation',
        'manual NGN bank deposits with proof upload and admin approval',
    ],
    'provider_integrations' => ['dedicated PaymentGatewayManager with unlimited admin-addable NGN gateway providers'],
    'scheduled_tasks' => ['payment expiry/reconciliation maintenance'],
    'events' => [
        'payment.created',
        'payment.succeeded',
        'payment.failed',
        'payment.refunded',
        'payment.provider.failed',
        'payment.provider.health_changed',
    ],
];
