<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('education_academic_units',function(Blueprint $t){$t->id();$t->foreignId('institution_id')->constrained('education_institutions')->cascadeOnDelete();$t->foreignId('parent_unit_id')->nullable()->constrained('education_academic_units')->nullOnDelete();$t->string('unit_type',40)->index();$t->string('name');$t->string('short_name')->nullable();$t->string('code')->nullable();$t->string('slug')->index();$t->text('description')->nullable();$t->unsignedInteger('display_order')->default(0);$t->boolean('active')->default(true)->index();$t->json('metadata')->nullable();$t->string('source_url')->nullable();$t->string('source_title')->nullable();$t->date('source_published_at')->nullable();$t->timestamp('verified_at')->nullable();$t->timestamps();$t->softDeletes();$t->unique(['institution_id','parent_unit_id','name']);});
  Schema::create('education_departments',function(Blueprint $t){$t->id();$t->foreignId('institution_id')->constrained('education_institutions')->cascadeOnDelete();$t->foreignId('academic_unit_id')->nullable()->constrained('education_academic_units')->nullOnDelete();$t->string('name');$t->string('short_name')->nullable();$t->string('code')->nullable();$t->string('slug')->index();$t->text('description')->nullable();$t->boolean('active')->default(true)->index();$t->json('metadata')->nullable();$t->string('source_url')->nullable();$t->string('source_title')->nullable();$t->date('source_published_at')->nullable();$t->timestamp('verified_at')->nullable();$t->timestamps();$t->softDeletes();$t->unique(['institution_id','academic_unit_id','name']);});
  Schema::create('education_programmes',function(Blueprint $t){$t->id();$t->foreignId('institution_id')->constrained('education_institutions')->cascadeOnDelete();$t->foreignId('academic_unit_id')->nullable()->constrained('education_academic_units')->nullOnDelete();$t->foreignId('department_id')->nullable()->constrained('education_departments')->nullOnDelete();$t->string('name');$t->string('official_title')->nullable();$t->string('short_name')->nullable();$t->string('code')->nullable();$t->string('slug')->index();$t->string('award_type',60)->nullable()->index();$t->string('qualification_level',60)->nullable();$t->unsignedSmallInteger('duration_value')->nullable();$t->string('duration_unit',20)->nullable();$t->string('study_mode',40)->nullable();$t->text('description')->nullable();$t->boolean('active')->default(true)->index();$t->json('metadata')->nullable();$t->string('source_url')->nullable();$t->string('source_title')->nullable();$t->date('source_published_at')->nullable();$t->timestamp('verified_at')->nullable();$t->timestamps();$t->softDeletes();$t->index(['institution_id','department_id']);});
  Schema::create('education_academic_sessions',function(Blueprint $t){$t->id();$t->string('name',30)->unique();$t->unsignedSmallInteger('start_year');$t->unsignedSmallInteger('end_year');$t->string('slug')->unique();$t->string('status',30)->default('active')->index();$t->boolean('is_current')->default(false)->index();$t->date('application_start_date')->nullable();$t->date('application_end_date')->nullable();$t->json('metadata')->nullable();$t->timestamps();});
  Schema::create('education_admission_routes',function(Blueprint $t){$t->id();$t->string('code',50)->unique();$t->string('name');$t->text('description')->nullable();$t->boolean('active')->default(true)->index();$t->timestamps();});
  Schema::create('education_programme_admissions',function(Blueprint $t){$t->id();$t->foreignId('programme_id')->constrained('education_programmes')->cascadeOnDelete();$t->foreignId('academic_session_id')->constrained('education_academic_sessions')->restrictOnDelete();$t->string('admission_status',30)->default('draft')->index();$t->boolean('utme_available')->default(false);$t->boolean('direct_entry_available')->default(false);$t->boolean('other_entry_available')->default(false);$t->boolean('first_choice_required')->nullable();$t->string('application_status',30)->default('open')->index();$t->text('general_notes')->nullable();$t->string('official_source_url')->nullable();$t->string('source_title')->nullable();$t->date('source_published_at')->nullable();$t->date('effective_from')->nullable();$t->date('effective_until')->nullable();$t->string('verification_status',30)->default('draft')->index();$t->timestamp('verified_at')->nullable();$t->timestamp('published_at')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->unique(['programme_id','academic_session_id']);});
  Schema::create('education_programme_admission_routes',function(Blueprint $t){$t->id();$t->foreignId('programme_admission_id')->constrained('education_programme_admissions')->cascadeOnDelete();$t->foreignId('admission_route_id')->constrained('education_admission_routes')->restrictOnDelete();$t->timestamps();$t->unique(['programme_admission_id','admission_route_id']);});
  Schema::create('education_admission_requirements',function(Blueprint $t){$t->id();$t->foreignId('programme_admission_id')->constrained('education_programme_admissions')->cascadeOnDelete();$t->foreignId('admission_route_id')->nullable()->constrained('education_admission_routes')->nullOnDelete();$t->string('candidate_type')->nullable()->index();$t->unsignedTinyInteger('minimum_age')->nullable();$t->unsignedTinyInteger('maximum_age')->nullable();$t->date('age_reference_date')->nullable();$t->unsignedSmallInteger('minimum_utme_score')->nullable();$t->unsignedTinyInteger('minimum_o_level_credit_count')->nullable();$t->unsignedTinyInteger('maximum_o_level_sittings')->nullable();$t->boolean('awaiting_result_allowed')->nullable();$t->boolean('post_utme_required')->nullable();$t->unsignedSmallInteger('post_utme_minimum_score')->nullable();$t->boolean('screening_required')->nullable();$t->unsignedBigInteger('screening_fee_minor')->nullable();$t->string('screening_currency',3)->nullable();$t->boolean('international_qualification_verification_required')->nullable();$t->text('notes')->nullable();$t->text('special_conditions')->nullable();$t->string('status',30)->default('draft')->index();$t->string('verification_status',30)->default('draft')->index();$t->string('source_url')->nullable();$t->string('source_title')->nullable();$t->date('source_published_at')->nullable();$t->date('effective_from')->nullable();$t->date('effective_until')->nullable();$t->timestamp('verified_at')->nullable();$t->timestamps();});
  Schema::create('education_admission_olevel_requirements',function(Blueprint $t){$t->id();$t->foreignId('admission_requirement_id')->constrained('education_admission_requirements')->cascadeOnDelete();$t->unsignedTinyInteger('minimum_credit_count');$t->unsignedTinyInteger('maximum_sittings')->nullable();$t->boolean('awaiting_result_allowed')->nullable();$t->boolean('required_english')->default(false);$t->boolean('required_mathematics')->nullable();$t->text('notes')->nullable();$t->timestamps();$t->unique('admission_requirement_id');});
  Schema::create('education_admission_olevel_subjects',function(Blueprint $t){$t->id();$t->foreignId('olevel_requirement_id')->constrained('education_admission_olevel_requirements')->cascadeOnDelete();$t->string('subject_name');$t->string('subject_code')->nullable();$t->string('requirement_type',20)->default('required');$t->string('minimum_grade',20)->nullable();$t->decimal('minimum_grade_numeric',5,2)->nullable();$t->string('group_key')->nullable();$t->string('alternative_group')->nullable();$t->boolean('compulsory')->default(false);$t->text('notes')->nullable();$t->unsignedSmallInteger('display_order')->default(0);$t->timestamps();$t->unique(['olevel_requirement_id','subject_name','group_key']);});
  Schema::create('education_admission_utme_combinations',function(Blueprint $t){$t->id();$t->foreignId('admission_requirement_id')->constrained('education_admission_requirements')->cascadeOnDelete();$t->string('name');$t->unsignedTinyInteger('minimum_subject_count')->nullable();$t->text('notes')->nullable();$t->boolean('active')->default(true)->index();$t->timestamps();});
  Schema::create('education_admission_utme_subjects',function(Blueprint $t){$t->id();$t->foreignId('combination_id')->constrained('education_admission_utme_combinations')->cascadeOnDelete();$t->string('subject_name');$t->string('subject_code')->nullable();$t->boolean('compulsory')->default(true);$t->unsignedTinyInteger('display_order')->default(0);$t->text('notes')->nullable();$t->timestamps();$t->unique(['combination_id','subject_name']);});
  Schema::create('education_admission_direct_entry_qualifications',function(Blueprint $t){$t->id();$t->foreignId('admission_requirement_id')->constrained('education_admission_requirements')->cascadeOnDelete();$t->string('qualification_type',80);$t->string('minimum_grade')->nullable();$t->decimal('minimum_points',7,2)->nullable();$t->boolean('relevant_field_required')->nullable();$t->text('required_subjects')->nullable();$t->text('awarding_institution_requirement')->nullable();$t->string('minimum_duration')->nullable();$t->text('notes')->nullable();$t->boolean('active')->default(true)->index();$t->timestamps();});
  Schema::create('education_admission_result_bodies',function(Blueprint $t){$t->id();$t->foreignId('admission_requirement_id')->constrained('education_admission_requirements')->cascadeOnDelete();$t->string('body_name');$t->string('body_code')->nullable();$t->string('result_type')->nullable();$t->boolean('accepted')->default(true);$t->text('notes')->nullable();$t->timestamps();$t->unique(['admission_requirement_id','body_name']);});
  Schema::create('education_admission_cutoffs',function(Blueprint $t){$t->id();$t->foreignId('programme_admission_id')->constrained('education_programme_admissions')->cascadeOnDelete();$t->string('cutoff_type',40)->index();$t->decimal('score',6,2);$t->decimal('score_scale',6,2)->nullable();$t->string('candidate_category')->nullable();$t->text('notes')->nullable();$t->string('source_url');$t->string('source_title');$t->date('source_published_at')->nullable();$t->timestamp('verified_at')->nullable();$t->timestamps();});
  Schema::create('education_admission_screening_rules',function(Blueprint $t){$t->id();$t->foreignId('programme_admission_id')->constrained('education_programme_admissions')->cascadeOnDelete();$t->boolean('required')->default(false);$t->string('screening_type',60);$t->decimal('minimum_score',7,2)->nullable();$t->boolean('registration_required')->default(true);$t->boolean('first_choice_required')->nullable();$t->boolean('result_upload_required')->nullable();$t->string('screening_url')->nullable();$t->date('start_date')->nullable();$t->date('end_date')->nullable();$t->unsignedBigInteger('fee_minor')->nullable();$t->string('currency',3)->nullable();$t->text('notes')->nullable();$t->string('source_url');$t->string('source_title');$t->date('source_published_at')->nullable();$t->timestamp('verified_at')->nullable();$t->timestamps();});
  Schema::create('education_admission_special_rules',function(Blueprint $t){$t->id();$t->foreignId('programme_admission_id')->constrained('education_programme_admissions')->cascadeOnDelete();$t->string('rule_type',50)->index();$t->string('title');$t->text('description');$t->string('candidate_category')->nullable();$t->unsignedSmallInteger('priority')->default(0);$t->string('source_url');$t->string('source_title');$t->date('source_published_at')->nullable();$t->timestamp('verified_at')->nullable();$t->timestamps();});
  Schema::create('education_admission_documents',function(Blueprint $t){$t->id();$t->foreignId('programme_admission_id')->constrained('education_programme_admissions')->cascadeOnDelete();$t->string('document_type',100);$t->boolean('required')->default(true);$t->text('notes')->nullable();$t->string('source_url')->nullable();$t->string('source_title')->nullable();$t->timestamps();});
  Schema::create('education_admission_sources',function(Blueprint $t){$t->id();$t->foreignId('programme_admission_id')->nullable()->constrained('education_programme_admissions')->cascadeOnDelete();$t->foreignId('admission_requirement_id')->nullable()->constrained('education_admission_requirements')->cascadeOnDelete();$t->string('source_type',60);$t->string('title');$t->string('url');$t->string('publisher')->nullable();$t->date('publication_date')->nullable();$t->timestamp('retrieved_at');$t->date('effective_from')->nullable();$t->date('effective_until')->nullable();$t->string('verification_status',30)->default('draft')->index();$t->text('notes')->nullable();$t->timestamps();$t->index(['programme_admission_id','admission_requirement_id']);});
 }
 public function down(): void {
  foreach(['education_admission_sources','education_admission_documents','education_admission_special_rules','education_admission_screening_rules','education_admission_cutoffs','education_admission_result_bodies','education_admission_direct_entry_qualifications','education_admission_utme_subjects','education_admission_utme_combinations','education_admission_olevel_subjects','education_admission_olevel_requirements','education_admission_requirements','education_programme_admission_routes','education_programme_admissions','education_admission_routes','education_academic_sessions','education_programmes','education_departments','education_academic_units'] as $t) Schema::dropIfExists($t);
 }
};