<?php

return [
    'identifier' => 'events.entertainment',
    'name' => 'Events & Entertainment',
    'version' => '1.0.0',
    'description' => 'Event discovery, ticketing, attendee management and organiser tools for concerts, festivals, conferences, comedy, culture, sports, food, classes, virtual events and other live experiences.',
    'compatibility' => '>=2.0.0',
    'dependencies' => [],
    'permissions' => [
        'events.view',
        'events.purchase',
        'events.organize',
        'events.manage',
        'events.verify',
        'events.publish',
        'events.tickets.manage',
        'events.orders.view',
        'events.checkin.manage',
        'events.settings.manage',
    ],
    'role_permissions' => [
        'ADMIN' => [
            'events.view','events.purchase','events.organize','events.manage','events.verify',
            'events.publish','events.tickets.manage','events.orders.view','events.checkin.manage',
            'events.settings.manage',
        ],
        'STAFF' => [
            'events.view','events.purchase','events.organize','events.manage','events.verify',
            'events.publish','events.tickets.manage','events.orders.view','events.checkin.manage',
        ],
        'SUPPORT' => ['events.view','events.orders.view'],
        'USER' => ['events.view','events.purchase','events.organize','events.orders.view'],
    ],
    'navigation' => [[
        'id' => 'events',
        'label' => 'Events & Entertainment',
        'url' => '/events',
        'icon' => 'calendar-days',
        'permission' => 'events.view',
        'section' => 'services',
        'order' => 96,
    ]],
    'admin_navigation' => [[
        'id' => 'admin-events',
        'label' => 'Events & Entertainment',
        'url' => '/admin/events',
        'icon' => 'calendar-days',
        'permission' => 'events.view',
        'section' => 'addons',
        'order' => 96,
    ]],
    'categories' => [
        ['id'=>'concerts-live-music','key'=>'concerts_live_music','label'=>'Concerts & Live Music'],
        ['id'=>'festivals','key'=>'festivals','label'=>'Festivals'],
        ['id'=>'comedy-nightlife','key'=>'comedy_nightlife','label'=>'Comedy & Nightlife'],
        ['id'=>'arts-culture','key'=>'arts_culture','label'=>'Arts & Culture'],
        ['id'=>'sports-wellness','key'=>'sports_wellness','label'=>'Sports & Wellness'],
        ['id'=>'food-drink','key'=>'food_drink','label'=>'Food & Drink'],
        ['id'=>'business-conferences','key'=>'business_conferences','label'=>'Business & Conferences'],
        ['id'=>'classes-workshops','key'=>'classes_workshops','label'=>'Classes & Workshops'],
        ['id'=>'community','key'=>'community','label'=>'Community'],
        ['id'=>'spirituality-religion','key'=>'spirituality_religion','label'=>'Spirituality & Religion'],
        ['id'=>'family-kids','key'=>'family_kids','label'=>'Family & Kids'],
        ['id'=>'cinema-screenings','key'=>'cinema_screenings','label'=>'Cinema & Screenings'],
        ['id'=>'virtual-events','key'=>'virtual_events','label'=>'Virtual Events'],
    ],
    'settings' => [
        ['key'=>'enabled','type'=>'boolean','default'=>true],
        ['key'=>'default_currency','type'=>'string','default'=>'NGN'],
        ['key'=>'require_transaction_pin','type'=>'boolean','default'=>true],
        ['key'=>'require_organizer_verification','type'=>'boolean','default'=>true],
        ['key'=>'require_event_approval','type'=>'boolean','default'=>true],
        ['key'=>'allow_free_events','type'=>'boolean','default'=>true],
        ['key'=>'allow_virtual_events','type'=>'boolean','default'=>true],
    ],
    'migrations' => [
        '2026_10_08_003000_create_events_core_schema.php',
    ],
    'web_route_files' => ['addons/events-entertainment/routes/web.php'],
    'api_route_files' => ['addons/events-entertainment/routes/api.php'],
    'routes' => ['/events'],
    'api_routes' => ['/api/v1/events'],
    'provider_integrations' => ['Core Payment/Provider services'],
    'provider_capabilities' => ['ticket_payment','ticket_delivery','ticket_status'],
    'scheduled_tasks' => ['Event ticket expiry reconciliation','Event payout reconciliation'],
    'events' => [
        'events.created','events.published','events.ticket.purchased',
        'events.ticket.checked_in','events.cancelled',
    ],
];
