<?php
namespace Semizzy\Addons\Loans\Services;
use App\Models\WalletAccount;
use App\Models\WalletMovement;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use RuntimeException;
use Semizzy\Addons\Loans\Models\Loan;
use Semizzy\Addons\Loans\Models\LoanProduct;
use Semizzy\Addons\Loans\Models\LoanRepayment;
class LoanService {
 public function apply(int $userId, array $data): Loan { $p=LoanProduct::where('key',$data['product_key'])->where('active',true)->firstOrFail(); $amount=(int)$data['amount_minor']; if($amount<(int)$p->minimum_amount_minor || ($p->maximum_amount_minor!==null && $amount>(int)$p->maximum_amount_minor)) throw new RuntimeException('Loan amount is outside product limits.'); $interest=(int)floor($amount*(float)$p->interest_rate/100); return Loan::create(['user_id'=>$userId,'loan_product_id'=>$p->id,'reference'=>'LOAN-'.strtoupper(Str::random(12)),'currency'=>$p->currency,'principal_minor'=>$amount,'interest_minor'=>$interest,'total_due_minor'=>$amount+$interest,'status'=>'pending']); }
 public function approve(Loan $loan): Loan { if($loan->status!=='pending') throw new RuntimeException('Only pending loans can be approved.'); $loan->status='approved';$loan->approved_at=now();$loan->due_at=now()->addDays($loan->product->tenure_days);$loan->saveOrFail();return $loan->fresh('product'); }
 public function reject(Loan $loan,string $reason): Loan { if(!in_array($loan->status,['pending','approved'],true)) throw new RuntimeException('Loan cannot be rejected in its current state.');$loan->status='rejected';$loan->rejection_reason=$reason;$loan->saveOrFail();return $loan; }
 public function disburse(Loan $loan): Loan { return DB::transaction(function()use($loan){$loan=Loan::whereKey($loan->id)->lockForUpdate()->with('product')->firstOrFail();if($loan->status!=='approved')throw new RuntimeException('Only approved loans can be disbursed.');$wallet=WalletAccount::where('user_id',$loan->user_id)->where('currency',$loan->currency)->where('status','active')->lockForUpdate()->firstOrFail();$before=(string)$wallet->available_minor;$after=(string)((int)$before+(int)$loan->principal_minor);$wallet->available_minor=$after;$wallet->saveOrFail();WalletMovement::create(['wallet_account_id'=>$wallet->id,'operation_key'=>'loan:disbursement:'.$loan->reference,'reference'=>'LOAN-DIS-'.strtoupper(Str::random(10)),'type'=>'loan_disbursement','amount_minor'=>(string)$loan->principal_minor,'currency'=>$wallet->currency,'available_before_minor'=>$before,'available_after_minor'=>$after,'held_before_minor'=>(string)$wallet->held_minor,'held_after_minor'=>(string)$wallet->held_minor,'metadata'=>['loan_reference'=>$loan->reference]]);$loan->status='disbursed';$loan->disbursed_at=now();$loan->saveOrFail();return $loan->fresh('product');}); }
 public function repay(Loan $loan,int $userId,int $amount,string $idempotency): LoanRepayment { return DB::transaction(function()use($loan,$userId,$amount,$idempotency){$loan=Loan::whereKey($loan->id)->where('user_id',$userId)->lockForUpdate()->firstOrFail();if(!in_array($loan->status,['disbursed','overdue'],true))throw new RuntimeException('Loan is not repayable.');$remaining=$loan->total_due_minor-$loan->repaid_minor;if($amount<1||$amount>$remaining)throw new RuntimeException('Repayment exceeds outstanding balance.');$op='loan:repayment:'.$loan->reference.':'.$idempotency;$existing=LoanRepayment::where('operation_key',$op)->first();if($existing)return $existing;$wallet=WalletAccount::where('user_id',$userId)->where('currency',$loan->currency)->where('status','active')->lockForUpdate()->firstOrFail();$before=(int)$wallet->available_minor;if($before<$amount)throw new RuntimeException('Insufficient wallet balance.');$after=$before-$amount;$wallet->available_minor=(string)$after;$wallet->saveOrFail();WalletMovement::create(['wallet_account_id'=>$wallet->id,'operation_key'=>$op,'reference'=>'LOAN-REP-'.strtoupper(Str::random(10)),'type'=>'loan_repayment','amount_minor'=>(string)$amount,'currency'=>$wallet->currency,'available_before_minor'=>(string)$before,'available_after_minor'=>(string)$after,'held_before_minor'=>(string)$wallet->held_minor,'held_after_minor'=>(string)$wallet->held_minor,'metadata'=>['loan_reference'=>$loan->reference]]);$loan->repaid_minor += $amount;$loan->status=$loan->repaid_minor >= $loan->total_due_minor?'closed':($loan->status==='overdue'?'overdue':'disbursed');if($loan->status==='closed')$loan->closed_at=now();$loan->saveOrFail();return LoanRepayment::create(['loan_id'=>$loan->id,'user_id'=>$userId,'operation_key'=>$op,'reference'=>'LRP-'.strtoupper(Str::random(12)),'amount_minor'=>$amount,'currency'=>$loan->currency,'balance_after_minor'=>$loan->total_due_minor-$loan->repaid_minor]);}); }
 public function markOverdue(int $limit=100): int { $n=0;Loan::whereIn('status',['disbursed'])->whereNotNull('due_at')->where('due_at','<',now())->whereColumn('repaid_minor','<','total_due_minor')->limit($limit)->get()->each(function(Loan $l)use(&$n){$l->status='overdue';$l->save();$n++;});return $n; }
}