import React from 'react';
import { Head, router } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';

type Institution = { id:number; slug:string; name:string; institution_type:string; country_code:string; state:string|null; active:boolean; programmes_count:number; products_count:number };
type Product = { id:number; key:string; name:string; service_type:string; currency:string; price_minor:number; active:boolean; institution?:{id:number;name:string}|null; provider?:{id:number;display_name:string}|null; transactions_count:number };
type Provider = { id:number; identifier:string; display_name:string };
type Transaction = { id:number; reference:string; status:string; amount_minor:number; currency:string; user?:{name:string}|null; product?:{name:string}|null; created_at:string };
export default function AdminSchoolAdmissionIndex({ institutions, products, providers, transactions }: { institutions:Institution[]; products:Product[]; providers:Provider[]; transactions:{data:Transaction[]}; programmes:unknown[]; serviceTypes:string[]; institutionTypes:string[] }) {
 const [institution,setInstitution] = React.useState({slug:'',name:'',institution_type:'university',country_code:'NG',state:'',official_website:'',admissions_url:'',active:true});
 const [product,setProduct] = React.useState({key:'',institution_id:'',programme_id:'',service_type:'application_form',name:'',description:'',currency:'NGN',price_minor:'',provider_id:'',provider_product_code:'',active:true,display_order:'100'});
 const field = (value:string,onChange:(v:string)=>void,placeholder:string,type='text') => <input className="w-full rounded-lg border px-3 py-2 text-sm" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} type={type}/>;
 const submitInstitution = (e:React.FormEvent) => {e.preventDefault();router.post('/admin/school-admission/institutions',institution);};
 const submitProduct = (e:React.FormEvent) => {e.preventDefault();router.post('/admin/school-admission/products',{...product,institution_id:product.institution_id||null,programme_id:product.programme_id||null,provider_id:product.provider_id||null,price_minor:Number(product.price_minor),display_order:Number(product.display_order)});};
 return <AppLayout><Head title="Admin · School Admission"/><div className="mx-auto max-w-7xl space-y-8 p-4 md:p-8">
  <header><p className="text-sm font-medium text-blue-600">Addon management</p><h1 className="text-2xl font-bold">School Admission</h1><p className="mt-1 text-sm text-gray-500">Manage institutions, admission products, provider mappings and transaction visibility. No institution or provider is preloaded as live data.</p></header>
  <section className="grid gap-6 lg:grid-cols-2">
   <form onSubmit={submitInstitution} className="space-y-3 rounded-xl border p-5"><h2 className="font-semibold">Add institution</h2>{field(institution.name,v=>setInstitution(s=>({...s,name:v})),'Institution name')}{field(institution.slug,v=>setInstitution(s=>({...s,slug:v})),'url-slug') }
    <select className="w-full rounded-lg border px-3 py-2 text-sm" value={institution.institution_type} onChange={e=>setInstitution(s=>({...s,institution_type:e.target.value}))}>{['university','polytechnic','college_of_education','technical_college','other'].map(v=><option key={v}>{v}</option>)}</select>
    {field(institution.state,v=>setInstitution(s=>({...s,state:v})),'State (optional)')}{field(institution.official_website,v=>setInstitution(s=>({...s,official_website:v})),'Official website (optional)', 'url')}{field(institution.admissions_url,v=>setInstitution(s=>({...s,admissions_url:v})),'Admissions portal (optional)','url')}
    <button className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Save institution</button>
   </form>
   <form onSubmit={submitProduct} className="space-y-3 rounded-xl border p-5"><h2 className="font-semibold">Add admission product</h2>{field(product.name,v=>setProduct(s=>({...s,name:v})),'Product display name')}{field(product.key,v=>setProduct(s=>({...s,key:v})),'unique-product-key')}
    <select className="w-full rounded-lg border px-3 py-2 text-sm" value={product.institution_id} onChange={e=>setProduct(s=>({...s,institution_id:e.target.value}))}><option value="">No institution linked</option>{institutions.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select>
    <select className="w-full rounded-lg border px-3 py-2 text-sm" value={product.service_type} onChange={e=>setProduct(s=>({...s,service_type:e.target.value}))}>{['application_form','post_utme','screening','acceptance_fee','admission_status','other'].map(v=><option key={v}>{v}</option>)}</select>
    {field(product.description,v=>setProduct(s=>({...s,description:v})),'Description (optional)')}{field(product.price_minor,v=>setProduct(s=>({...s,price_minor:v})),'Price in minor units (kobo)','number')}
    <select className="w-full rounded-lg border px-3 py-2 text-sm" value={product.provider_id} onChange={e=>setProduct(s=>({...s,provider_id:e.target.value}))}><option value="">No provider mapped yet</option>{providers.map(p=><option key={p.id} value={p.id}>{p.display_name} ({p.identifier})</option>)}</select>
    <button className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Save product</button>
   </form>
  </section>
  <section className="space-y-3"><h2 className="text-lg font-semibold">Institutions ({institutions.length})</h2><div className="overflow-x-auto rounded-xl border"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50"><tr><th className="p-3">Institution</th><th className="p-3">Type</th><th className="p-3">Programmes</th><th className="p-3">Products</th><th className="p-3">Status</th></tr></thead><tbody>{institutions.map(i=><tr key={i.id} className="border-t"><td className="p-3 font-medium">{i.name}<div className="text-xs text-gray-500">{i.slug}</div></td><td className="p-3">{i.institution_type}</td><td className="p-3">{i.programmes_count}</td><td className="p-3">{i.products_count}</td><td className="p-3">{i.active?'Active':'Disabled'}</td></tr>)}</tbody></table></div></section>
  <section className="space-y-3"><h2 className="text-lg font-semibold">Admission products ({products.length})</h2><div className="overflow-x-auto rounded-xl border"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50"><tr><th className="p-3">Product</th><th className="p-3">Institution</th><th className="p-3">Type</th><th className="p-3">Price</th><th className="p-3">Provider</th><th className="p-3">Transactions</th><th className="p-3">Actions</th></tr></thead><tbody>{products.map(p=><tr key={p.id} className="border-t"><td className="p-3">{p.name}<div className="text-xs text-gray-500">{p.key}</div></td><td className="p-3">{p.institution?.name??'—'}</td><td className="p-3">{p.service_type}</td><td className="p-3">{new Intl.NumberFormat('en-NG',{style:'currency',currency:p.currency}).format(p.price_minor/100)}</td><td className="p-3">{p.provider?.display_name??'Not mapped'}</td><td className="p-3">{p.transactions_count}</td><td className="p-3"><button onClick={()=>router.post('/admin/school-admission/products/'+p.id+'/toggle')} className="rounded border px-3 py-1">{p.active?'Disable':'Enable'}</button></td></tr>)}</tbody></table></div></section>
  <section className="space-y-3"><h2 className="text-lg font-semibold">Recent transactions</h2><div className="overflow-x-auto rounded-xl border"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50"><tr><th className="p-3">Reference</th><th className="p-3">Customer</th><th className="p-3">Product</th><th className="p-3">Amount</th><th className="p-3">Status</th></tr></thead><tbody>{transactions.data.map(t=><tr key={t.id} className="border-t"><td className="p-3">{t.reference}</td><td className="p-3">{t.user?.name??'—'}</td><td className="p-3">{t.product?.name??'—'}</td><td className="p-3">{new Intl.NumberFormat('en-NG',{style:'currency',currency:t.currency}).format(t.amount_minor/100)}</td><td className="p-3">{t.status}</td></tr>)}</tbody></table></div></section>
 </div></AppLayout>;
}