<?php
namespace Semizzy\Addons\Investments\Services;
use App\Models\WalletAccount;
use App\Models\WalletMovement;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use RuntimeException;
use Semizzy\Addons\Investments\Models\InvestmentAccount;
use Semizzy\Addons\Investments\Models\InvestmentProduct;
use Semizzy\Addons\Investments\Models\InvestmentMovement;
class InvestmentService {
 private function add(string $a,string $b):string{return function_exists('bcadd')?bcadd($a,$b,0):(string)((int)$a+(int)$b);}
 private function sub(string $a,string $b):string{return function_exists('bcsub')?bcsub($a,$b,0):(string)((int)$a-(int)$b);}
 private function pct(string $a,float $rate):string{return (string)floor((float)$a*$rate/100);}
 public function create(int $userId,array $data):InvestmentAccount{$p=InvestmentProduct::where('key',$data['product_key'])->where('active',true)->firstOrFail();$amount=(string)$data['amount_minor'];if(!ctype_digit($amount)||bccomp($amount,(string)$p->minimum_amount_minor,0)<0||($p->maximum_amount_minor!==null&&bccomp($amount,(string)$p->maximum_amount_minor,0)>0))throw new RuntimeException('Investment amount is outside product limits.');return InvestmentAccount::create(['user_id'=>$userId,'investment_product_id'=>$p->id,'reference'=>'INV-'.strtoupper(Str::random(12)),'currency'=>$p->currency,'principal_minor'=>$amount,'status'=>'pending']);}
 public function fund(InvestmentAccount $account,int $userId,string $idempotency):InvestmentAccount{return DB::transaction(function()use($account,$userId,$idempotency){$a=InvestmentAccount::whereKey($account->id)->where('user_id',$userId)->lockForUpdate()->with('product')->firstOrFail();if($a->status!=='pending')throw new RuntimeException('Investment is not awaiting funding.');$op='investment:fund:'.$a->reference.':'.$idempotency;if(InvestmentMovement::where('operation_key',$op)->exists())return $a->fresh('product');$w=WalletAccount::where('user_id',$userId)->where('currency',$a->currency)->where('status','active')->lockForUpdate()->firstOrFail();$before=(string)$w->available_minor;if(function_exists('bccomp')?$this->cmp($before,(string)$a->principal_minor)<0:(int)$before<(int)$a->principal_minor)throw new RuntimeException('Insufficient wallet balance.');$after=$this->sub($before,(string)$a->principal_minor);$w->available_minor=$after;$w->saveOrFail();WalletMovement::create(['wallet_account_id'=>$w->id,'operation_key'=>$op,'reference'=>'INV-FUND-'.strtoupper(Str::random(10)),'type'=>'investment_funding','amount_minor'=>(string)$a->principal_minor,'currency'=>$w->currency,'available_before_minor'=>$before,'available_after_minor'=>$after,'held_before_minor'=>(string)$w->held_minor,'held_after_minor'=>(string)$w->held_minor,'metadata'=>['investment_reference'=>$a->reference]]);$a->status='active';$a->funded_at=now();$a->matures_at=now()->addDays($a->product->term_days);$a->saveOrFail();InvestmentMovement::create(['investment_account_id'=>$a->id,'user_id'=>$userId,'operation_key'=>$op,'reference'=>'IMV-FUND-'.strtoupper(Str::random(10)),'type'=>'funding','amount_minor'=>$a->principal_minor,'currency'=>$a->currency,'balance_after_minor'=>$a->principal_minor]);return $a->fresh('product');});}
 private function cmp(string $a,string $b):int{return function_exists('bccomp')?bccomp($a,$b,0):((int)$a<=>((int)$b);}
 public function processMaturity(int $limit=100):int{$n=0;InvestmentAccount::where('status','active')->whereNotNull('matures_at')->where('matures_at','<=',now())->limit($limit)->get()->each(function($a)use(&$n){DB::transaction(function()use($a){$x=InvestmentAccount::whereKey($a->id)->lockForUpdate()->with('product')->first();if(!$x||$x->status!=='active')return;$profit=(int)$this->pct((string)$x->principal_minor,(float)$x->product->profit_rate);$x->profit_minor=$profit;$x->status='matured';$x->saveOrFail();InvestmentMovement::create(['investment_account_id'=>$x->id,'user_id'=>$x->user_id,'operation_key'=>'investment:profit:'.$x->reference,'reference'=>'IMV-PROFIT-'.strtoupper(Str::random(10)),'type'=>'profit','amount_minor'=>$profit,'currency'=>$x->currency,'balance_after_minor'=>$this->add((string)$x->principal_minor,(string)$profit)]);});$n++;});return $n;}
 public function redeem(InvestmentAccount $account,int $userId,string $idempotency):InvestmentAccount{return DB::transaction(function()use($account,$userId,$idempotency){$a=InvestmentAccount::whereKey($account->id)->where('user_id',$userId)->lockForUpdate()->with('product')->firstOrFail();if(!in_array($a->status,['active','matured'],true))throw new RuntimeException('Investment cannot be redeemed.');if($a->status==='active'&&!$a->product->allow_early_redemption)throw new RuntimeException('Investment is locked until maturity.');$op='investment:redeem:'.$a->reference.':'.$idempotency;if(InvestmentMovement::where('operation_key',$op)->exists())return $a->fresh('product');$gross=$this->add((string)$a->principal_minor,(string)$a->profit_minor);$penalty=($a->status==='active')?(int)$this->pct($gross,(float)$a->product->early_redemption_penalty):0;$net=$this->sub($gross,(string)$penalty);$w=WalletAccount::where('user_id',$userId)->where('currency',$a->currency)->where('status','active')->lockForUpdate()->firstOrFail();$before=(string)$w->available_minor;$after=$this->add($before,$net);$w->available_minor=$after;$w->saveOrFail();WalletMovement::create(['wallet_account_id'=>$w->id,'operation_key'=>$op,'reference'=>'INV-RED-'.strtoupper(Str::random(10)),'type'=>'investment_redemption','amount_minor'=>$net,'currency'=>$w->currency,'available_before_minor'=>$before,'available_after_minor'=>$after,'held_before_minor'=>(string)$w->held_minor,'held_after_minor'=>(string)$w->held_minor,'metadata'=>['investment_reference'=>$a->reference,'gross_amount_minor'=>$gross,'penalty_minor'=>$penalty]]);$a->redeemed_minor=$net;$a->status='redeemed';$a->redeemed_at=now();$a->saveOrFail();InvestmentMovement::create(['investment_account_id'=>$a->id,'user_id'=>$userId,'operation_key'=>$op.':ledger','reference'=>'IMV-RED-'.strtoupper(Str::random(10)),'type'=>'redemption','amount_minor'=>$net,'currency'=>$a->currency,'balance_after_minor'=>0]);return $a->fresh('product');});}
}