import React from 'react';import axios from 'axios';
export default function BusinessAdmin(){
 const [partners,setPartners]=React.useState<any[]>([]),[settlements,setSettlements]=React.useState<any[]>([]),[loading,setLoading]=React.useState(true);
 const load=()=>{setLoading(true);return Promise.all([axios.get('/admin/business/partners'),axios.get('/admin/business/settlements?status=pending')]).then(([p,s])=>{setPartners(p.data.partners?.data||[]);setSettlements(s.data.settlements?.data||[])}).finally(()=>setLoading(false))};
 React.useEffect(()=>{load()},[]);
 const action=async(fn:()=>Promise<any>)=>{try{await fn();await load()}catch(e:any){alert(e?.response?.data?.message||'Action failed.')}};
 const approve=(id:number,approved:boolean)=>action(()=>axios.post('/admin/business/partners/'+id+'/approve',{approved}));
 const save=(p:any)=>{const parent=prompt('Parent partner ID (blank = none)',p.parent_partner_id??'');const rate=prompt('Commission rate in basis points (0-10000)',String(p.commission_rate_bps??0));const daily=prompt('Daily limit in minor units (blank = unlimited)',p.daily_limit_minor??'');const monthly=prompt('Monthly limit in minor units (blank = unlimited)',p.monthly_limit_minor??'');return action(()=>axios.patch('/admin/business/partners/'+p.id,{parent_partner_id:parent===''?null:Number(parent),commission_rate_bps:Number(rate),daily_limit_minor:daily===''?null:Number(daily),monthly_limit_minor:monthly===''?null:Number(monthly)}))};
 const status=(id:number,s:string)=>action(()=>axios.patch('/admin/business/partners/'+id,{status:s}));
 const settle=(id:number)=>action(()=>axios.post('/admin/business/settlements/'+id+'/settle'));
 return <div className="p-6 space-y-6"><div><h1 className="text-2xl font-bold">Business, Agent, Merchant & Reseller</h1><p className="text-sm opacity-70">Production controls for hierarchy, pricing, limits, approvals and commissions.</p></div>
 <div className="rounded-xl border p-4"><h2 className="font-semibold mb-3">Partner management</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">User</th><th className="p-3">Type</th><th className="p-3">Business</th><th className="p-3">Status</th><th className="p-3">Commission</th><th className="p-3">Limits</th><th className="p-3">Controls</th></tr></thead><tbody>{partners.map(p=><tr key={p.id} className="border-b"><td className="p-3">{p.user?.name||p.user_id}</td><td className="p-3 capitalize">{p.type}</td><td className="p-3">{p.business?.business_name||'—'}</td><td className="p-3 capitalize">{p.status}</td><td className="p-3">{((p.commission_rate_bps||0)/100).toFixed(2)}%</td><td className="p-3">{p.daily_limit_minor??'∞'} / {p.monthly_limit_minor??'∞'}</td><td className="p-3 flex flex-wrap gap-2">{p.status==='pending'&&<><button className="rounded border px-3 py-1" onClick={()=>approve(p.id,true)}>Approve</button><button className="rounded border px-3 py-1" onClick={()=>approve(p.id,false)}>Reject</button></>}{p.status==='active'&&<button className="rounded border px-3 py-1" onClick={()=>status(p.id,'suspended')}>Suspend</button>}{p.status==='suspended'&&<button className="rounded border px-3 py-1" onClick={()=>status(p.id,'active')}>Activate</button>}<button className="rounded border px-3 py-1" onClick={()=>save(p)}>Hierarchy / Limits</button></td></tr>)}</tbody></table></div></div>
 <div className="rounded-xl border p-4"><h2 className="font-semibold mb-3">Pending commission settlements</h2>{settlements.length===0?<p className="opacity-70">No pending settlements.</p>:<div className="space-y-2">{settlements.map(s=><div key={s.id} className="flex flex-wrap items-center justify-between gap-3 border rounded-lg p-3"><div><b>#{s.id}</b> · {s.beneficiary_partner?.user?.name||s.beneficiary_partner_id}<div className="text-xs opacity-70">{s.service_key} · {s.amount_minor} {s.currency} · depth {s.depth}</div></div><button className="rounded border px-3 py-1" onClick={()=>settle(s.id)}>Settle</button></div>)}</div>}</div>
 {loading&&<p className="opacity-70">Loading…</p>}</div>;
}