import {Head} from '@inertiajs/react';import{useState}from'react';
type Product={id:number;name:string;category:string;description?:string;currency:string;premium_minor:number;coverage?:{amount_minor?:number};provider?:{name:string}};
export default function Insurance({products,policies,claims=[]}:{products:Product[];policies:any[];claims?:any[]}){const[busy,setBusy]=useState<number|null>(null),[message,setMessage]=useState('');
const csrf=()=>document.querySelector('meta[name="csrf-token"]')?.getAttribute('content')||'';
const call=async(url:string,body?:any)=>{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrf(),Accept:'application/json'},body:body?JSON.stringify(body):undefined});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||'Request failed.');return j};
const buy=async(p:Product)=>{setBusy(p.id);setMessage('');try{await call('/insurance/purchase',{product_id:p.id,holder:{},idempotency_key:crypto.randomUUID()});setMessage('Purchase submitted successfully.');location.reload()}catch(e:any){setMessage(e.message)}finally{setBusy(null)}};
const action=async(fn:()=>Promise<any>,ok:string)=>{try{await fn();setMessage(ok);location.reload()}catch(e:any){setMessage(e.message)}};
return <><Head title="Insurance & Protection"/><main className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-6xl"><h1 className="text-3xl font-extrabold">Insurance & Protection</h1><p className="mt-1 text-slate-500">Provider-backed protection products and policy management.</p>{message&&<div className="mt-4 rounded-xl border bg-white p-4">{message}</div>}
<section className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{products.map(p=><article key={p.id} className="rounded-2xl border bg-white p-5 shadow-sm"><span className="text-xs font-bold uppercase text-indigo-600">{p.category}</span><h2 className="mt-2 text-xl font-extrabold">{p.name}</h2><p className="mt-2 text-sm text-slate-500">{p.description||'Provider-backed insurance protection.'}</p><p className="mt-4 text-2xl font-black">{p.currency} {(p.premium_minor/100).toLocaleString()}</p>{p.coverage?.amount_minor&&<p className="text-sm">Coverage up to {p.currency} {(p.coverage.amount_minor/100).toLocaleString()}</p>}<p className="mt-2 text-xs text-slate-400">Provider: {p.provider?.name||'Configured provider'}</p><button disabled={busy!==null} onClick={()=>buy(p)} className="mt-5 w-full rounded-xl bg-indigo-600 px-4 py-3 font-bold text-white disabled:opacity-50">{busy===p.id?'Processing…':'Buy Protection'}</button></article>)}</section>
<section className="mt-10"><h2 className="text-xl font-extrabold">My Policies</h2><div className="mt-3 space-y-3">{policies.map((p:any)=><div key={p.id} className="rounded-xl border bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><span><b>{p.product?.name||'Policy'}</b><br/><small>{p.reference}</small></span><span className="font-bold">{p.status}</span></div><div className="mt-3 flex flex-wrap gap-2">{['provider_pending','pending'].includes(p.status)&&<button onClick={()=>action(()=>call('/insurance/policies/'+p.id+'/requery'),'Policy requeried.')} className="rounded-lg border px-3 py-2 text-xs font-bold">Requery</button>}{['active','issued'].includes(p.status)&&<><button onClick={()=>action(()=>call('/insurance/policies/'+p.id+'/renew',{idempotency_key:crypto.randomUUID()}),'Renewal submitted.')} className="rounded-lg border px-3 py-2 text-xs font-bold">Renew</button><button onClick={()=>{const reason=window.prompt('Reason for cancellation?');if(reason)action(()=>call('/insurance/policies/'+p.id+'/cancel',{reason}),'Cancellation submitted.')}} className="rounded-lg border px-3 py-2 text-xs font-bold">Cancel</button><button onClick={()=>{const description=window.prompt('Describe the claim');if(description)action(()=>call('/insurance/policies/'+p.id+'/claims',{description,idempotency_key:crypto.randomUUID()}),'Claim submitted.')}} className="rounded-lg border px-3 py-2 text-xs font-bold">Make Claim</button></>}</div></div>)}{!policies.length&&<div className="rounded-xl border bg-white p-5 text-slate-500">No policies yet.</div>}</div></section>
<section className="mt-10"><h2 className="text-xl font-extrabold">My Claims</h2><div className="mt-3 space-y-3">{claims.map((x:any)=><div key={x.id} className="rounded-xl border bg-white p-4 flex flex-wrap items-center justify-between gap-3"><span><b>{x.reference}</b><br/><small>{x.policy?.reference||'Policy'}</small></span><span className="flex items-center gap-2 font-bold">{x.status}{!['approved','paid','rejected','cancelled'].includes(x.status)&&<button onClick={()=>action(()=>call('/insurance/claims/'+x.id+'/requery'),'Claim requeried.')} className="rounded-lg border px-3 py-2 text-xs">Requery</button>}</span></div>)}{!claims.length&&<div className="rounded-xl border bg-white p-5 text-slate-500">No claims yet.</div>}</div></section></div></main></>}