import { Head, router } from '@inertiajs/react';

type NotificationItem = {
  id: string;
  type: string;
  title: string;
  message: string;
  url: string | null;
  readAt: string | null;
  createdAt: string | null;
};

type Props = { notifications: NotificationItem[]; unreadCount: number };

export default function Notifications({ notifications, unreadCount }: Props) {
  const markAllRead = () => router.post('/notifications/read-all', {}, { preserveScroll: true });
  const markRead = (id: string) => router.post(`/notifications/${encodeURIComponent(id)}/read`, {}, { preserveScroll: true });

  return (
    <>
      <Head title="Notifications" />
      <main className="min-h-screen bg-slate-50 p-4 pb-24 md:p-8">
        <div className="mx-auto max-w-3xl">
          <header className="flex items-start justify-between gap-4">
            <div>
              <p className="text-sm font-semibold text-indigo-700">SEMIZZY ONE</p>
              <h1 className="mt-1 text-2xl font-extrabold text-slate-900">Notifications</h1>
              <p className="mt-1 text-sm text-slate-600">{unreadCount} unread notification{unreadCount === 1 ? '' : 's'}</p>
            </div>
            {unreadCount > 0 && <button onClick={markAllRead} className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm font-semibold">Mark all read</button>}
          </header>

          <section className="mt-6 space-y-3">
            {notifications.length === 0 ? (
              <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center">
                <h2 className="font-bold text-slate-800">You’re all caught up</h2>
                <p className="mt-2 text-sm text-slate-600">Important account and service updates will appear here when generated by the platform.</p>
              </div>
            ) : notifications.map(item => (
              <article key={item.id} className={`rounded-2xl border bg-white p-4 shadow-sm ${item.readAt ? 'border-slate-200' : 'border-indigo-200'}`}>
                <div className="flex items-start gap-3">
                  <span aria-hidden="true" className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${item.readAt ? 'bg-slate-300' : 'bg-indigo-600'}`} />
                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-start justify-between gap-2">
                      <h2 className="font-bold text-slate-900">{item.title}</h2>
                      {item.createdAt && <time className="text-xs text-slate-500" dateTime={item.createdAt}>{new Date(item.createdAt).toLocaleString()}</time>}
                    </div>
                    {item.message && <p className="mt-2 whitespace-pre-wrap break-words text-sm text-slate-600">{item.message}</p>}
                    <div className="mt-3 flex flex-wrap gap-3 text-sm font-semibold">
                      {item.url && <a href={item.url} className="text-indigo-700">Open details</a>}
                      {!item.readAt && <button onClick={() => markRead(item.id)} className="text-slate-700">Mark as read</button>}
                    </div>
                  </div>
                </div>
              </article>
            ))}
          </section>

          <nav className="fixed inset-x-0 bottom-0 border-t border-slate-200 bg-white/95 p-2 backdrop-blur md:static md:mt-8 md:border-0 md:bg-transparent">
            <div className="mx-auto flex max-w-3xl justify-around text-xs font-semibold text-slate-600 md:justify-start md:gap-5">
              <a href="/dashboard" className="p-2">Home</a><a href="/dashboard" className="p-2">Services</a><a href="/dashboard" className="p-2">Transactions</a><a href="/notifications" aria-current="page" className="p-2 text-indigo-700">Notifications</a><a href="/profile" className="p-2">Profile</a>
            </div>
          </nav>
        </div>
      </main>
    </>
  );
}
