import { Head, router, useForm } from '@inertiajs/react';

type Item={id:number;type:string;status:string;changes:Record<string,string>;reason:string;businessEntityType:string|null;businessRegisteredName:string|null;businessRegistrationNumber:string|null;businessTaxId:string|null;businessRegisteredAddress:string|null;businessState:string|null;businessCountry:string|null;documentCount:number;adminNote:string|null;reviewedAt:string|null;createdAt:string|null};
export default function ProfileChangeRequests({requests,latestPending,canRequestBusiness}:{requests:Item[];latestPending:Item|null;canRequestBusiness:boolean}){
 const form=useForm<any>({request_type:'personal',reason:'',name:'',email:'',phone:'',date_of_birth:'',gender:'',address:'',city:'',state:'',country:'Nigeria',postal_code:'',occupation:'',business_entity_type:'business_name',business_registered_name:'',business_registration_number:'',business_tax_id:'',business_registered_address:'',business_state:'',business_country:'Nigeria',business_documents:[],transaction_pin:''});
 const submit=(e:React.FormEvent)=>{e.preventDefault();form.post('/profile/change-requests',{forceFormData:true,preserveScroll:true,onSuccess:()=>form.reset('reason','name','email','phone','date_of_birth','gender','address','city','state','country','postal_code','occupation','business_registered_name','business_registration_number','business_tax_id','business_registered_address','business_state','business_documents','transaction_pin')});};
 return <main className="min-h-screen bg-slate-50 p-4 pb-24 md:p-8"><Head title="Profile change requests"/><div className="mx-auto max-w-4xl"><section className="rounded-3xl bg-slate-900 p-6 text-white"><p className="text-xs font-bold uppercase tracking-widest text-slate-300">SEMIZZY ONE</p><h1 className="mt-2 text-2xl font-black">Profile change requests</h1><p className="mt-2 text-sm text-slate-300">Sensitive identity and contact changes are reviewed by an administrator before they take effect.</p></section>
 {latestPending&&<div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900"><b>Pending request #{latestPending.id}</b> — wait for admin review before submitting another request.</div>}
 <form onSubmit={submit} className="mt-5 space-y-5 rounded-3xl border bg-white p-6 shadow-sm">
  <div className="flex flex-wrap gap-2">{['personal','business'].map(t=><button type="button" key={t} disabled={t==='business'&&!canRequestBusiness||!!latestPending} onClick={()=>form.setData('request_type',t)} className={form.data.request_type===t?'rounded-xl bg-indigo-600 px-4 py-2 text-sm font-black text-white':'rounded-xl border px-4 py-2 text-sm font-black'}>{t==='business'?'Business / Company name':'Personal details'}</button>)}</div>
  {form.data.request_type==='personal'?<div className="grid gap-4 md:grid-cols-2">
   {['name','email','phone','date_of_birth','gender','address','city','state','country','postal_code','occupation'].map((field)=><label key={field} className="text-sm font-semibold capitalize">{field.replaceAll('_',' ')}<input className="mt-1 w-full rounded-xl border p-3 font-normal" type={field==='email'?'email':field==='date_of_birth'?'date':'text'} value={form.data[field]} onChange={e=>form.setData(field,e.target.value)} placeholder={'New '+field.replaceAll('_',' ')}/></label>)}
  </div>:<div className="space-y-4">
   <div className="rounded-2xl border border-indigo-100 bg-indigo-50 p-4 text-sm text-indigo-900"><b>CAC evidence required.</b> For a Business Name, CAC's current process uses electronic Certificate of Registration and Certified Extract. For companies, CAC provides an electronic Certificate and Certified Extract; upload the documents you received from the CAC and make sure the registration number matches the document. citeturn0search0turn0search1</div>
   <div className="grid gap-4 md:grid-cols-2">
    <label className="text-sm font-semibold">Entity type<select className="mt-1 w-full rounded-xl border p-3 font-normal" value={form.data.business_entity_type} onChange={e=>form.setData('business_entity_type',e.target.value)}><option value="business_name">Registered Business Name</option><option value="private_company">Private Company (Ltd)</option><option value="public_company">Public Company (PLC)</option><option value="llp">Limited Liability Partnership (LLP)</option><option value="lp">Limited Partnership (LP)</option><option value="incorporated_trustees">Incorporated Trustees</option></select></label>
    <label className="text-sm font-semibold">Registered business/company name<input required className="mt-1 w-full rounded-xl border p-3 font-normal" value={form.data.business_registered_name} onChange={e=>form.setData('business_registered_name',e.target.value)}/></label>
    <label className="text-sm font-semibold">CAC registration / RC / BN number<input required className="mt-1 w-full rounded-xl border p-3 font-normal" value={form.data.business_registration_number} onChange={e=>form.setData('business_registration_number',e.target.value)}/></label>
    <label className="text-sm font-semibold">TIN (optional)<input className="mt-1 w-full rounded-xl border p-3 font-normal" value={form.data.business_tax_id} onChange={e=>form.setData('business_tax_id',e.target.value)}/></label>
    <label className="text-sm font-semibold md:col-span-2">Registered address<textarea className="mt-1 w-full rounded-xl border p-3 font-normal" value={form.data.business_registered_address} onChange={e=>form.setData('business_registered_address',e.target.value)}/></label>
    <label className="text-sm font-semibold">State<input className="mt-1 w-full rounded-xl border p-3 font-normal" value={form.data.business_state} onChange={e=>form.setData('business_state',e.target.value)}/></label>
    <label className="text-sm font-semibold">Country<input className="mt-1 w-full rounded-xl border p-3 font-normal" value={form.data.business_country} onChange={e=>form.setData('business_country',e.target.value)}/></label>
   </div>
   <label className="block text-sm font-semibold">CAC documents <span className="font-normal text-slate-500">(Certificate/Certified Extract and any supporting registration documents)</span><input required multiple type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" className="mt-1 w-full rounded-xl border p-3 font-normal" onChange={e=>form.setData('business_documents',Array.from(e.target.files??[]))}/></label>
  </div>}
  <label className="block text-sm font-semibold">Reason for change<textarea required minLength={5} maxLength={2000} className="mt-1 w-full rounded-xl border p-3 font-normal" value={form.data.reason} onChange={e=>form.setData('reason',e.target.value)} placeholder="Explain why this change is needed"/></label>
  <label className="block text-sm font-semibold">Transaction PIN<input required inputMode="numeric" pattern="\d{4}" maxLength={4} type="password" className="mt-1 w-full rounded-xl border p-3 font-normal" value={form.data.transaction_pin} onChange={e=>form.setData('transaction_pin',e.target.value.replace(/\D/g,'').slice(0,4))}/></label>
  <button disabled={form.processing||!!latestPending} className="w-full rounded-xl bg-slate-900 p-3.5 font-black text-white disabled:opacity-50">{form.processing?'Submitting…':'Submit request for admin review'}</button>
 </form>
 <section className="mt-5 space-y-3">{requests.map(item=><article key={item.id} className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between gap-3"><b>Request #{item.id}</b><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{item.status}</span></div><p className="mt-2 text-sm text-slate-600">{item.type==='business'?item.businessRegisteredName:Object.entries(item.changes).map(([k,v])=>k+': '+v).join(' · ')}</p>{item.reason&&<p className="mt-2 text-sm">Reason: {item.reason}</p>}{item.adminNote&&<p className="mt-2 rounded-xl bg-amber-50 p-3 text-sm">Admin: {item.adminNote}</p>}</article>)}</section>
 </div></main>;
}
