import {Head,router} from '@inertiajs/react';
import {FormEvent,useState} from 'react';
type Item={id:number;title:string;description?:string|null;institution?:string|null;faculty?:string|null;department?:string|null;course_code?:string|null;course_title?:string|null;education_level?:string|null;semester?:string|null;academic_session?:string|null;is_free:boolean;price_minor:number;currency:string;file_size:number;owned:boolean;has_preview:boolean};
type Props={title?:string;items:{data:Item[];links?:{url:string|null;label:string;active:boolean}[]};filters?:Record<string,string|null>;options?:Record<string,(string|number)[]>};
export default function SchoolPastQuestions({title='School Past Questions',items,filters={},options={}}:Props){
 const [q,setQ]=useState(filters.q||''); const [selected,setSelected]=useState<Record<string,string>>({institution:filters.institution||'',school_category:filters.school_category||'',department:filters.department||'',course_code:filters.course_code||'',education_level:filters.education_level||'',semester:filters.semester||'',academic_session:filters.academic_session||''});
 const search=(e:FormEvent)=>{e.preventDefault();router.get('/education/school-past-questions',{q,...selected},{preserveState:true,replace:true});};
 return <><Head title={title}/><main className="space-y-6 p-5 md:p-8"><header><p className="text-sm font-semibold uppercase tracking-wide opacity-60">Education library</p><h1 className="text-3xl font-bold">{title}</h1><p className="mt-2 max-w-2xl opacity-70">Find past papers by institution, course, level, semester and academic session.</p></header>
 <form onSubmit={search} className="space-y-3"><div className="flex max-w-2xl gap-2"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search school, course or paper…" className="min-w-0 flex-1 rounded-xl border bg-transparent p-3"/><button className="rounded-xl bg-black px-5 py-3 text-white">Search</button></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{([['school_category','School category'],['institution','Institution'],['department','Department'],['course_code','Course code'],['education_level','Level'],['semester','Semester'],['academic_session','Academic session']] as const).map(([key,label])=><select key={key} value={selected[key]||''} onChange={e=>setSelected({...selected,[key]:e.target.value})} className="rounded-xl border bg-transparent p-3"><option value="">All {label}s</option>{(options[key]||[]).map(value=><option key={String(value)} value={String(value)}>{value}</option>)}</select>)}</div></form>
 <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items?.data?.map(item=><article key={item.id} className="space-y-3 rounded-2xl border p-5"><div className="flex items-start justify-between gap-3"><h2 className="font-semibold">{item.title}</h2><span className="shrink-0 rounded-full border px-2 py-1 text-xs">{item.is_free?'Free':item.owned?'Owned':'Paid'}</span></div><p className="text-sm opacity-70">{[item.institution,item.department,item.course_code,item.course_title,item.education_level,item.semester,item.academic_session].filter(Boolean).join(' · ')}</p>{item.description&&<p className="text-sm">{item.description}</p>}<div className="flex items-center justify-between gap-3 border-t pt-3"><span className="text-sm font-medium">{item.is_free?'Free':item.currency+' '+(item.price_minor/100).toFixed(2)}</span>{item.owned?<a className="rounded-lg border px-3 py-2 text-sm" href={'/education/past-questions/'+item.id+'/download'}>Download</a>:<button onClick={()=>router.post('/education/past-questions/'+item.id+'/purchase')} className="rounded-lg bg-black px-3 py-2 text-sm text-white">Buy access</button>}{item.has_preview&&<a target="_blank" rel="noreferrer" className="rounded-lg border px-3 py-2 text-sm" href={'/education/past-questions/'+item.id+'/preview'}>Preview</a>}</div></article>)}</section>
 {!items?.data?.length&&<p className="rounded-xl border p-8 text-center opacity-70">No school past questions published yet. Please check back soon.</p>}
 <nav className="flex flex-wrap gap-2">{items?.links?.map((link,i)=><button key={i} disabled={!link.url} onClick={()=>link.url&&router.get(link.url,{}, {preserveState:true, preserveScroll:true})} className={'rounded-lg border px-3 py-2 text-sm '+(link.active?'bg-black text-white':'') } dangerouslySetInnerHTML={{__html:link.label}} />)}</nav>
 </main></>;
}
