<?php
return [
 'identifier'=>'ads.monetization',
 'name'=>'Ads & Monetization',
 'version'=>'1.0.0',
 'description'=>'Advertising campaigns, seller listing boosts, sponsored placements, budgets, moderation, and reporting.',
 'compatibility'=>'>=2.0.0',
 'dependencies'=>[],
 'permissions'=>['ads.view','ads.campaigns.manage','ads.placements.manage','ads.moderation.manage','ads.reports.view','ads.settings.manage','ads.promotions.create','ads.promotions.manage'],
 'role_permissions'=>[
  'ADMIN'=>['ads.view','ads.campaigns.manage','ads.placements.manage','ads.moderation.manage','ads.reports.view','ads.settings.manage','ads.promotions.create','ads.promotions.manage'],
  'STAFF'=>['ads.view','ads.campaigns.manage','ads.moderation.manage','ads.reports.view','ads.promotions.manage'],
  'SUPPORT'=>['ads.view','ads.reports.view'],
  'USER'=>['ads.promotions.create'],
 ],
 'navigation'=>[
  ['id'=>'ads-promotions','label'=>'Boost a listing','url'=>'/ads/promotions','icon'=>'megaphone','permission'=>'ads.promotions.create','section'=>'marketplace','order'=>80],
 ],
 'admin_navigation'=>[
  ['id'=>'admin-ads-monetization','label'=>'Ads & Monetization','url'=>'/admin/ads','icon'=>'megaphone','permission'=>'ads.view','section'=>'addons','order'=>170],
  ['id'=>'admin-ad-promotions','label'=>'Marketplace boosts','url'=>'/admin/ads/promotions','icon'=>'trending-up','permission'=>'ads.promotions.manage','section'=>'addons','order'=>171],
  ['id'=>'admin-ad-types','label'=>'Ad Types & Formats','url'=>'/admin/ads/types','icon'=>'layers','permission'=>'ads.settings.manage','section'=>'addons','order'=>172],
 ],
 'settings'=>[
  ['key'=>'enabled','type'=>'boolean','default'=>true],
  ['key'=>'default_currency','type'=>'string','default'=>'NGN'],
  ['key'=>'default_campaign_review_required','type'=>'boolean','default'=>true],
  ['key'=>'allow_cpc','type'=>'boolean','default'=>true],
  ['key'=>'allow_cpm','type'=>'boolean','default'=>true],
  ['key'=>'allow_sponsored_marketplace_listings','type'=>'boolean','default'=>false],
  ['key'=>'minimum_campaign_budget_minor','type'=>'integer','default'=>100000],
  ['key'=>'default_daily_budget_minor','type'=>'integer','default'=>0],
 ],
 'migrations'=>['2026_10_09_000500_create_ads_monetization.php','2026_10_09_000501_create_ad_promotions.php','2026_10_09_000502_create_ad_types.php'],
 'web_route_files'=>['addons/ads.monetization/routes/admin.php'],
 'api_route_files'=>[],
 'routes'=>['/admin/ads','/admin/ads/types','/admin/ads/promotions','/ads/promotions'],
 'api_routes'=>[],
 'provider_integrations'=>[],
 'provider_capabilities'=>[],
 'scheduled_tasks'=>[],
 'events'=>['ads.campaign.submitted','ads.campaign.approved','ads.campaign.paused','ads.impression.recorded','ads.click.recorded','ads.budget.exhausted','ads.promotion.submitted','ads.promotion.approved'],
];
