<?php
return [
 'identifier'=>'ads.monetization',
 'name'=>'Ads & Monetization',
 'version'=>'1.0.0',
 'description'=>'Centralized advertising campaigns, sponsored placements, budgets, moderation, impression and click reporting, and monetization controls for Core and compatible addons.',
 'compatibility'=>'>=2.0.0',
 'dependencies'=>[],
 'permissions'=>['ads.view','ads.campaigns.manage','ads.placements.manage','ads.moderation.manage','ads.reports.view','ads.settings.manage'],
 'role_permissions'=>[
  'ADMIN'=>['ads.view','ads.campaigns.manage','ads.placements.manage','ads.moderation.manage','ads.reports.view','ads.settings.manage'],
  'STAFF'=>['ads.view','ads.campaigns.manage','ads.moderation.manage','ads.reports.view'],
  'SUPPORT'=>['ads.view','ads.reports.view'],
  'USER'=>[],
 ],
 'navigation'=>[],
 'admin_navigation'=>[['id'=>'admin-ads-monetization','label'=>'Ads & Monetization','url'=>'/admin/ads','icon'=>'megaphone','permission'=>'ads.view','section'=>'addons','order'=>170]],
 'settings'=>[
  ['key'=>'enabled','type'=>'boolean','default'=>true],
  ['key'=>'default_currency','type'=>'string','default'=>'NGN'],
  ['key'=>'default_campaign_review_required','type'=>'boolean','default'=>true],
  ['key'=>'allow_cpc','type'=>'boolean','default'=>true],
  ['key'=>'allow_cpm','type'=>'boolean','default'=>true],
  ['key'=>'allow_sponsored_marketplace_listings','type'=>'boolean','default'=>false],
  ['key'=>'minimum_campaign_budget_minor','type'=>'integer','default'=>100000],
  ['key'=>'default_daily_budget_minor','type'=>'integer','default'=>0],
 ],
 'migrations'=>['2026_10_09_000500_create_ads_monetization.php'],
 'web_route_files'=>['addons/ads.monetization/routes/admin.php'],
 'api_route_files'=>[],
 'routes'=>['/admin/ads'],
 'api_routes'=>[],
 'provider_integrations'=>[],
 'provider_capabilities'=>[],
 'scheduled_tasks'=>[],
 'events'=>['ads.campaign.submitted','ads.campaign.approved','ads.campaign.paused','ads.impression.recorded','ads.click.recorded','ads.budget.exhausted'],
];
