<?php
namespace Semizzy\Addons\Education\Http\Controllers;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Inertia\Inertia;
use Semizzy\Addons\Education\Models\{EducationInstitution,EducationAcademicUnit,EducationDepartment,EducationProgramme,EducationAcademicSession,EducationProgrammeAdmission,EducationAdmissionRoute};
final class AdminSchoolAdmissionController extends Controller {
 public function index(){return Inertia::render('Admin/Education/SchoolAdmission',['institutions'=>EducationInstitution::orderBy('name')->get(['id','name','category','state','active']),'units'=>EducationAcademicUnit::with('institution')->orderBy('name')->get(),'departments'=>EducationDepartment::with(['institution','academicUnit'])->orderBy('name')->get(),'programmes'=>EducationProgramme::with(['institution','academicUnit','department'])->orderBy('name')->get(),'sessions'=>EducationAcademicSession::orderByDesc('start_year')->get(),'admissionRoutes'=>EducationAdmissionRoute::where('active',true)->get(),'admissions'=>EducationProgrammeAdmission::with(['programme','academicSession'])->latest()->paginate(25)]);}
 public function unit(Request $r){$d=$r->validate(['institution_id'=>'required|exists:education_institutions,id','parent_unit_id'=>'nullable|exists:education_academic_units,id','unit_type'=>'required|string|max:40','name'=>'required|string|max:190','short_name'=>'nullable|string|max:190','code'=>'nullable|string|max:80','source_url'=>'nullable|url']);$d['slug']=Str::slug($d['name']);return back()->with('success',EducationAcademicUnit::create($d)?'Academic unit created.':'Unable to create academic unit.');}
 public function department(Request $r){$d=$r->validate(['institution_id'=>'required|exists:education_institutions,id','academic_unit_id'=>'nullable|exists:education_academic_units,id','name'=>'required|string|max:190','short_name'=>'nullable|string|max:190','code'=>'nullable|string|max:80','source_url'=>'nullable|url']);$d['slug']=Str::slug($d['name']);return back()->with('success',EducationDepartment::create($d)?'Department created.':'Unable to create department.');}
 public function programme(Request $r){$d=$r->validate(['institution_id'=>'required|exists:education_institutions,id','academic_unit_id'=>'nullable|exists:education_academic_units,id','department_id'=>'nullable|exists:education_departments,id','name'=>'required|string|max:190','official_title'=>'nullable|string|max:190','award_type'=>'nullable|string|max:60','qualification_level'=>'nullable|string|max:60','duration_value'=>'nullable|integer|min:1|max:20','duration_unit'=>'nullable|string|max:20','study_mode'=>'nullable|string|max:40','source_url'=>'nullable|url']);$d['slug']=Str::slug($d['name']);return back()->with('success',EducationProgramme::create($d)?'Programme created.':'Unable to create programme.');}
 public function session(Request $r){$d=$r->validate(['name'=>'required|string|max:30','start_year'=>'required|integer|min:2000|max:2100','end_year'=>'required|integer|min:2000|max:2100']);$d['slug']=Str::slug($d['name']);$d['status']='active';return back()->with('success',EducationAcademicSession::create($d)?'Academic session created.':'Unable to create session.');}
 public function admission(Request $r){$d=$r->validate(['programme_id'=>'required|exists:education_programmes,id','academic_session_id'=>'required|exists:education_academic_sessions,id','utme_available'=>'boolean','direct_entry_available'=>'boolean','other_entry_available'=>'boolean','first_choice_required'=>'nullable|boolean','general_notes'=>'nullable|string','official_source_url'=>'required|url','source_title'=>'required|string|max:190']);$d['verification_status']='researched';$d['admission_status']='researched';return back()->with('success',EducationProgrammeAdmission::create($d)?'Programme admission record created for research/verification.':'Unable to create admission record.');}
 public function seedRoutes(){foreach([['code'=>'utme','name'=>'UTME'],['code'=>'direct_entry','name'=>'Direct Entry']] as $x) EducationAdmissionRoute::firstOrCreate(['code'=>$x['code']],$x);return back()->with('success','Admission routes synchronized.');}
}