<?php

return [
    'identifier' => 'banking.financial-integrations',
    'name' => 'Banking & Financial Integrations',
    'version' => '1.0.0',
    'compatibility' => '>=2.0.0',
    'dependencies' => [],
    'role_permissions' => [
        'ADMIN' => [
            'banking.view',
            'banking.manage',
            'banking.providers.manage',
            'banking.transfers.manage',
            'banking.accounts.manage',
            'banking.reconciliation.manage',
            'banking.settings.manage',
        ],
        'STAFF' => [
            'banking.view',
            'banking.transfers.manage',
            'banking.reconciliation.manage',
        ],
        'SUPPORT' => ['banking.view'],
        'USER' => [
            'banking.view',
            'banking.transfers.create',
            'banking.accounts.view',
        ],
    ],
    'permissions' => [
        'banking.view',
        'banking.transfers.create',
        'banking.transfers.manage',
        'banking.accounts.view',
        'banking.accounts.manage',
        'banking.providers.manage',
        'banking.reconciliation.manage',
        'banking.settings.manage',
    ],
    'navigation' => [
        [
            'id' => 'banking',
            'label' => 'Banking & Financial Integrations',
            'url' => '/admin/banking',
            'icon' => 'landmark',
            'permission' => 'banking.view',
            'section' => 'addons',
            'order' => 31,
        ],
    ],
    'settings' => [
        ['key' => 'default_currency', 'type' => 'string', 'default' => 'NGN'],
        ['key' => 'transfer_idempotency_required', 'type' => 'boolean', 'default' => true],
        ['key' => 'require_transaction_pin', 'type' => 'boolean', 'default' => true],
        ['key' => 'automatic_provider_failover', 'type' => 'boolean', 'default' => true],
        ['key' => 'automatic_reconciliation', 'type' => 'boolean', 'default' => true],
        ['key' => 'bank_account_name_enquiry', 'type' => 'boolean', 'default' => true],
    ],
    'migrations' => [],
    'web_route_files' => [],
    'api_route_files' => [],
    'routes' => ['/banking'],
    'api_routes' => ['/api/v1/banking'],
    'services' => [
        'bank account verification and name enquiry',
        'bank directory and account validation',
        'single and bulk bank transfers',
        'scheduled transfers and transfer status/requery',
        'virtual, dedicated and collection accounts',
        'automatic wallet funding and collections',
        'provider priority, failover and health checks',
        'reconciliation and settlement matching',
        'immutable financial ledger integration',
        'idempotency and duplicate-transfer protection',
    ],
    'provider_integrations' => ['Core ProviderManager'],
    'scheduled_tasks' => [
        'bank transfer status reconciliation',
        'provider health checks',
        'automatic settlement reconciliation',
    ],
    'events' => [
        'banking.transfer.created',
        'banking.transfer.processing',
        'banking.transfer.succeeded',
        'banking.transfer.failed',
        'banking.transfer.reversed',
        'banking.account.verified',
        'banking.reconciliation.completed',
    ],
];
