import React,{useEffect,useState} from 'react';
type Config={enabled:boolean;assistantName:string;welcomeMessage:string;privacyNotice:string;authenticated:boolean};
type Message={role:'user'|'assistant';content:string};
export default function AIChatbotWidget(){
 const [config,setConfig]=useState<Config|null>(null),[open,setOpen]=useState(false),[uuid,setUuid]=useState(''),[messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let alive=true;fetch('/ai-chatbot/config?path='+encodeURIComponent(window.location.pathname),{headers:{Accept:'application/json'},credentials:'same-origin'}).then(r=>r.ok?r.json():null).then(c=>{if(alive&&c?.enabled)setConfig(c)}).catch(()=>{});return()=>{alive=false}},[]);
 const csrf=()=>document.querySelector('meta[name="csrf-token"]')?.getAttribute('content')??'';
 const start=async()=>{if(uuid)return uuid;const r=await fetch('/ai-chatbot/conversations',{method:'POST',credentials:'same-origin',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf()},body:'{}'});if(!r.ok)throw new Error('Could not start a conversation. Refresh and try again.');const d=await r.json();setUuid(d.uuid);return d.uuid};
 const escalate=async()=>{if(!uuid)return;setBusy(true);setError('');try{const r=await fetch('/ai-chatbot/conversations/'+uuid+'/escalate',{method:'POST',credentials:'same-origin',headers:{Accept:'application/json','X-CSRF-TOKEN':csrf()}});const d=await r.json();if(!r.ok)throw new Error(d.message??'Could not create support ticket.');setMessages(m=>[...m,{role:'assistant',content:'Human support request created: '+d.ticketReference}]);}catch(err){setError(err instanceof Error?err.message:'Could not create support ticket.')}finally{setBusy(false)}};
 const send=async(e:React.FormEvent)=>{e.preventDefault();const text=input.trim();if(!text||busy)return;setBusy(true);setError('');setMessages(m=>[...m,{role:'user',content:text}]);setInput('');try{const id=await start();const r=await fetch('/ai-chatbot/conversations/'+id+'/messages',{method:'POST',credentials:'same-origin',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf()},body:JSON.stringify({message:text})});const d=await r.json();if(!r.ok)throw new Error(d.message??'Assistant unavailable. Try again.');setMessages(m=>[...m,{role:'assistant',content:d.reply}])}catch(err){setError(err instanceof Error?err.message:'Assistant unavailable.')}finally{setBusy(false)}};
 if(!config?.enabled)return null;
 return <div className="fixed bottom-20 right-4 z-[100] sm:bottom-6 sm:right-6"><button aria-label={open?'Close assistant':'Open assistant'} onClick={()=>setOpen(v=>!v)} className="flex h-14 w-14 items-center justify-center rounded-full bg-indigo-600 text-2xl text-white shadow-xl">{open?'×':'✦'}</button>{open&&<section aria-label="AI platform assistant" className="mb-3 flex h-[min(70vh,560px)] w-[min(92vw,380px)] flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl dark:border-slate-700 dark:bg-slate-900"><header className="bg-indigo-600 p-4 text-white"><div className="font-semibold">{config.assistantName}</div><div className="mt-1 text-xs opacity-90">{config.welcomeMessage}</div></header><div className="flex-1 space-y-3 overflow-y-auto p-3">{messages.length===0&&<div className="rounded-xl bg-slate-100 p-3 text-sm text-slate-700 dark:bg-slate-800 dark:text-slate-200">{config.privacyNotice}</div>}{messages.map((m,i)=><div key={i} className={'max-w-[90%] whitespace-pre-wrap rounded-xl p-3 text-sm '+(m.role==='user'?'ml-auto bg-indigo-600 text-white':'bg-slate-100 text-slate-800 dark:bg-slate-800 dark:text-slate-100')}>{m.content}</div>)}{busy&&<div className="text-sm text-slate-500">Thinking…</div>}{error&&<div role="alert" className="text-sm text-red-600">{error}</div>}</div><form onSubmit={send} className="flex gap-2 border-t p-3 dark:border-slate-700"><input aria-label="Message" maxLength={4000} value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask a question…" className="min-w-0 flex-1 rounded-lg border p-2 text-sm dark:bg-slate-800"/><button disabled={busy||!input.trim()} className="rounded-lg bg-indigo-600 px-3 text-sm font-semibold text-white disabled:opacity-50">Send</button></form>{config.authenticated&&uuid&&<div className="px-3 pb-2"><button onClick={escalate} disabled={busy} className="w-full rounded-lg border px-3 py-2 text-xs disabled:opacity-50">Contact human support</button></div>}<div className="px-3 pb-2 text-[10px] text-slate-500">Never share passwords, OTPs or transaction PINs.</div></section>}</div>;
}
