<?php

return [
    'identifier' => 'forex-digital-assets',
    'name' => 'Forex & Digital Assets',
    'version' => '1.0.0',
    'description' => 'Forex instrument discovery and digital-asset market infrastructure with verified provider provenance. Trading and exchange execution remain disabled until an approved provider is configured.',
    'compatibility' => '>=2.0.0',
    'dependencies' => [],
    'permissions' => [
        'forex.view',
        'forex.market.view',
        'forex.market.manage',
        'forex.providers.manage',
        'forex.orders.manage',
        'forex.settings.manage',
    ],
    'role_permissions' => [
        'ADMIN' => [
            'forex.view',
            'forex.market.view',
            'forex.market.manage',
            'forex.providers.manage',
            'forex.orders.manage',
            'forex.settings.manage',
        ],
        'STAFF' => ['forex.view', 'forex.market.view', 'forex.market.manage'],
        'SUPPORT' => ['forex.view', 'forex.market.view'],
        'USER' => ['forex.view', 'forex.market.view'],
    ],
    'navigation' => [
        [
            'id' => 'forex-digital-assets',
            'label' => 'Forex & Digital Assets',
            'url' => '/forex-digital-assets',
            'icon' => 'candlestick-chart',
            'permission' => 'forex.view',
            'section' => 'services',
            'order' => 65,
        ],
    ],
    'admin_navigation' => [
        [
            'id' => 'admin-forex-digital-assets',
            'label' => 'Forex & Digital Assets',
            'url' => '/admin/forex-digital-assets',
            'icon' => 'candlestick-chart',
            'permission' => 'forex.view',
            'section' => 'addons',
            'order' => 65,
        ],
    ],
    'settings' => [
        'enabled' => true,
        'default_fiat_currency' => 'NGN',
        'market_data_enabled' => false,
        'forex_enabled' => true,
        'digital_assets_enabled' => true,
        'trading_enabled' => false,
        'exchange_enabled' => false,
        'require_verified_provider' => true,
        'require_trade_kyc' => true,
        'require_transaction_pin' => true,
        'stale_quote_seconds' => 120,
        'allow_leverage' => false,
        'max_leverage' => 1,
    ],
    'migrations' => [
        '2026_10_08_005000_create_forex_digital_asset_market_schema.php',
    ],
    'web_route_files' => [
        'addons/forex-digital-assets/routes/web.php',
        'addons/forex-digital-assets/routes/admin.php',
    ],
    'api_route_files' => [
        'addons/forex-digital-assets/routes/api.php',
    ],
    'provider_integration' => [
        'type' => 'core',
        'manager' => 'App\\Services\\Providers\\ProviderManager',
        'capabilities' => ['market_data', 'quote', 'order_execution', 'portfolio_sync'],
    ],
    'scheduled_tasks' => [
        'market_quotes' => 'Refresh forex and digital-asset quotes only from enabled, verified market-data providers.',
        'reconciliation' => 'Reconcile provider orders/holdings through the database queue and cPanel cron when execution is enabled.',
    ],
    'events' => [
        'forex.quote.updated',
        'forex.order.created',
        'forex.order.executed',
        'digital_asset.quote.updated',
        'digital_asset.order.created',
        'digital_asset.order.executed',
    ],
    'regulatory_boundary' => [
        'no_guaranteed_returns',
        'no_fake_market_data',
        'no_fake_balances_or_transactions',
        'no_unverified_execution_provider',
        'no_leverage_by_default',
        'no_private_key_storage_by_default',
        'execution_disabled_until_verified_provider_and_required_controls_are_ready',
    ],
];
