<?php
namespace Semizzy\Addons\Savings\Http\Controllers;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Inertia\Inertia;
use Semizzy\Addons\Savings\Models\{SavingsAccount,SavingsPlan,SavingsMovement};
class SavingsController extends Controller {
 public function index(Request $r){return Inertia::render('Savings',['plans'=>SavingsPlan::where('active',true)->get(),'accounts'=>SavingsAccount::where('user_id',$r->user()->id)->with('plan')->latest()->get()]);}
 public function apiIndex(Request $r){return response()->json(['accounts'=>SavingsAccount::where('user_id',$r->user()->id)->with('plan')->latest()->get()]);}
 public function create(Request $r){$d=$r->validate(['plan_key'=>'required|string|max:100','name'=>'required|string|max:100','currency'=>'required|string|size:3','target_amount_minor'=>'nullable|integer|min:1']);$plan=SavingsPlan::where('key',$d['plan_key'])->where('active',true)->firstOrFail();$ref='SAV-'.strtoupper(bin2hex(random_bytes(6)));$a=SavingsAccount::create(['user_id'=>$r->user()->id,'savings_plan_id'=>$plan->id,'reference'=>$ref,'name'=>$d['name'],'currency'=>strtoupper($d['currency']),'target_amount_minor'=>$d['target_amount_minor']??null]);return response()->json(['account'=>$a],201);}
 public function contribute(Request $r,string $reference){$d=$r->validate(['amount_minor'=>'required|integer|min:1']);return DB::transaction(function()use($r,$reference,$d){$a=SavingsAccount::where('reference',$reference)->where('user_id',$r->user()->id)->lockForUpdate()->firstOrFail();abort_unless($a->status==='active',422,'Savings account is not active.');$key='savings:contribution:'.$reference.':'.($r->header('Idempotency-Key')?:bin2hex(random_bytes(8)));$m= SavingsMovement::where('operation_key',$key)->first();if($m)return response()->json(['account'=>$a->fresh(),'movement'=>$m]);$wallet=\App\Models\WalletAccount::where('user_id',$r->user()->id)->where('currency',$a->currency)->where('status','active')->lockForUpdate()->firstOrFail();abort_unless((int)$wallet->balance_minor >= (int)$d['amount_minor'],422,'Insufficient wallet balance.');$wallet->decrement('balance_minor',$d['amount_minor']);$a->balance_minor=(int)$a->balance_minor+(int)$d['amount_minor'];$a->last_contribution_at=now();$a->save();$m=SavingsMovement::create(['savings_account_id'=>$a->id,'user_id'=>$r->user()->id,'operation_key'=>$key,'type'=>'contribution','amount_minor'=>$d['amount_minor'],'currency'=>$a->currency,'balance_after_minor'=>$a->balance_minor,'reference'=>'SVM-'.strtoupper(bin2hex(random_bytes(6)))]);return response()->json(['account'=>$a->fresh(),'movement'=>$m]);});}
 public function withdraw(Request $r,string $reference){$d=$r->validate(['amount_minor'=>'required|integer|min:1']);return DB::transaction(function()use($r,$reference,$d){$a=SavingsAccount::where('reference',$reference)->where('user_id',$r->user()->id)->with('plan')->lockForUpdate()->firstOrFail();abort_unless($a->status==='active',422,'Savings account is not active.');abort_unless((int)$a->balance_minor >= (int)$d['amount_minor'],422,'Insufficient savings balance.');if($a->matures_at && now()->lt($a->matures_at) && !$a->plan->allow_early_withdrawal)abort(422,'Savings is locked until maturity.');$key='savings:withdrawal:'.$reference.':'.($r->header('Idempotency-Key')?:bin2hex(random_bytes(8)));if(SavingsMovement::where('operation_key',$key)->exists())return response()->json(['message'=>'Already processed.']);$wallet=\App\Models\WalletAccount::where('user_id',$r->user()->id)->where('currency',$a->currency)->where('status','active')->lockForUpdate()->firstOrFail();$a->balance_minor-=$d['amount_minor'];$a->save();$wallet->increment('balance_minor',$d['amount_minor']);$m=SavingsMovement::create(['savings_account_id'=>$a->id,'user_id'=>$r->user()->id,'operation_key'=>$key,'type'=>'withdrawal','amount_minor'=>$d['amount_minor'],'currency'=>$a->currency,'balance_after_minor'=>$a->balance_minor,'reference'=>'SVM-'.strtoupper(bin2hex(random_bytes(6)))]);return response()->json(['account'=>$a->fresh(),'movement'=>$m]);});}
}