<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
 if(!Schema::hasTable('vtu_transactions'))Schema::create('vtu_transactions',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->string('reference')->unique();$t->foreignId('user_id')->constrained()->restrictOnDelete();$t->foreignId('service_id')->constrained('services')->restrictOnDelete();$t->foreignId('service_product_id')->nullable()->constrained('service_products')->nullOnDelete();$t->foreignId('api_provider_id')->nullable()->constrained('api_providers')->nullOnDelete();$t->foreignId('financial_operation_id')->nullable()->unique()->constrained()->nullOnDelete();$t->string('idempotency_key')->unique();$t->string('status')->default('pending')->index();$t->decimal('amount_minor',20,0);$t->decimal('fee_minor',20,0)->default(0);$t->decimal('total_minor',20,0);$t->char('currency',3)->default('NGN');$t->string('customer_tier')->default('USER');$t->string('recipient')->nullable()->index();$t->json('request_payload')->nullable();$t->json('response_payload')->nullable();$t->string('provider_reference')->nullable()->index();$t->string('provider_status')->nullable();$t->string('failure_code')->nullable();$t->text('failure_message')->nullable();$t->timestamp('processed_at')->nullable();$t->timestamp('completed_at')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->index(['user_id','created_at']);$t->index(['service_id','status']);});
 if(!Schema::hasTable('vtu_transaction_attempts'))Schema::create('vtu_transaction_attempts',function(Blueprint $t){$t->id();$t->foreignId('vtu_transaction_id')->constrained()->cascadeOnDelete();$t->foreignId('api_provider_id')->nullable()->constrained('api_providers')->nullOnDelete();$t->unsignedInteger('attempt_number');$t->string('operation');$t->string('status');$t->string('provider_reference')->nullable()->index();$t->json('request_payload')->nullable();$t->json('response_payload')->nullable();$t->string('error_code')->nullable();$t->text('error_message')->nullable();$t->timestamp('started_at')->nullable();$t->timestamp('finished_at')->nullable();$t->timestamps();$t->unique(['vtu_transaction_id','attempt_number'],'vtu_attempt_number_unique');});
 if(!Schema::hasTable('vtu_bulk_operations'))Schema::create('vtu_bulk_operations',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->string('reference')->unique();$t->foreignId('user_id')->constrained()->restrictOnDelete();$t->foreignId('service_id')->nullable()->constrained('services')->nullOnDelete();$t->string('status')->default('pending')->index();$t->unsignedInteger('total_items')->default(0);$t->unsignedInteger('processed_items')->default(0);$t->unsignedInteger('successful_items')->default(0);$t->unsignedInteger('failed_items')->default(0);$t->json('metadata')->nullable();$t->timestamps();});
 if(!Schema::hasTable('vtu_bulk_operation_items'))Schema::create('vtu_bulk_operation_items',function(Blueprint $t){$t->id();$t->foreignId('bulk_operation_id')->constrained('vtu_bulk_operations')->cascadeOnDelete();$t->unsignedInteger('sequence');$t->string('idempotency_key')->unique();$t->foreignId('vtu_transaction_id')->nullable()->constrained('vtu_transactions')->nullOnDelete();$t->string('recipient')->nullable();$t->foreignId('product_id')->nullable()->constrained('service_products')->nullOnDelete();$t->decimal('amount_minor',20,0)->nullable();$t->string('status')->default('pending')->index();$t->text('error_message')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->unique(['bulk_operation_id','sequence']);});
 if(!Schema::hasTable('vtu_service_configurations'))Schema::create('vtu_service_configurations',function(Blueprint $t){$t->id();$t->foreignId('service_id')->constrained('services')->cascadeOnDelete();$t->string('key');$t->json('value')->nullable();$t->boolean('is_secret')->default(false);$t->boolean('enabled')->default(true);$t->timestamps();$t->unique(['service_id','key']);});
}
public function down():void{Schema::dropIfExists('vtu_service_configurations');Schema::dropIfExists('vtu_bulk_operation_items');Schema::dropIfExists('vtu_bulk_operations');Schema::dropIfExists('vtu_transaction_attempts');Schema::dropIfExists('vtu_transactions');}};
