<?php
namespace Semizzy\Addons\BulkSms\Services;
use App\Models\WalletAccount; use App\Models\WalletMovement; use App\Services\Providers\ProviderManager; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str; use RuntimeException;
use Semizzy\Addons\BulkSms\Models\BulkSmsCampaign; use Semizzy\Addons\BulkSms\Models\BulkSmsMessage; use Semizzy\Addons\BulkSms\Models\BulkSmsProduct;
class BulkSmsService {
 public function __construct(private ProviderManager $providers){}
 private function cmp(string $a,string $b):int{return function_exists('bccomp')?bccomp($a,$b,0):((int)$a<=>$b);}
 private function mul(string $a,int $b):string{return function_exists('bcmul')?bcmul($a,(string)$b,0):(string)((int)$a*$b);}
 private function sub(string $a,string $b):string{return function_exists('bcsub')?bcsub($a,$b,0):(string)((int)$a-(int)$b);}
 private function debit(WalletAccount $w,string $amount,string $op,array $meta):void{$before=(string)$w->available_minor;if($this->cmp($before,$amount)<0)throw new RuntimeException('Insufficient wallet balance.');$after=$this->sub($before,$amount);$w->available_minor=$after;$w->saveOrFail();WalletMovement::create(['wallet_account_id'=>$w->id,'operation_key'=>$op,'reference'=>'SMS-WAL-'.strtoupper(Str::random(10)),'type'=>'bulk_sms','amount_minor'=>$amount,'currency'=>$w->currency,'available_before_minor'=>$before,'available_after_minor'=>$after,'held_before_minor'=>(string)$w->held_minor,'held_after_minor'=>(string)$w->held_minor,'metadata'=>$meta]);}
 public function createCampaign(int $uid,array $data,array $phones):BulkSmsCampaign{return DB::transaction(function()use($uid,$data,$phones){$existing=BulkSmsCampaign::where('user_id',$uid)->where('idempotency_key',$data['idempotency_key'])->first();if($existing)return $existing;$p=BulkSmsProduct::where('key',$data['product_key'])->where('active',true)->lockForUpdate()->firstOrFail();$phones=array_values(array_unique(array_filter(array_map('trim',$phones))));$limit=(int)$p->max_recipients;if(count($phones)<1||count($phones)>$limit)throw new RuntimeException('Invalid recipient count.');$amount=$this->mul((string)$p->price_per_sms_minor,count($phones));$w=WalletAccount::where('user_id',$uid)->where('currency',$p->currency)->where('status','active')->lockForUpdate()->firstOrFail();$op='bulk-sms:create:'.$data['idempotency_key'];$this->debit($w,$amount,$op,['product'=>$p->key,'recipients'=>count($phones)]);$c=BulkSmsCampaign::create(['user_id'=>$uid,'product_id'=>$p->id,'reference'=>'SMS-'.strtoupper(Str::random(12)),'sender'=>$data['sender'],'message'=>$data['message'],'status'=>'queued','recipient_count'=>count($phones),'amount_minor'=>$amount,'currency'=>$p->currency,'scheduled_at'=>$data['scheduled_at']??null,'idempotency_key'=>$data['idempotency_key']]);foreach($phones as $phone){BulkSmsMessage::create(['campaign_id'=>$c->id,'phone'=>$phone,'status'=>'queued','amount_minor'=>(string)$p->price_per_sms_minor,'idempotency_key'=>$c->reference.':'.hash('sha256',$phone)]);}return $c;});}
 public function dispatch(int $limit=100):int{$messages=BulkSmsMessage::where('status','queued')->with(['campaign.product.provider'])->orderBy('id')->limit(max(1,min($limit,500)))->get();$sent=0;foreach($messages as $m){$c=$m->campaign;$p=$c?->product;if(!$c||!$p?->provider_id)continue;try{$result=$this->providers->executeProvider($p->provider,'bulk-sms.communication','sms_send',['to'=>$m->phone,'sender'=>$c->sender,'message'=>$c->message,'campaign_reference'=>$c->reference],'bulk-sms:send:'.$m->id);$m->status=$result->accepted?'sent':'failed';$m->provider_status=$result->status;$m->provider_reference=$result->providerReference;$m->error=$result->accepted?null:$result->message;$m->sent_at=$result->accepted?now():null;$m->save();$c->increment($result->accepted?'sent_count':'failed_count');$sent++;}catch(\Throwable $e){$m->status='failed';$m->error='Provider execution failed; safe retry/reconciliation required.';$m->failed_at=now();$m->save();}}return $sent;}
 public function reconcile(int $limit=100):int{$messages=BulkSmsMessage::where('status','sent')->whereNotNull('provider_reference')->with('campaign.product.provider')->orderBy('id')->limit(max(1,min($limit,500)))->get();$n=0;foreach($messages as $m){$p=$m->campaign?->product;if(!$p?->provider_id)continue;try{$r=$this->providers->executeProvider($p->provider,'bulk-sms.communication','sms_status',['provider_reference'=>$m->provider_reference,'campaign_reference'=>$m->campaign->reference],'bulk-sms:status:'.$m->id);$status=strtolower($r->status);if(in_array($status,['delivered','success','successful','completed'],true)){$m->status='delivered';$m->delivered_at=now();$m->save();$m->campaign->increment('delivered_count');}elseif(in_array($status,['failed','rejected','undelivered'],true)){$m->status='failed';$m->failed_at=now();$m->error=$r->message;$m->save();$m->campaign->increment('failed_count');}$n++;}catch(\Throwable $e){report($e);}}return $n;}
}