<?php

return [
    'category' => [
        'code' => 'exam_registration',
        'label' => 'Exam Registration',
        'description' => 'Registration and payment services for school, professional, technical and international examinations. Exam result checking remains owned by the Exams & Results addon.',
    ],

    'bodies' => [
        [
            'code' => 'ican',
            'name' => 'Institute of Chartered Accountants of Nigeria',
            'short_name' => 'ICAN',
            'country' => 'NG',
            'type' => 'professional_accounting',
            'programmes' => ['professional', 'atswa'],
            'services' => ['student_registration', 'exam_registration', 'exemption'],
        ],
        [
            'code' => 'anan',
            'name' => 'Association of National Accountants of Nigeria',
            'short_name' => 'ANAN',
            'country' => 'NG',
            'type' => 'professional_accounting',
            'programmes' => ['professional_examination'],
            'services' => ['student_registration', 'exam_registration'],
        ],
        [
            'code' => 'cibn',
            'name' => 'Chartered Institute of Bankers of Nigeria',
            'short_name' => 'CIBN',
            'country' => 'NG',
            'type' => 'professional_banking',
            'programmes' => ['professional_examination'],
            'services' => ['student_registration', 'exam_registration'],
        ],
        [
            'code' => 'citn',
            'name' => 'Chartered Institute of Taxation of Nigeria',
            'short_name' => 'CITN',
            'country' => 'NG',
            'type' => 'professional_taxation',
            'programmes' => ['professional_examination'],
            'services' => ['student_registration', 'exam_registration'],
        ],
        [
            'code' => 'cis',
            'name' => 'Chartered Institute of Stockbrokers',
            'short_name' => 'CIS',
            'country' => 'NG',
            'type' => 'professional_finance',
            'programmes' => ['professional_examination'],
            'services' => ['student_registration', 'exam_registration'],
        ],
        [
            'code' => 'cipm',
            'name' => 'Chartered Institute of Personnel Management of Nigeria',
            'short_name' => 'CIPM',
            'country' => 'NG',
            'type' => 'professional_hr',
            'programmes' => ['professional_examination'],
            'services' => ['student_registration', 'exam_registration'],
        ],
        [
            'code' => 'ciin',
            'name' => 'Chartered Insurance Institute of Nigeria',
            'short_name' => 'CIIN',
            'country' => 'NG',
            'type' => 'professional_insurance',
            'programmes' => ['professional_examination'],
            'services' => ['student_registration', 'exam_registration'],
        ],
        [
            'code' => 'icsan',
            'name' => 'Institute of Chartered Secretaries and Administrators of Nigeria',
            'short_name' => 'ICSAN',
            'country' => 'NG',
            'type' => 'professional_corporate_governance',
            'programmes' => ['professional_examination'],
            'services' => ['student_registration', 'exam_registration'],
        ],
        [
            'code' => 'nim',
            'name' => 'Nigerian Institute of Management (Chartered)',
            'short_name' => 'NIM',
            'country' => 'NG',
            'type' => 'professional_management',
            'programmes' => ['professional_examination', 'professional_certification'],
            'services' => ['registration', 'exam_registration'],
        ],
        [
            'code' => 'acca',
            'name' => 'Association of Chartered Certified Accountants',
            'short_name' => 'ACCA',
            'country' => 'INT',
            'type' => 'international_accounting',
            'programmes' => ['acca_qualification'],
            'services' => ['student_registration', 'exam_registration'],
        ],
        [
            'code' => 'cima',
            'name' => 'Chartered Institute of Management Accountants',
            'short_name' => 'CIMA',
            'country' => 'INT',
            'type' => 'international_accounting',
            'programmes' => ['professional_qualification'],
            'services' => ['student_registration', 'exam_registration'],
        ],
        [
            'code' => 'icaew',
            'name' => 'Institute of Chartered Accountants in England and Wales',
            'short_name' => 'ICAEW',
            'country' => 'GB',
            'type' => 'international_accounting',
            'programmes' => ['aca'],
            'services' => ['student_registration', 'exam_registration'],
        ],
        [
            'code' => 'waec',
            'name' => 'West African Examinations Council',
            'short_name' => 'WAEC',
            'country' => 'NG',
            'type' => 'school_examination',
            'programmes' => ['wassce'],
            'services' => ['exam_registration'],
        ],
        [
            'code' => 'neco',
            'name' => 'National Examinations Council',
            'short_name' => 'NECO',
            'country' => 'NG',
            'type' => 'school_examination',
            'programmes' => ['ssce', 'bece'],
            'services' => ['exam_registration'],
        ],
        [
            'code' => 'nabteb',
            'name' => 'National Business and Technical Examinations Board',
            'short_name' => 'NABTEB',
            'country' => 'NG',
            'type' => 'technical_examination',
            'programmes' => ['nabteb'],
            'services' => ['exam_registration'],
        ],
        [
            'code' => 'jamb',
            'name' => 'Joint Admissions and Matriculation Board',
            'short_name' => 'JAMB',
            'country' => 'NG',
            'type' => 'admissions_examination',
            'programmes' => ['utme', 'de'],
            'services' => ['exam_registration'],
        ],
    ],
];
