<?php
return [
 'official_sources' => [
  [
   'key'=>'nuc_universities',
   'name'=>'National Universities Commission — Nigerian University System',
   'url'=>'https://enuc.nuc.edu.ng/nus',
   'category'=>'university',
   'accrediting_body'=>'NUC',
   'import_mode'=>'official_html_table',
   'verified_scope'=>'All universities listed by NUC',
  ],
  [
   'key'=>'nbte_approved_institutions',
   'name'=>'National Board for Technical Education — Approved Institutions',
   'url'=>'https://nbte.gov.ng/nbte/approved%20institutions',
   'category'=>'technical',
   'accrediting_body'=>'NBTE',
   'import_mode'=>'category_linked_official_lists',
   'verified_scope'=>'Federal/state/private polytechnics, colleges of agriculture, colleges of health sciences and technology, colleges of nursing and midwifery, monotechnics, IEIs, vocational enterprise institutions and technical colleges',
  ],
  [
   'key'=>'ncce_accredited_colleges',
   'name'=>'National Commission for Colleges of Education — Accredited Colleges',
   'url'=>'https://www.ncce.gov.ng/AccreditedColleges/Index',
   'category'=>'college_of_education',
   'accrediting_body'=>'NCCE',
   'import_mode'=>'official_html_table',
   'verified_scope'=>'NCCE accredited colleges and institutions offering NCE',
  ],
 ],
 'categories'=>[
  'university'=>'Universities',
  'polytechnic'=>'Polytechnics',
  'college_of_education'=>'Colleges of Education',
  'college_of_agriculture'=>'Colleges of Agriculture',
  'college_of_health'=>'Colleges of Health Sciences/Technology',
  'college_of_nursing'=>'Colleges of Nursing/Midwifery',
  'monotechnic'=>'Monotechnics / Specialized Institutions',
  'innovation_enterprise'=>'Innovation Enterprise Institutions (IEI)',
  'vocational_enterprise'=>'Vocational Enterprise Institutions',
  'technical_college'=>'Technical Colleges',
  'rtc'=>'Rural/Technical/Resource Training Centres (RTC)',
  'other'=>'Other Approved Institutions',
 ],
 'ownerships'=>[
  'federal'=>'Federal',
  'state'=>'State',
  'private'=>'Private',
  'public'=>'Public',
  'community'=>'Community',
  'faith_based'=>'Faith Based',
  'other'=>'Other',
 ],
];
