<?php
namespace Addons\BusinessAgentMerchantReseller\Http\Controllers;
use Addons\BusinessAgentMerchantReseller\Models\{BusinessProfile,BusinessPartner};
use Addons\BusinessAgentMerchantReseller\Services\BusinessPartnerService;
use Illuminate\Http\Request;
use Inertia\Inertia;
class BusinessAdminController{
 public function page(){return Inertia::render('BusinessAdmin');}
 public function partners(){return response()->json(['partners'=>BusinessPartner::with(['user','business'])->latest()->paginate(100)]);}
 public function approve(Request $r,BusinessPartner $partner,BusinessPartnerService $s){$d=$r->validate(['approved'=>'required|boolean','note'=>'nullable|string|max:1000']);return response()->json(['partner'=>$s->approve($partner,$r->user(),$d['approved'],$d['note']??'')]);}
 public function update(Request $r,BusinessPartner $partner){$d=$r->validate(['status'=>'sometimes|in:pending,active,suspended,rejected','pricing_profile'=>'sometimes|string|max:100','daily_limit_minor'=>'nullable|integer|min:0','monthly_limit_minor'=>'nullable|integer|min:0','commission_rate_bps'=>'sometimes|integer|min:0|max:10000','parent_partner_id'=>'nullable|integer|exists:business_partners,id','settlement_mode'=>'sometimes|in:wallet,manual','minimum_balance_minor'=>'sometimes|integer|min:0','service_rules'=>'nullable|array']);if(isset($d['parent_partner_id'])&&((int)$d['parent_partner_id']===$partner->id||BusinessPartner::whereKey($d['parent_partner_id'])->where('status','!=','active')->exists()))abort(422,'Invalid parent partner.');$partner->update($d);$partner->events()->create(['actor_user_id'=>$r->user()->id,'action'=>'commercial_settings_updated','status'=>$partner->status,'metadata'=>['fields'=>array_keys($d)]]);return response()->json(['partner'=>$partner->fresh()]);}
public function pricing(BusinessPartner $partner){return response()->json(['rules'=>\DB::table('business_pricing_rules')->where('business_partner_id',$partner->id)->orderBy('service_key')->orderBy('product_key')->get()]);}
public function savePricing(Request $r,BusinessPartner $partner){$d=$r->validate(['service_key'=>'required|string|max:100','product_key'=>'nullable|string|max:150','rule_type'=>'required|in:markup,commission,discount','amount_minor'=>'nullable|integer|min:0','rate_bps'=>'nullable|integer|min:0|max:10000','min_amount_minor'=>'nullable|integer|min:0','max_amount_minor'=>'nullable|integer|min:0','enabled'=>'sometimes|boolean']);if(($d['amount_minor']??null)===null&&($d['rate_bps']??null)===null)abort(422,'Provide a fixed amount or rate.');if(isset($d['min_amount_minor'],$d['max_amount_minor'])&&$d['min_amount_minor']>$d['max_amount_minor'])abort(422,'Minimum amount cannot exceed maximum amount.');$id=$r->input('id');if($id){\DB::table('business_pricing_rules')->where('id',$id)->where('business_partner_id',$partner->id)->update(array_merge($d,['updated_at'=>now()]));}else{\DB::table('business_pricing_rules')->insert(array_merge($d,['business_partner_id'=>$partner->id,'created_at'=>now(),'updated_at'=>now()]));}return response()->json(['rules'=>\DB::table('business_pricing_rules')->where('business_partner_id',$partner->id)->get()]);}
}
