import { Head, Link, router } from '@inertiajs/react';
import { FormEvent, useState } from 'react';

type AddonEvent={id:number;event:string;from_status:string|null;to_status:string|null;message:string|null;created_at:string|null};
type Addon={id:number;identifier:string;name:string;version:string;status:string;last_error:string|null;dependencies:Array<string|{identifier?:string}>;permissions:string[];installed_at:string|null;activated_at:string|null;events:AddonEvent[]};
type AvailableAddon={identifier:string;name:string;version:string;compatibility:string|null;dependencies:Array<string|{identifier?:string}>;permissions:string[]};
type Props={addons:Addon[];availableAddons:AvailableAddon[]};

const busy=new Set(['validating','installing','enabling','disabling','updating','uninstalling']);
const date=(v:string|null)=>v?new Date(v).toLocaleString():'Not recorded';
const statusClass:Record<string,string>={active:'bg-emerald-100 text-emerald-800',installed:'bg-blue-100 text-blue-800',inactive:'bg-amber-100 text-amber-800',failed:'bg-red-100 text-red-800',archived:'bg-slate-200 text-slate-700',draft:'bg-slate-100 text-slate-700',validating:'bg-violet-100 text-violet-800',installing:'bg-violet-100 text-violet-800',enabling:'bg-violet-100 text-violet-800',disabling:'bg-violet-100 text-violet-800',updating:'bg-indigo-100 text-indigo-800',uninstalling:'bg-violet-100 text-violet-800'};

export default function Addons({addons,availableAddons}:Props){
 const [processing,setProcessing]=useState<string|null>(null);
 const [selected,setSelected]=useState('');
 const [updating,setUpdating]=useState<number|null>(null);
 const register=(e:FormEvent)=>{e.preventDefault();if(!selected||processing)return;setProcessing('register');router.post('/admin/addons/register',{identifier:selected},{onSuccess:()=>setSelected(''),onFinish:()=>setProcessing(null)});};
 const action=(url:string,key:string,confirm?:string)=>{if(processing||(confirm&&!window.confirm(confirm)))return;setProcessing(key);router.post(url,undefined,{onFinish:()=>setProcessing(null)});};
 const update=(addon:Addon,e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);setProcessing('update:'+addon.id);router.post('/admin/addons/'+addon.id+'/update',{identifier:addon.identifier,name:String(d.get('name')||addon.name),version:String(d.get('version')||''),compatibility:String(d.get('compatibility')||'')||null,dependencies:String(d.get('dependencies')||'').split(',').map(x=>x.trim()).filter(Boolean),permissions:String(d.get('permissions')||'').split(',').map(x=>x.trim()).filter(Boolean)},{onSuccess:()=>setUpdating(null),onFinish:()=>setProcessing(null)});};
 return <><Head title="Addon Manager"/><main className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-7xl">
  <Link href="/dashboard" className="text-sm font-semibold text-indigo-700">← Dashboard</Link>
  <div className="mt-3"><h1 className="text-3xl font-extrabold tracking-tight text-slate-900">Addon Manager</h1><p className="mt-2 text-sm text-slate-600">Discover, register, install, activate, update, disable and archive addons from their manifests. This page contains no addon-specific registration logic.</p></div>
  <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-indigo-600">Addon registry</p><h2 className="mt-1 text-xl font-extrabold text-slate-900">Available addons</h2><p className="mt-1 text-sm text-slate-600">New addons appear here automatically when their manifest is installed under the addon registry.</p></div><form onSubmit={register} className="flex flex-col gap-2 sm:flex-row"><select value={selected} onChange={e=>setSelected(e.target.value)} disabled={!!processing} className="min-w-64 rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="">Select an addon…</option>{availableAddons.filter(a=>!addons.some(x=>x.identifier===a.identifier)).map(a=><option key={a.identifier} value={a.identifier}>{a.name} · v{a.version}</option>)}</select><button disabled={!selected||!!processing} className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{processing==='register'?'Registering…':'Register addon'}</button></form></div>
   {availableAddons.length===0&&<p className="mt-4 rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No addon manifests were discovered.</p>}
   <div className="mt-4 grid gap-3 md:grid-cols-2">{availableAddons.map(a=><div key={a.identifier} className="rounded-xl border border-slate-100 bg-slate-50 p-4"><p className="font-bold text-slate-900">{a.name}</p><p className="mt-1 text-xs font-mono text-slate-500">{a.identifier} · v{a.version}</p><p className="mt-2 text-xs text-slate-600">Core {a.compatibility||'Any'} · Dependencies: {a.dependencies.length?'declared':'None'}</p></div>)}</div>
  </section>
  <div className="mt-6 grid gap-4">{addons.length===0&&<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No addons registered yet.</div>}
  {addons.map(a=>{const isBusy=busy.has(a.status)||!!processing;return <article key={a.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-extrabold text-slate-900">{a.name}</h2><span className={'rounded-full px-2.5 py-1 text-xs font-bold uppercase '+(statusClass[a.status]||'bg-slate-100 text-slate-700')}>{busy.has(a.status)?a.status+'…':a.status}</span></div><p className="mt-1 text-xs font-mono text-slate-500">{a.identifier} · v{a.version}</p>{a.last_error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{a.last_error}</p>}</div><div className="flex flex-wrap gap-2">
  {(a.status==='draft'||a.status==='failed'||a.status==='inactive')&&<button disabled={isBusy} onClick={()=>action('/admin/addons/'+a.id+'/install','install:'+a.id)} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">{processing==='install:'+a.id?'Installing…':'Install'}</button>}
  {(a.status==='installed'||a.status==='inactive')&&<button disabled={isBusy} onClick={()=>action('/admin/addons/'+a.id+'/activate','activate:'+a.id)} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">{processing==='activate:'+a.id?'Activating…':'Activate'}</button>}
  {['installed','active','inactive'].includes(a.status)&&<button onClick={()=>setUpdating(updating===a.id?null:a.id)} className="rounded-lg border border-indigo-300 px-3 py-2 text-xs font-bold text-indigo-700">{updating===a.id?'Close update':'Update'}</button>}
  {a.status==='active'&&<button disabled={isBusy} onClick={()=>action('/admin/addons/'+a.id+'/disable','disable:'+a.id)} className="rounded-lg bg-amber-500 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">Disable</button>}
  {['installed','inactive','failed'].includes(a.status)&&<button disabled={isBusy} onClick={()=>action('/admin/addons/'+a.id+'/uninstall','uninstall:'+a.id,'Uninstall this addon? It will be archived after the lifecycle operation.')} className="rounded-lg border border-red-300 px-3 py-2 text-xs font-bold text-red-700 disabled:opacity-50">Uninstall</button>}
  {a.status==='draft'&&<button disabled={isBusy} onClick={()=>action('/admin/addons/'+a.id+'/archive','archive:'+a.id,'Archive this addon?')} className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-bold text-slate-700 disabled:opacity-50">Archive</button>}
 </div></div>
 {updating===a.id&&<form onSubmit={e=>update(a,e)} className="mt-5 rounded-xl border border-indigo-100 bg-indigo-50 p-4"><p className="text-sm font-bold">Update addon manifest</p><div className="mt-3 grid gap-3 md:grid-cols-2"><input name="name" defaultValue={a.name} required className="rounded-lg border px-3 py-2 text-sm"/><input name="version" required placeholder="New semantic version" className="rounded-lg border px-3 py-2 text-sm"/><input name="compatibility" placeholder="Core compatibility" className="rounded-lg border px-3 py-2 text-sm"/><input name="dependencies" defaultValue={a.dependencies.map(d=>typeof d==='string'?d:d.identifier).filter(Boolean).join(',')} placeholder="Dependencies, comma separated" className="rounded-lg border px-3 py-2 text-sm"/><input name="permissions" defaultValue={a.permissions.join(',')} placeholder="Permissions, comma separated" className="rounded-lg border px-3 py-2 text-sm md:col-span-2"/></div><button disabled={processing==='update:'+a.id} className="mt-3 rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold text-white">Validate & update</button></form>}
 <div className="mt-5 grid gap-4 border-t pt-4 md:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Dependencies</p><p className="mt-1 text-sm text-slate-600">{a.dependencies.length?a.dependencies.map(d=>typeof d==='string'?d:d.identifier).filter(Boolean).join(', '):'None'}</p></div><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Permissions</p><div className="mt-2 flex flex-wrap gap-1.5">{a.permissions.map(p=><span key={p} className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-semibold">{p}</span>)}</div><p className="mt-3 text-xs text-slate-500">Installed: {date(a.installed_at)} · Activated: {date(a.activated_at)}</p></div></div></article>})}</div>
 </div></main></>;
}
