import {Head,Link} from '@inertiajs/react';
type Conversation={uuid:string;title:string;status:string;supportTicketId:number|null;createdAt:string;lastMessageAt:string|null;userName:string|null;userEmail:string|null};
type Message={id:number;role:string;content:string;provider:string|null;model:string|null;inputTokens:number|null;outputTokens:number|null;createdAt:string};
type Props={conversation:Conversation;messages:Message[]};
export default function AIChatbotConversation({conversation,messages}:Props){
 return <div className="mx-auto max-w-5xl space-y-5 p-4 md:p-6"><Head title={'AI conversation · '+conversation.title}/><header className="flex flex-wrap items-start justify-between gap-3"><div><Link href="/admin/ai-chatbot/conversations" className="text-sm text-indigo-600 underline">← All conversations</Link><h1 className="mt-2 text-2xl font-bold">{conversation.title}</h1><p className="mt-1 break-all text-xs text-slate-500">{conversation.uuid}</p></div><span className="rounded-full border px-3 py-1 text-sm">{conversation.status}</span></header>
 <section className="grid gap-3 rounded-xl border p-4 text-sm sm:grid-cols-2 dark:border-slate-700"><div><span className="text-slate-500">User</span><div className="font-medium">{conversation.userName??'Visitor'}</div><div className="text-slate-500">{conversation.userEmail??'Anonymous visitor'}</div></div><div><span className="text-slate-500">Created</span><div>{conversation.createdAt}</div><span className="mt-2 block text-slate-500">Last activity</span><div>{conversation.lastMessageAt??'No messages yet'}</div></div>{conversation.supportTicketId&&<div className="sm:col-span-2"><a className="text-indigo-600 underline" href={'/support/'+conversation.supportTicketId}>Open support ticket #{conversation.supportTicketId}</a></div>}</section>
 <section className="space-y-4"><h2 className="text-lg font-semibold">Conversation transcript ({messages.length} messages shown, maximum 500)</h2>{messages.map(m=><article key={m.id} className="rounded-xl border p-4 dark:border-slate-700"><div className="flex flex-wrap items-center justify-between gap-2"><div className="font-semibold capitalize">{m.role}</div><time className="text-xs text-slate-500">{m.createdAt}</time></div><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-6">{m.content}</p>{m.role==='assistant'&&(m.provider||m.model||m.inputTokens!==null||m.outputTokens!==null)&&<div className="mt-3 border-t pt-2 text-xs text-slate-500 dark:border-slate-700">{[m.provider,m.model,m.inputTokens!==null?'Input tokens: '+m.inputTokens:null,m.outputTokens!==null?'Output tokens: '+m.outputTokens:null].filter(Boolean).join(' · ')}</div>}</article>)}{messages.length===0&&<div className="rounded-xl border p-8 text-center text-slate-500">No messages are stored for this conversation.</div>}</section></div>;
}
