import {Head,router,useForm} from '@inertiajs/react';
type Provider={id:number;name:string;driver:string;model:string;enabled:boolean;priority:number;hasKey:boolean;lastTestStatus:string|null;lastTestMessage:string|null};
type Knowledge={id:number;title:string;category:string;content:string;source_url:string|null;published:boolean};
type Props={settings:Record<string,any>;providers:Provider[];knowledge:Knowledge[];stats:Record<string,number>};
export default function AIChatbot({settings,providers,knowledge,stats}:Props){
 const p=useForm({name:'',driver:'openai',model:'gpt-4o-mini',api_key:'',enabled:false,priority:100,timeout_seconds:20,max_output_tokens:600});
 const s=useForm({enabled:!!settings.enabled,public_enabled:!!settings.public_enabled,assistant_name:String(settings.assistant_name),welcome_message:String(settings.welcome_message),allowed_paths:(settings.allowed_paths??[]) as string[],excluded_paths:(settings.excluded_paths??[]) as string[],retention_days:Number(settings.retention_days??90),max_message_chars:Number(settings.max_message_chars??4000),max_context_messages:Number(settings.max_context_messages??12)});
 const k=useForm({title:'',category:'general',content:'',source_url:'',published:false});
 return <div className="mx-auto max-w-7xl space-y-6 p-4 md:p-6"><Head title="AI Chatbot"/><header><h1 className="text-2xl font-bold">AI Chatbot & Platform Assistant</h1><p className="mt-1 text-sm text-slate-500">Manage providers, published knowledge and page visibility.</p></header>
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{Object.entries({Conversations:stats.conversations??0,Messages:stats.messages??0,Knowledge:stats.knowledgeItems??0,'Enabled providers':stats.enabledProviders??0}).map(([name,value])=><div key={name} className="rounded-xl border p-4 dark:border-slate-700"><div className="text-sm text-slate-500">{name}</div><div className="mt-2 text-2xl font-semibold">{value}</div></div>)}</div>
 <section className="rounded-xl border p-5 dark:border-slate-700"><h2 className="mb-4 text-lg font-semibold">Assistant settings</h2><form className="grid gap-4 md:grid-cols-2" onSubmit={e=>{e.preventDefault();s.put('/admin/ai-chatbot/settings')}}>
 <label className="flex gap-2"><input type="checkbox" checked={s.data.enabled} onChange={e=>s.setData('enabled',e.target.checked)}/> Enable assistant</label><label className="flex gap-2"><input type="checkbox" checked={s.data.public_enabled} onChange={e=>s.setData('public_enabled',e.target.checked)}/> Allow public visitors</label>
 <label>Assistant name<input className="mt-1 w-full rounded border p-2 dark:bg-slate-800" value={s.data.assistant_name} onChange={e=>s.setData('assistant_name',e.target.value)}/></label><label>Welcome message<input className="mt-1 w-full rounded border p-2 dark:bg-slate-800" value={s.data.welcome_message} onChange={e=>s.setData('welcome_message',e.target.value)}/></label>
 <label>Allowed paths, one per line<textarea rows={4} className="mt-1 w-full rounded border p-2 dark:bg-slate-800" value={s.data.allowed_paths.join('\n')} onChange={e=>s.setData('allowed_paths',e.target.value.split('\n').map(x=>x.trim()).filter(Boolean))}/></label><label>Excluded paths, one per line<textarea rows={4} className="mt-1 w-full rounded border p-2 dark:bg-slate-800" value={s.data.excluded_paths.join('\n')} onChange={e=>s.setData('excluded_paths',e.target.value.split('\n').map(x=>x.trim()).filter(Boolean))}/></label>
 <label>Retention days<input type="number" min="1" max="3650" className="mt-1 w-full rounded border p-2 dark:bg-slate-800" value={s.data.retention_days} onChange={e=>s.setData('retention_days',Number(e.target.value))}/></label><label>Max message characters<input type="number" min="100" max="4000" className="mt-1 w-full rounded border p-2 dark:bg-slate-800" value={s.data.max_message_chars} onChange={e=>s.setData('max_message_chars',Number(e.target.value))}/></label><label>Context messages<input type="number" min="2" max="30" className="mt-1 w-full rounded border p-2 dark:bg-slate-800" value={s.data.max_context_messages} onChange={e=>s.setData('max_context_messages',Number(e.target.value))}/></label><button className="w-fit rounded-lg bg-indigo-600 px-4 py-2 text-white">Save settings</button></form></section>
 <section className="rounded-xl border p-5 dark:border-slate-700"><h2 className="mb-4 text-lg font-semibold">Add AI provider</h2><form className="grid gap-3 md:grid-cols-4" onSubmit={e=>{e.preventDefault();p.post('/admin/ai-chatbot/providers',{onSuccess:()=>p.reset()})}}><input required placeholder="Provider name" className="rounded border p-2 dark:bg-slate-800" value={p.data.name} onChange={e=>p.setData('name',e.target.value)}/><select className="rounded border p-2 dark:bg-slate-800" value={p.data.driver} onChange={e=>p.setData('driver',e.target.value)}><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="gemini">Google Gemini</option></select><input required placeholder="Model ID" className="rounded border p-2 dark:bg-slate-800" value={p.data.model} onChange={e=>p.setData('model',e.target.value)}/><input required type="password" autoComplete="new-password" placeholder="API key" className="rounded border p-2 dark:bg-slate-800" value={p.data.api_key} onChange={e=>p.setData('api_key',e.target.value)}/><label className="flex gap-2"><input type="checkbox" checked={p.data.enabled} onChange={e=>p.setData('enabled',e.target.checked)}/> Enabled</label><label>Priority<input type="number" min="1" max="10000" className="mt-1 w-full rounded border p-2 dark:bg-slate-800" value={p.data.priority} onChange={e=>p.setData('priority',Number(e.target.value))}/></label><button className="w-fit rounded-lg bg-indigo-600 px-4 py-2 text-white">Add provider</button></form><div className="mt-4 space-y-3">{providers.map(x=><div key={x.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3 dark:border-slate-700"><div><strong>{x.name} · {x.driver}</strong><div className="text-sm text-slate-500">{x.model} · {x.enabled?'Enabled':'Disabled'} · {x.hasKey?'Credential saved':'No credential'} {x.lastTestStatus?'· Test: '+x.lastTestStatus:''}</div>{x.lastTestMessage&&<div className="text-sm">{x.lastTestMessage}</div>}</div><div className="flex gap-2"><button className="rounded border px-3 py-2" onClick={()=>router.post('/admin/ai-chatbot/providers/'+x.id+'/test')}>Test</button><button className="rounded border px-3 py-2" onClick={()=>router.put('/admin/ai-chatbot/providers/'+x.id,{enabled:!x.enabled})}>{x.enabled?'Disable':'Enable'}</button><button className="rounded border border-red-300 px-3 py-2 text-red-600" onClick={()=>{if(confirm('Remove provider?'))router.delete('/admin/ai-chatbot/providers/'+x.id)}}>Remove</button></div></div>)}</div></section>
 <section className="rounded-xl border p-5 dark:border-slate-700"><h2 className="mb-4 text-lg font-semibold">Knowledge base</h2><form className="grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();k.post('/admin/ai-chatbot/knowledge',{onSuccess:()=>k.reset()})}}><input required placeholder="Title" className="rounded border p-2 dark:bg-slate-800" value={k.data.title} onChange={e=>k.setData('title',e.target.value)}/><input placeholder="Category" className="rounded border p-2 dark:bg-slate-800" value={k.data.category} onChange={e=>k.setData('category',e.target.value)}/><textarea required rows={4} placeholder="Approved help content" className="rounded border p-2 md:col-span-2 dark:bg-slate-800" value={k.data.content} onChange={e=>k.setData('content',e.target.value)}/><input type="url" placeholder="Source URL (optional)" className="rounded border p-2 dark:bg-slate-800" value={k.data.source_url} onChange={e=>k.setData('source_url',e.target.value)}/><label className="flex gap-2"><input type="checkbox" checked={k.data.published} onChange={e=>k.setData('published',e.target.checked)}/> Publish</label><button className="w-fit rounded-lg bg-indigo-600 px-4 py-2 text-white">Add knowledge</button></form><div className="mt-4 space-y-3">{knowledge.map(x=><div key={x.id} className="rounded-lg border p-3 dark:border-slate-700"><div className="flex items-center justify-between gap-2"><strong>{x.title} · {x.category}</strong><div className="flex gap-2"><button className="rounded border px-3 py-1" onClick={()=>router.put('/admin/ai-chatbot/knowledge/'+x.id,{published:!x.published})}>{x.published?'Unpublish':'Publish'}</button><button className="rounded border border-red-300 px-3 py-1 text-red-600" onClick={()=>{if(confirm('Delete knowledge item?'))router.delete('/admin/ai-chatbot/knowledge/'+x.id)}}>Delete</button></div></div><p className="mt-2 whitespace-pre-wrap text-sm">{x.content.slice(0,400)}{x.content.length>400?'…':''}</p></div>)}</div></section>
 </div>;
}
