import React from 'react';
import { Head, useForm } from '@inertiajs/react';

type Provider={id:number;name:string;code:string;driver:string;base_url:string|null;priority:number;weight:number;enabled:boolean;paused:boolean;maintenance:boolean;has_credentials:boolean;failure_count:number;last_success_at:string|null;last_error:string|null};

export default function FxProviders({providers}:{providers:Provider[]}) {
  const add=useForm({name:'',code:'',driver:'generic_json',base_url:'',credentials:{api_key:''},settings:{url_template:'',auth:'query',query:{},rate_path:''},priority:100,weight:1,enabled:false});
  const submit=(e:React.FormEvent)=>{e.preventDefault();add.post('/admin/fx-providers',{preserveScroll:true,onSuccess:()=>add.reset()});};
  return <><Head title="FX Rate Providers"/><main className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-6xl">
    <h1 className="text-2xl font-extrabold">Currency & FX Rate Providers</h1>
    <p className="mt-2 text-sm text-slate-600">NGN remains SEMIZZY ONE's accounting currency. FX providers supply reference rates for NGN, USD and future currencies. Add unlimited providers and use priority-based failover.</p>
    <div className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-extrabold">Configured providers</h2><div className="mt-4 space-y-3">{providers.map(p=><div key={p.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><b>{p.name}</b><div className="text-xs text-slate-500">{p.code} · priority {p.priority} · {p.has_credentials?'credentials configured':'credentials missing'}</div></div><form method="post" action={'/admin/fx-providers/'+p.id+'/toggle'}><button className="rounded-lg border px-3 py-2 text-xs">{p.enabled?'Disable':'Enable'}</button></form></div>{p.last_error&&<div className="mt-2 text-xs text-red-600">{p.last_error}</div>}</div>)}</div></div>
    <form onSubmit={submit} className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-extrabold">Add FX provider</h2><p className="mt-1 text-xs text-slate-500">Unlimited providers are supported. Keep new providers disabled until credentials and response mapping have been tested.</p><div className="mt-4 grid gap-3 md:grid-cols-2">
      <input required className="rounded-xl border p-3" placeholder="Provider name" value={add.data.name} onChange={e=>add.setData('name',e.target.value)}/><input required className="rounded-xl border p-3" placeholder="Unique code" value={add.data.code} onChange={e=>add.setData('code',e.target.value)}/><input className="rounded-xl border p-3 md:col-span-2" placeholder="Base URL" value={add.data.base_url} onChange={e=>add.setData('base_url',e.target.value)}/><input className="rounded-xl border p-3" placeholder="API key" value={add.data.credentials.api_key} onChange={e=>add.setData('credentials',{api_key:e.target.value})}/><input className="rounded-xl border p-3" placeholder="Priority (1 = first)" type="number" value={add.data.priority} onChange={e=>add.setData('priority',Number(e.target.value))}/><input className="rounded-xl border p-3" placeholder="URL template" value={add.data.settings.url_template} onChange={e=>add.setData('settings',{...add.data.settings,url_template:e.target.value})}/><input className="rounded-xl border p-3" placeholder="Rate JSON path e.g. rates.NGN" value={add.data.settings.rate_path} onChange={e=>add.setData('settings',{...add.data.settings,rate_path:e.target.value})}/></div><button disabled={add.processing} className="mt-4 rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white">Add provider</button></form>
  </div></main></>;
}