import React from 'react';
import { Head, router, useForm } from '@inertiajs/react';

type Product={id:number,name:string,key:string,active:boolean,profit_rate:string,term_days:number};
type Investment={id:number,reference:string,status:string,principal_minor:number,profit_minor:number,product:Product};
type Security={id:number,symbol:string,name:string,asset_type:string,market?:string|null,exchange?:string|null,currency:string,status:string,quotes?:any[]};
type Provider={id:number,name:string,key:string,provider_type:string,status:string,verified:boolean,is_data_provider:boolean,is_execution_provider:boolean};

export default function AdminInvestments({products=[],investments,securities,providers=[]}:{products?:Product[];investments?:{data:Investment[]};securities?:{data:Security[]};providers?:Provider[]}){
 const securityForm=useForm({symbol:'',name:'',asset_type:'equity',market:'NGX',exchange:'',isin:'',currency:'NGN',country:'NG',description:''});
 const providerForm=useForm({name:'',key:'',provider_type:'market_data',regulatory_note:'',is_data_provider:true,is_execution_provider:false});
 const quoteForm=useForm({security_id:'',source:'',last_price:'',currency:'NGN',observed_at:'',expires_at:''});
 const submit=(url:string,form:any)=>form.post(url,{preserveScroll:true});
 return <><Head title="Stocks & Investments Marketplace Admin"/><div className="space-y-6 p-6">
  <div><h1 className="text-2xl font-bold">Stocks &amp; Investments Marketplace</h1><p className="text-sm opacity-70">Manage investment products, published securities, approved providers and source-labelled quote snapshots. Trading stays disabled until a real verified execution provider is configured.</p></div>
  <section className="rounded-xl border p-5"><h2 className="mb-4 font-semibold">Investment products</h2>{products.length===0?<p className="opacity-60">No products.</p>:<div className="space-y-2">{products.map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-3 border-b py-3 last:border-b-0"><div><b>{p.name}</b><div className="text-sm opacity-60">{p.profit_rate}% · {p.term_days} days · {p.active?'Active':'Disabled'}</div></div><button type="button" onClick={()=>router.post('/admin/investments/products/'+p.id+'/toggle',{},{preserveScroll:true})} className="rounded border px-3 py-2 text-sm">{p.active?'Disable':'Enable'}</button></div>)}</div>}</section>
  <section className="rounded-xl border p-5"><h2 className="mb-4 font-semibold">Add security draft</h2><form className="grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();submit('/admin/investments/securities',securityForm)}}><input className="rounded border p-3" placeholder="Symbol" value={securityForm.data.symbol} onChange={e=>securityForm.setData('symbol',e.target.value)}/><input className="rounded border p-3" placeholder="Security name" value={securityForm.data.name} onChange={e=>securityForm.setData('name',e.target.value)}/><select className="rounded border p-3" value={securityForm.data.asset_type} onChange={e=>securityForm.setData('asset_type',e.target.value)}><option value="equity">Equity</option><option value="etf">ETF</option><option value="bond">Bond</option><option value="fund">Fund</option><option value="other">Other</option></select><input className="rounded border p-3" placeholder="Exchange e.g. NGX" value={securityForm.data.exchange} onChange={e=>securityForm.setData('exchange',e.target.value)}/><input className="rounded border p-3" placeholder="Market" value={securityForm.data.market} onChange={e=>securityForm.setData('market',e.target.value)}/><input className="rounded border p-3" placeholder="ISIN (optional)" value={securityForm.data.isin} onChange={e=>securityForm.setData('isin',e.target.value)}/><input className="rounded border p-3" placeholder="Currency" value={securityForm.data.currency} onChange={e=>securityForm.setData('currency',e.target.value)}/><input className="rounded border p-3" placeholder="Country code" value={securityForm.data.country} onChange={e=>securityForm.setData('country',e.target.value)}/><textarea className="rounded border p-3 md:col-span-2" placeholder="Description / provenance note" value={securityForm.data.description} onChange={e=>securityForm.setData('description',e.target.value)}/><button disabled={securityForm.processing} className="rounded bg-black px-4 py-3 text-white md:col-span-2">{securityForm.processing?'Saving…':'Save draft'}</button></form></section>
  <section className="rounded-xl border p-5"><h2 className="mb-4 font-semibold">Security catalogue</h2>{(securities?.data??[]).length===0?<p className="opacity-60">No securities yet.</p>:<div className="space-y-2">{(securities?.data??[]).map(s=><div key={s.id} className="flex flex-wrap items-center justify-between gap-3 border-b py-3 last:border-b-0"><div><b>{s.symbol} — {s.name}</b><div className="text-sm opacity-60">{s.asset_type} · {s.exchange||s.market||'—'} · {s.status}</div></div>{s.status==='published'?<button type="button" onClick={()=>router.post('/admin/investments/securities/'+s.id+'/unpublish',{}, {preserveScroll:true})} className="rounded border px-3 py-2 text-sm">Unpublish</button>:<button type="button" onClick={()=>router.post('/admin/investments/securities/'+s.id+'/publish',{}, {preserveScroll:true})} className="rounded border px-3 py-2 text-sm">Publish</button>}</div>)}</div>}</section>
  <section className="rounded-xl border p-5"><h2 className="mb-4 font-semibold">Market-data providers</h2><form className="grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();submit('/admin/investments/providers',providerForm)}}><input className="rounded border p-3" placeholder="Provider name" value={providerForm.data.name} onChange={e=>providerForm.setData('name',e.target.value)}/><input className="rounded border p-3" placeholder="Unique key" value={providerForm.data.key} onChange={e=>providerForm.setData('key',e.target.value)}/><select className="rounded border p-3" value={providerForm.data.provider_type} onChange={e=>providerForm.setData('provider_type',e.target.value)}><option value="market_data">Market data</option><option value="broker">Broker</option><option value="both">Both</option><option value="custodian">Custodian</option><option value="other">Other</option></select><input className="rounded border p-3" placeholder="Regulatory note / licence reference" value={providerForm.data.regulatory_note} onChange={e=>providerForm.setData('regulatory_note',e.target.value)}/><label className="flex items-center gap-2"><input type="checkbox" checked={providerForm.data.is_data_provider} onChange={e=>providerForm.setData('is_data_provider',e.target.checked)}/> Data provider</label><label className="flex items-center gap-2"><input type="checkbox" checked={providerForm.data.is_execution_provider} onChange={e=>providerForm.setData('is_execution_provider',e.target.checked)}/> Execution provider</label><button disabled={providerForm.processing} className="rounded bg-black px-4 py-3 text-white md:col-span-2">{providerForm.processing?'Saving…':'Save disabled provider'}</button></form><div className="mt-5 space-y-2">{providers.map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-3 border-b py-3 last:border-b-0"><div><b>{p.name}</b><div className="text-sm opacity-60">{p.provider_type} · {p.status} · {p.verified?'Verified':'Unverified'}</div></div><div className="flex gap-2">{!p.verified&&<button type="button" onClick={()=>router.post('/admin/investments/providers/'+p.id+'/verify',{}, {preserveScroll:true})} className="rounded border px-3 py-2 text-sm">Verify &amp; enable</button>}{p.status==='enabled'&&<button type="button" onClick={()=>router.post('/admin/investments/providers/'+p.id+'/disable',{}, {preserveScroll:true})} className="rounded border px-3 py-2 text-sm">Disable</button>}</div></div>)}</div></section>
  <section className="rounded-xl border p-5"><h2 className="mb-4 font-semibold">Record a quote snapshot</h2><form className="grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();if(quoteForm.data.security_id)submit('/admin/investments/securities/'+quoteForm.data.security_id+'/quotes',quoteForm)}}><select className="rounded border p-3" value={quoteForm.data.security_id} onChange={e=>quoteForm.setData('security_id',e.target.value)}><option value="">Select security</option>{(securities?.data??[]).map(s=><option key={s.id} value={s.id}>{s.symbol} — {s.name}</option>)}</select><input className="rounded border p-3" placeholder="Approved source name" value={quoteForm.data.source} onChange={e=>quoteForm.setData('source',e.target.value)}/><input className="rounded border p-3" placeholder="Last price" type="number" step="0.0001" value={quoteForm.data.last_price} onChange={e=>quoteForm.setData('last_price',e.target.value)}/><input className="rounded border p-3" placeholder="Currency" value={quoteForm.data.currency} onChange={e=>quoteForm.setData('currency',e.target.value)}/><input className="rounded border p-3" type="datetime-local" value={quoteForm.data.observed_at} onChange={e=>quoteForm.setData('observed_at',e.target.value)}/><input className="rounded border p-3" type="datetime-local" value={quoteForm.data.expires_at} onChange={e=>quoteForm.setData('expires_at',e.target.value)}/><button disabled={quoteForm.processing} className="rounded bg-black px-4 py-3 text-white md:col-span-2">{quoteForm.processing?'Recording…':'Record quote snapshot'}</button></form></section>
  <section className="rounded-xl border p-5"><h2 className="mb-3 font-semibold">Investment accounts</h2>{(investments?.data??[]).length===0?<p className="opacity-60">No investment accounts.</p>:<div className="space-y-2">{investments?.data.map(i=><div key={i.id} className="border-b py-2">{i.reference} — {i.status} — ₦{Number(i.principal_minor)/100}</div>)}</div>}</section>
 </div></>;
}
