import { Head, router, useForm } from '@inertiajs/react';
import { useState } from 'react';

type Method={id:number;name:string;bank_name:string;account_name:string;account_number:string;instructions?:string|null;currency:string;enabled:boolean;priority:number};
type Deposit={id:number;reference:string;user?:{id:number;name?:string|null;email?:string|null};method?:Method|null;amount_minor:string;currency:string;status:string;proof_original_name?:string|null;user_note?:string|null;admin_note?:string|null;submitted_at?:string|null;reviewed_at?:string|null;proof_url:string};

export default function ManualDeposits({methods=[],deposits}:{methods?:Method[];deposits:{data?:Deposit[]}|Deposit[]}){
 const rows=Array.isArray(deposits)?deposits:(deposits?.data||[]);
 const [note,setNote]=useState<Record<number,string>>({});
 const form=useForm({name:'',bank_name:'',account_name:'',account_number:'',instructions:'',priority:100});
 const money=(minor:string)=>{try{const n=BigInt(minor);return '₦'+(n/100n).toLocaleString()+'.'+(n%100n).toString().padStart(2,'0')}catch{return '—'}};
 const addMethod=(e:React.FormEvent)=>{e.preventDefault();form.post('/admin/payments/manual-deposits/methods',{preserveScroll:true,onSuccess:()=>form.reset()})};
 const review=(id:number,action:'approve'|'reject')=>router.post('/admin/payments/manual-deposits/'+id+'/'+action,{admin_note:note[id]||''},{preserveScroll:true});
 return <><Head title="Manual Deposits"/><main className="min-h-screen bg-slate-50 p-4 text-slate-900 sm:p-8"><div className="mx-auto max-w-7xl">
  <header><p className="text-xs font-black uppercase tracking-wider text-indigo-600">SEMIZZY ONE · PAYMENTS</p><h1 className="mt-1 text-2xl font-black">Manual NGN Deposits</h1><p className="mt-2 text-sm text-slate-500">Review payment proof and approve only verified deposits. Approval credits the existing Core NGN wallet once, idempotently.</p></header>
  <section className="mt-6 rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="font-black">Bank deposit methods</h2><form onSubmit={addMethod} className="mt-4 grid gap-3 md:grid-cols-3"><input className="rounded-xl border p-3" placeholder="Method name" value={form.data.name} onChange={e=>form.setData('name',e.target.value)}/><input className="rounded-xl border p-3" placeholder="Bank name" value={form.data.bank_name} onChange={e=>form.setData('bank_name',e.target.value)}/><input className="rounded-xl border p-3" placeholder="Account name" value={form.data.account_name} onChange={e=>form.setData('account_name',e.target.value)}/><input className="rounded-xl border p-3" placeholder="Account number" inputMode="numeric" value={form.data.account_number} onChange={e=>form.setData('account_number',e.target.value)}/><input className="rounded-xl border p-3" placeholder="Priority" type="number" value={form.data.priority} onChange={e=>form.setData('priority',Number(e.target.value))}/><button disabled={form.processing} className="rounded-xl bg-indigo-600 p-3 font-black text-white">Create Disabled Method</button><textarea className="rounded-xl border p-3 md:col-span-3" rows={2} placeholder="Customer instructions (optional)" value={form.data.instructions} onChange={e=>form.setData('instructions',e.target.value)}/></form>
   <div className="mt-5 space-y-2">{methods.map(m=><div key={m.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div><b>{m.name}</b><span className="ml-2 text-sm text-slate-500">{m.bank_name} · {m.account_number} · {m.account_name}</span></div><button onClick={()=>router.post('/admin/payments/manual-deposits/methods/'+m.id+'/toggle',{}, {preserveScroll:true})} className="rounded-lg border px-3 py-2 text-xs font-bold">{m.enabled?'Disable':'Enable'}</button></div>)}</div>
  </section>
  <section className="mt-6 overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-slate-200"><div className="border-b p-5"><h2 className="font-black">Deposit requests</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Reference</th><th className="p-3">User</th><th className="p-3">Amount</th><th className="p-3">Method</th><th className="p-3">Proof</th><th className="p-3">Status</th><th className="p-3">Review</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={7} className="p-8 text-center text-slate-500">No manual deposit requests.</td></tr>:rows.map(d=><tr key={d.id} className="border-t align-top"><td className="p-3 font-mono text-xs">{d.reference}</td><td className="p-3">{d.user?.name||d.user?.email||d.user?.id||'—'}</td><td className="p-3 font-black">{money(d.amount_minor)}</td><td className="p-3">{d.method?.name||'—'}</td><td className="p-3"><a className="font-bold text-indigo-700 underline" href={d.proof_url}>Open proof</a></td><td className="p-3 font-bold uppercase">{d.status}</td><td className="p-3">{d.status==='pending'?<div className="min-w-56"><textarea rows={2} className="w-full rounded-lg border p-2 text-xs" placeholder="Review note" value={note[d.id]||''} onChange={e=>setNote({...note,[d.id]:e.target.value})}/><div className="mt-2 flex gap-2"><button onClick={()=>review(d.id,'approve')} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-black text-white">Approve & Credit</button><button onClick={()=>review(d.id,'reject')} disabled={!note[d.id]?.trim()} className="rounded-lg bg-red-600 px-3 py-2 text-xs font-black text-white disabled:opacity-40">Reject</button></div></div>:<span className="text-xs text-slate-500">{d.admin_note||'Reviewed'}</span>}</td></tr>)}</tbody></table></div></section>
 </div></main></>;
}
