import { Head, useForm } from '@inertiajs/react';
type Props={tiers:any;features:Record<string,boolean>};
const labels:Record<string,string>={registration_enabled:'User registration',kyc_enabled:'KYC applications',finance_enabled:'Wallet & finance',vtu_enabled:'VTU services',support_enabled:'Support centre',notifications_enabled:'Notifications',api_enabled:'API access',maintenance_mode:'Maintenance mode'};
export default function PlatformControls({tiers,features}:Props){
 const form=useForm({features,tiers:Object.fromEntries(Object.entries(tiers).map(([id,t]:any)=>[id,{daily_limit_minor:t.daily_limit_minor??'',balance_limit_minor:t.balance_limit_minor??''}]))});
 const submit=(e:React.FormEvent)=>{e.preventDefault();form.put('/admin/platform-controls',{preserveScroll:true});};
 return <><Head title="Platform controls"/><main className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-6xl"><header><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">SEMIZZY ONE · ADMIN CONTROL CENTER</p><h1 className="mt-1 text-3xl font-black">Platform controls</h1><p className="mt-2 text-sm text-slate-600">Central control for tier limits and major platform capabilities. Financial values are stored in minor units; NGN uses kobo.</p></header>
 <form onSubmit={submit} className="mt-6 space-y-6"><section className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Platform functions</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(labels).map(([key,label])=><label key={key} className="flex items-center justify-between rounded-2xl border p-4"><span className="text-sm font-bold">{label}</span><input type="checkbox" checked={!!form.data.features[key]} onChange={e=>form.setData('features',{...form.data.features,[key]:e.target.checked})} /></label>)}</div><p className="mt-3 text-xs text-slate-500">Maintenance mode is stored centrally and can be wired to additional modules without changing their business logic.</p></section>
 <section className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Tier limits</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{tiers.map((t:any)=><div key={t.id} className="rounded-2xl border p-4"><div className="flex items-center justify-between"><h3 className="font-black">{t.name}</h3><span className="text-xs text-slate-500">Tier {t.id}</span></div><label className="mt-4 block text-sm font-bold">Daily transaction limit (kobo)<input inputMode="numeric" className="mt-1 w-full rounded-xl border p-3 font-normal" value={form.data.tiers[t.id]?.daily_limit_minor??''} onChange={e=>form.setData('tiers',{...form.data.tiers,[t.id]:{...form.data.tiers[t.id],daily_limit_minor:e.target.value}})} placeholder="0 = unlimited" /></label><label className="mt-3 block text-sm font-bold">Maximum wallet balance (kobo)<input inputMode="numeric" className="mt-1 w-full rounded-xl border p-3 font-normal" value={form.data.tiers[t.id]?.balance_limit_minor??''} onChange={e=>form.setData('tiers',{...form.data.tiers,[t.id]:{...form.data.tiers[t.id],balance_limit_minor:e.target.value}})} placeholder="Leave blank if unlimited" /></label></div>)}</div></section>
 <div className="flex flex-wrap gap-3"><button disabled={form.processing} className="rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white disabled:opacity-50">{form.processing?'Saving…':'Save platform controls'}</button><a href="/admin/users" className="rounded-xl border bg-white px-5 py-3 font-bold">Users</a><a href="/admin/kyc" className="rounded-xl border bg-white px-5 py-3 font-bold">KYC review</a><a href="/admin/settings" className="rounded-xl border bg-white px-5 py-3 font-bold">System settings</a></div></form></div></main></>}