import { Head, router } from '@inertiajs/react';
type Item={id:number;type:string;status:string;user:{id:number;name:string;username:string;email:string;phone:string|null;tier:number};changes:Record<string,string>;reason:string;businessEntityType:string|null;businessRegisteredName:string|null;businessRegistrationNumber:string|null;businessTaxId:string|null;businessRegisteredAddress:string|null;businessState:string|null;businessCountry:string|null;documents:string[];documentCount:number;adminNote:string|null;reviewedAt:string|null;createdAt:string|null};
export default function ProfileChangeRequests({requests}:{requests:{data:Item[];links:any[]}}){
 const review=(id:number,decision:'approved'|'rejected')=>{const note=window.prompt(decision==='approved'?'Optional approval note':'Reason for rejection')??''; if(decision==='rejected'&&!note.trim()){return;} router.post('/admin/profile-change-requests/'+id+'/review',{decision,admin_note:note},{preserveScroll:true});};
 return <main className="min-h-screen bg-slate-50 p-4 md:p-8"><Head title="Profile change requests"/><div className="mx-auto max-w-6xl"><header className="rounded-3xl bg-slate-900 p-6 text-white"><p className="text-xs font-bold uppercase tracking-wider text-slate-300">SEMIZZY ONE · ADMIN</p><h1 className="mt-1 text-2xl font-black">Profile change requests</h1><p className="mt-1 text-sm text-slate-300">Approve or reject sensitive personal and CAC business identity changes.</p></header>
 <section className="mt-5 space-y-4">{requests.data.map(item=><article key={item.id} className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><h2 className="font-black">{item.user.name} <span className="text-slate-400">(@{item.user.username})</span></h2><p className="text-sm text-slate-600">{item.user.email} · {item.user.phone||'No phone'} · Tier {item.user.tier}</p><span className="mt-2 inline-block rounded-full bg-indigo-50 px-3 py-1 text-xs font-black">{item.type} · {item.status}</span></div>{item.status==='pending'&&<div className="flex gap-2"><button onClick={()=>review(item.id,'approved')} className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-black text-white">Approve</button><button onClick={()=>review(item.id,'rejected')} className="rounded-xl bg-red-600 px-4 py-2 text-sm font-black text-white">Reject</button></div>}</div>
 {item.type==='personal'?<div className="mt-4 grid gap-2 md:grid-cols-2">{Object.entries(item.changes).map(([k,v])=><div key={k} className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold uppercase text-slate-400">{k.replaceAll('_',' ')}</p><p className="mt-1 text-sm font-semibold break-all">{v}</p></div>)}</div>:<div className="mt-4 grid gap-2 md:grid-cols-2"><div className="rounded-xl bg-indigo-50 p-3"><p className="text-xs font-bold">Registered entity</p><p className="font-black">{item.businessRegisteredName}</p><p className="text-sm">{item.businessRegistrationNumber} · {item.businessEntityType}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold uppercase text-slate-400">Documents</p><p className="font-semibold">{item.documentCount} uploaded CAC document(s)</p><div className="mt-2 flex flex-wrap gap-2">{item.documents.map((_,i)=><a key={i} href={`/admin/profile-change-requests/${item.id}/documents/${i}`} target="_blank" rel="noreferrer" className="rounded-lg bg-white px-3 py-1.5 text-xs font-bold text-indigo-700">View document {i+1}</a>)}</div></div></div>}
 <p className="mt-4 rounded-2xl bg-amber-50 p-4 text-sm text-amber-900"><b>Reason:</b> {item.reason}</p>
 </article>)}</section>
 <div className="mt-5 flex flex-wrap gap-2">{requests.links.map((l:any,i:number)=><button key={i} disabled={!l.url} onClick={()=>l.url&&router.visit(l.url)} className="rounded-lg border bg-white px-3 py-2 text-sm disabled:opacity-40" dangerouslySetInnerHTML={{__html:l.label}}/>)}</div>
 </div></main>;
}
