import { Head, router, useForm } from '@inertiajs/react';
import { useEffect, useMemo, useState } from 'react';

type Provider={id:number;display_name:string;environment:string;enabled:boolean;verification_status:string;integration_status:string};
type AuthField={key:string;label:string;type:string;secret:boolean;required:boolean;placement:'header'|'query'|'body'|'form'|'authorization';header_name?:string;query_name?:string;body_path?:string;prefix?:string};
type AuthType={value:string;label:string;fields:AuthField[]};
type Credential=AuthField & {id?:number;has_value?:boolean;value?:string};
type Service={id:number;external_service_id:string;external_service_code:string|null;name:string;description:string|null;service_type:string|null;network:string|null;provider_price:string|null;currency:string;status:string;category:string|null;subcategory:string|null};

export default function ProviderWizard({provider}:{provider:Provider}){
 const [step,setStep]=useState(1),[discovering,setDiscovering]=useState(false),[importing,setImporting]=useState(false),[services,setServices]=useState<Service[]>([]),[selected,setSelected]=useState<number[]>([]);
 const [connectionId,setConnectionId]=useState<number|null>(null),[authTypes,setAuthTypes]=useState<AuthType[]>([]),[authType,setAuthType]=useState('none');
 const [credentials,setCredentials]=useState<Credential[]>([]),[customFields,setCustomFields]=useState<AuthField[]>([]);
 const connection=useForm({name:'Default Connection',environment:provider.environment,base_url:'',api_version:'',api_prefix:'',auth_type:'none',auth_options:{},connect_timeout_seconds:10,request_timeout_seconds:30,verify_ssl:true,is_default:true});
 const endpoint=useForm({name:'Service Catalogue',operation:'catalogue_retrieval',method:'GET',path:'',full_url:'',content_type:'json',auth_mode:'connection'});

 useEffect(()=>{fetch('/admin/provider-auth/schema').then(r=>r.json()).then(x=>setAuthTypes(x.data||[]));},[]);
 const loadConnection=()=>fetch('/admin/providers/'+provider.id+'/connections').then(r=>r.json()).then(x=>{const c=x.data?.[0];if(c){setConnectionId(c.id);setAuthType(c.auth_type||'none');setCredentials(c.credentials||[]);}});
 const selectAuth=(type:string)=>{
   setAuthType(type);
   const schema=authTypes.find(x=>x.value===type);
   setCustomFields(type==='custom' ? [] : (schema?.fields||[]));
   setCredentials(type==='custom' ? [] : (schema?.fields||[]).map(f=>({...f,value:''})));
 };
 const updateCredential=(key:string,patch:Partial<Credential>)=>setCredentials(xs=>xs.map(x=>x.key===key?{...x,...patch}:x));
 const addCustomField=()=>setCustomFields(xs=>[...xs,{key:'field_'+(xs.length+1),label:'Custom credential',type:'password',secret:true,required:true,placement:'header',header_name:''}]);
 const saveAuth=()=>{
   if(!connectionId)return;
   const payload={auth_type:authType,auth_options:{custom_fields:authType==='custom'?customFields:[]},credentials:credentials.map(({id,has_value,value,...f})=>({...f,value:value||undefined}))};
   router.post('/admin/provider-connections/'+connectionId+'/authentication',payload,{preserveScroll:true,onSuccess:()=>setStep(4)});
 };
 const discover=()=>{setDiscovering(true);router.post('/admin/providers/'+provider.id+'/discover-services',{}, {preserveScroll:true,onFinish:()=>setDiscovering(false),onSuccess:()=>fetch('/admin/providers/'+provider.id+'/provider-services').then(r=>r.json()).then(x=>setServices(x.data||[]))});};
 const importSelected=()=>{setImporting(true);router.post('/admin/providers/'+provider.id+'/provider-services/import',{provider_service_ids:selected},{preserveScroll:true,onFinish:()=>setImporting(false)});};
 const groups=useMemo(()=>Object.entries(services.reduce((a,s)=>{const k=s.category||'Uncategorized';(a[k]||(a[k]=[])).push(s);return a},{} as Record<string,Service[]>)),[services]);
 const toggle=(id:number)=>setSelected(x=>x.includes(id)?x.filter(i=>i!==id):[...x,id]);
 const saveConnection=()=>connection.post('/admin/providers/'+provider.id+'/connections',{onSuccess:()=>{loadConnection();setStep(3)}} as any);

 return <><Head title={'Provider Setup - '+provider.display_name}/><main className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-6xl">
 <header className="mb-6"><p className="text-sm font-bold text-indigo-700">API PROVIDER SETUP</p><h1 className="text-3xl font-extrabold text-slate-950">{provider.display_name}</h1><p className="mt-2 text-slate-600">Configure authentication without hard-coding a provider, credential type or placement.</p></header>
 <div className="mb-6 grid grid-cols-2 gap-2 md:grid-cols-6">{['Basic','Connection','Authentication','Endpoints','Test & Discover','Select & Import'].map((x,i)=><button key={x} onClick={()=>setStep(i+1)} className={'rounded-xl border p-3 text-left text-xs font-bold '+(step===i+1?'border-indigo-600 bg-indigo-50 text-indigo-800':'border-slate-200 bg-white text-slate-600')}><span className="block text-slate-400">{i+1}</span>{x}</button>)}</div>
 {step===1&&<section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Basic information</h2><p className="mt-2 text-slate-600">Provider records remain normal editable records. No permanent provider is required by the engine.</p><button onClick={()=>setStep(2)} className="mt-6 rounded-xl bg-indigo-700 px-5 py-3 font-semibold text-white">Continue</button></section>}
 {step===2&&<section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Connection</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{[['name','Connection name'],['base_url','Base URL'],['api_version','API version'],['api_prefix','API prefix'],['connect_timeout_seconds','Connect timeout'],['request_timeout_seconds','Request timeout']].map(([k,l])=><label key={k} className="text-sm font-semibold">{l}<input className="mt-1 w-full rounded-xl border p-3 font-normal" value={(connection.data as any)[k]} onChange={e=>connection.setData(k as any,e.target.value)}/></label>)}</div><label className="mt-4 flex gap-2 text-sm"><input type="checkbox" checked={connection.data.verify_ssl} onChange={e=>connection.setData('verify_ssl',e.target.checked)}/> Verify SSL certificate</label><button disabled={connection.processing} onClick={saveConnection} className="mt-6 rounded-xl bg-indigo-700 px-5 py-3 font-semibold text-white disabled:opacity-50">{connection.processing?'Saving...':'Save connection and continue'}</button></section>}
 {step===3&&<section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Dynamic authentication</h2><p className="mt-2 text-slate-600">Choose the authentication model, then configure exactly the fields and placement required by this provider.</p><label className="mt-5 block text-sm font-semibold">Authentication type<select className="mt-1 w-full rounded-xl border p-3 font-normal" value={authType} onChange={e=>selectAuth(e.target.value)}>{authTypes.map(a=><option key={a.value} value={a.value}>{a.label}</option>)}</select></label>
 {authType==='custom'&&<div className="mt-5 space-y-4">{customFields.map((f,i)=><div key={f.key} className="rounded-xl border p-4"><div className="grid gap-3 md:grid-cols-2"><input className="rounded-xl border p-3" value={f.key} onChange={e=>setCustomFields(xs=>xs.map((x,j)=>j===i?{...x,key:e.target.value}:x))} placeholder="Field key"/><input className="rounded-xl border p-3" value={f.label} onChange={e=>setCustomFields(xs=>xs.map((x,j)=>j===i?{...x,label:e.target.value}:x))} placeholder="Label"/><select className="rounded-xl border p-3" value={f.placement} onChange={e=>setCustomFields(xs=>xs.map((x,j)=>j===i?{...x,placement:e.target.value as any}:x))}><option value="header">Header</option><option value="query">Query</option><option value="body">JSON body</option><option value="form">Form</option><option value="authorization">Authorization</option></select><input className="rounded-xl border p-3" value={f.header_name||''} onChange={e=>setCustomFields(xs=>xs.map((x,j)=>j===i?{...x,header_name:e.target.value}:x))} placeholder="Header name (if applicable)"/></div></div>)}<button onClick={addCustomField} className="rounded-xl border px-4 py-2 font-semibold">+ Add credential field</button></div>}
 <div className="mt-5 grid gap-4 md:grid-cols-2">{credentials.map(f=><div key={f.key} className="rounded-xl border p-4"><div className="flex items-center justify-between"><span className="font-semibold">{f.label}</span><span className="text-xs text-slate-500">{f.placement}</span></div><input type={f.secret||f.type==='password'?'password':'text'} className="mt-2 w-full rounded-xl border p-3" value={f.value||''} placeholder={f.has_value?'••••••••':'Enter credential'} onChange={e=>updateCredential(f.key,{value:e.target.value})}/><div className="mt-2 grid gap-2 md:grid-cols-2"><select className="rounded-lg border p-2 text-sm" value={f.placement} onChange={e=>updateCredential(f.key,{placement:e.target.value as any})}><option value="header">Header</option><option value="query">Query</option><option value="body">JSON body</option><option value="form">Form</option><option value="authorization">Authorization</option></select><input className="rounded-lg border p-2 text-sm" value={f.header_name||f.query_name||f.body_path||''} placeholder="Placement field name" onChange={e=>{const v=e.target.value;updateCredential(f.key,f.placement==='header'?{header_name:v}:f.placement==='query'?{query_name:v}:{body_path:v})}}/></div></div>)}</div>
 <button disabled={!connectionId} onClick={saveAuth} className="mt-6 rounded-xl bg-indigo-700 px-5 py-3 font-semibold text-white disabled:opacity-50">{connectionId?'Save authentication and continue':'Save the connection first'}</button></section>}
 {step===4&&<section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Endpoints</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><input className="rounded-xl border p-3" placeholder="Endpoint name" value={endpoint.data.name} onChange={e=>endpoint.setData('name',e.target.value)}/><select className="rounded-xl border p-3" value={endpoint.data.method} onChange={e=>endpoint.setData('method',e.target.value as any)}><option>GET</option><option>POST</option><option>PUT</option><option>PATCH</option><option>DELETE</option></select><input className="rounded-xl border p-3" placeholder="Relative path e.g. /services" value={endpoint.data.path} onChange={e=>endpoint.setData('path',e.target.value)}/><input className="rounded-xl border p-3" placeholder="Full URL override (optional)" value={endpoint.data.full_url} onChange={e=>endpoint.setData('full_url',e.target.value)}/></div><button onClick={()=>endpoint.post('/admin/providers/'+provider.id+'/endpoints',{onSuccess:()=>setStep(5)} as any)} className="mt-6 rounded-xl bg-indigo-700 px-5 py-3 font-semibold text-white">Save endpoint and continue</button></section>}
 {step===5&&<section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Test and discover</h2><p className="mt-2 text-slate-600">Discovery performs a real request using the saved authentication configuration. No fake success is generated.</p><button disabled={discovering} onClick={discover} className="mt-5 rounded-xl bg-indigo-700 px-5 py-3 font-semibold text-white disabled:opacity-50">{discovering?'Discovering...':'Discover Services'}</button>{services.length>0&&<p className="mt-3 text-sm font-semibold text-emerald-700">{services.length} services discovered.</p>}</section>}
 {step===6&&<section className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Select services to import</h2><p className="mt-1 text-slate-600">Nothing is customer-facing until the catalogue/mapping stages approve it.</p></div><button disabled={!selected.length||importing} onClick={importSelected} className="rounded-xl bg-indigo-700 px-5 py-3 font-semibold text-white disabled:opacity-50">{importing?'Importing...':'Import Selected ('+selected.length+')'}</button></div><div className="mt-6 space-y-5">{groups.map(([category,items])=><div key={category} className="overflow-hidden rounded-xl border"><div className="flex items-center justify-between bg-slate-50 p-4"><h3 className="font-bold">{category}</h3><button className="text-sm font-semibold text-indigo-700" onClick={()=>setSelected(s=>Array.from(new Set(s.concat(items.map(x=>x.id)))))}>Select category</button></div>{items.map(s=><label key={s.id} className="flex cursor-pointer items-center gap-3 border-t p-4 hover:bg-slate-50"><input type="checkbox" checked={selected.includes(s.id)} onChange={()=>toggle(s.id)}/><span className="flex-1"><strong>{s.name}</strong><small className="ml-2 text-slate-500">{s.network||''}</small></span><span className="font-semibold">{s.provider_price?s.currency+' '+s.provider_price:'-'}</span><span className="text-xs text-slate-500">{s.status}</span></label>)}</div>)}</div></section>}
 </div></main></>;
}
