import { Head, router, useForm } from '@inertiajs/react';
import { useMemo, useState } from 'react';

type Provider={id:number;display_name:string;environment:string;enabled:boolean;verification_status:string;integration_status:string};
type Service={id:number;external_service_id:string;external_service_code:string|null;name:string;description:string|null;service_type:string|null;network:string|null;provider_price:string|null;currency:string;status:string;category:string|null;subcategory:string|null};

export default function ProviderWizard({provider}:{provider:Provider}){
 const [step,setStep]=useState(1),[discovering,setDiscovering]=useState(false),[importing,setImporting]=useState(false),[services,setServices]=useState<Service[]>([]),[selected,setSelected]=useState<number[]>([]);
 const connection=useForm({name:'Default Connection',environment:provider.environment,base_url:'',api_version:'',api_prefix:'',connect_timeout_seconds:10,request_timeout_seconds:30,verify_ssl:true,is_default:true});
 const endpoint=useForm({name:'Service Catalogue',operation:'catalogue_retrieval',method:'GET',path:'',full_url:'',content_type:'json',auth_mode:'connection'});
 const discover=()=>{setDiscovering(true);router.post('/admin/providers/'+provider.id+'/discover-services',{}, {preserveScroll:true,onFinish:()=>setDiscovering(false),onSuccess:()=>fetch('/admin/providers/'+provider.id+'/provider-services').then(r=>r.json()).then(x=>setServices(x.data||[]))});};
 const importSelected=()=>{setImporting(true);router.post('/admin/providers/'+provider.id+'/provider-services/import',{provider_service_ids:selected},{preserveScroll:true,onFinish:()=>setImporting(false)});};
 const groups=useMemo(()=>Object.entries(services.reduce((a,s)=>{const k=s.category||'Uncategorized';(a[k]||(a[k]=[])).push(s);return a},{} as Record<string,Service[]>)),[services]);
 const toggle=(id:number)=>setSelected(x=>x.includes(id)?x.filter(i=>i!==id):[...x,id]);
 return <><Head title={'Provider Setup - '+provider.display_name}/><main className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-6xl">
 <header className="mb-6"><p className="text-sm font-bold text-indigo-700">API PROVIDER SETUP</p><h1 className="text-3xl font-extrabold text-slate-950">{provider.display_name}</h1><p className="mt-2 text-slate-600">Configure, authenticate, discover and selectively import services. Nothing becomes customer-facing automatically.</p></header>
 <div className="mb-6 grid grid-cols-2 gap-2 md:grid-cols-6">{['Basic','Connection','Authentication','Endpoints','Test & Discover','Select & Import'].map((x,i)=><button key={x} onClick={()=>setStep(i+1)} className={'rounded-xl border p-3 text-left text-xs font-bold '+(step===i+1?'border-indigo-600 bg-indigo-50 text-indigo-800':'border-slate-200 bg-white text-slate-600')}><span className="block text-slate-400">{i+1}</span>{x}</button>)}</div>
 {step===1&&<section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Basic information</h2><p className="mt-2 text-slate-600">Provider record is ready for configuration. The engine does not require a fixed provider list.</p><button onClick={()=>setStep(2)} className="mt-6 rounded-xl bg-indigo-700 px-5 py-3 font-semibold text-white">Continue</button></section>}
 {step===2&&<section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Connection</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{[['name','Connection name'],['base_url','Base URL'],['api_version','API version'],['api_prefix','API prefix'],['connect_timeout_seconds','Connect timeout'],['request_timeout_seconds','Request timeout']].map(([k,l])=><label key={k} className="text-sm font-semibold">{l}<input className="mt-1 w-full rounded-xl border p-3 font-normal" value={(connection.data as any)[k]} onChange={e=>connection.setData(k as any,e.target.value)}/></label>)}</div><label className="mt-4 flex gap-2 text-sm"><input type="checkbox" checked={connection.data.verify_ssl} onChange={e=>connection.setData('verify_ssl',e.target.checked)}/> Verify SSL certificate</label><button onClick={()=>connection.post('/admin/providers/'+provider.id+'/connections',{onSuccess:()=>setStep(3)} as any)} className="mt-6 rounded-xl bg-indigo-700 px-5 py-3 font-semibold text-white">Save connection and continue</button></section>}
 {step===3&&<section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Dynamic authentication</h2><p className="mt-2 text-slate-600">Authentication fields are intentionally provider-configurable. Credentials are never shown back as plaintext.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{['API Key','Token','Secret','Username','Password','PIN','Client ID','Client Secret','Merchant ID','Account ID'].map(x=><div key={x} className="rounded-xl border p-4"><span className="text-sm font-semibold">{x}</span><input type="password" className="mt-2 w-full rounded-xl border p-3" placeholder="Secure credential"/></div>)}</div><button onClick={()=>setStep(4)} className="mt-6 rounded-xl bg-indigo-700 px-5 py-3 font-semibold text-white">Continue</button></section>}
 {step===4&&<section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Endpoints</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><input className="rounded-xl border p-3" placeholder="Endpoint name" value={endpoint.data.name} onChange={e=>endpoint.setData('name',e.target.value)}/><select className="rounded-xl border p-3" value={endpoint.data.method} onChange={e=>endpoint.setData('method',e.target.value as any)}><option>GET</option><option>POST</option><option>PUT</option><option>PATCH</option><option>DELETE</option></select><input className="rounded-xl border p-3" placeholder="Relative path e.g. /services" value={endpoint.data.path} onChange={e=>endpoint.setData('path',e.target.value)}/><input className="rounded-xl border p-3" placeholder="Full URL override (optional)" value={endpoint.data.full_url} onChange={e=>endpoint.setData('full_url',e.target.value)}/></div><button onClick={()=>endpoint.post('/admin/providers/'+provider.id+'/endpoints',{onSuccess:()=>setStep(5)} as any)} className="mt-6 rounded-xl bg-indigo-700 px-5 py-3 font-semibold text-white">Save endpoint and continue</button></section>}
 {step===5&&<section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Test and discover</h2><p className="mt-2 text-slate-600">This performs a real request against the configured provider. If no discovery endpoint exists, use manual service configuration.</p><button disabled={discovering} onClick={discover} className="mt-5 rounded-xl bg-indigo-700 px-5 py-3 font-semibold text-white disabled:opacity-50">{discovering?'Discovering...':'Discover Services'}</button>{services.length>0&&<p className="mt-3 text-sm font-semibold text-emerald-700">{services.length} services discovered.</p>}</section>}
 {step===6&&<section className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Select services to import</h2><p className="mt-1 text-slate-600">Select exactly what SEMIZZY ONE should import.</p></div><button disabled={!selected.length||importing} onClick={importSelected} className="rounded-xl bg-indigo-700 px-5 py-3 font-semibold text-white disabled:opacity-50">{importing?'Importing...':'Import Selected ('+selected.length+')'}</button></div><div className="mt-6 space-y-5">{groups.map(([category,items])=><div key={category} className="overflow-hidden rounded-xl border"><div className="flex items-center justify-between bg-slate-50 p-4"><h3 className="font-bold">{category}</h3><button className="text-sm font-semibold text-indigo-700" onClick={()=>setSelected(s=>Array.from(new Set(s.concat(items.map(x=>x.id)))))}>Select category</button></div>{items.map(s=><label key={s.id} className="flex cursor-pointer items-center gap-3 border-t p-4 hover:bg-slate-50"><input type="checkbox" checked={selected.includes(s.id)} onChange={()=>toggle(s.id)}/><span className="flex-1"><strong>{s.name}</strong><small className="ml-2 text-slate-500">{s.network||''}</small></span><span className="font-semibold">{s.provider_price?s.currency+' '+s.provider_price:'-'}</span><span className="text-xs text-slate-500">{s.status}</span></label>)}</div>)}</div></section>}
 </div></main></>;
}