import React,{useEffect,useState} from 'react';

type Service={id:number;category?:{name:string};service_key:string;name:string;platform:string;operation:string;mode:'provider_api'|'manual';min_quantity:number;max_quantity:number;unit_price_minor:string;currency:string;active:boolean};
type Mapping={id:number;provider_id:number;provider?:string;service_key:string;provider_service_id?:string;capabilities:string[];enabled:boolean};

export default function SmmAdmin(){
 const [services,setServices]=useState<Service[]>([]); const [maps,setMaps]=useState<Mapping[]>([]); const [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true); const [a,b]=await Promise.all([fetch('/admin/smm').then(r=>r.ok?r.json():null),fetch('/admin/smm/mappings').then(r=>r.ok?r.json():null)]); if(a?.data?.data)setServices(a.data.data); if(b?.data)setMaps(b.data); setLoading(false)};
 useEffect(()=>{load()},[]);
 const toggle=async(id:number)=>{await fetch('/admin/smm/services/'+id+'/toggle',{method:'POST',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]')?.getAttribute('content')||''}});load()};
 const toggleMap=async(id:number)=>{await fetch('/admin/smm/mappings/'+id+'/toggle',{method:'POST',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]')?.getAttribute('content')||''}});load()};
 return <div className="space-y-6 p-6"><div><h1 className="text-2xl font-bold">SMM Services</h1><p className="text-sm opacity-70">Manage service catalogue and Core provider mappings.</p></div>
 <section><h2 className="mb-3 text-lg font-semibold">Service Catalogue</h2>{loading?<p>Loading…</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="p-2 text-left">Service</th><th className="p-2">Platform</th><th className="p-2">Mode</th><th className="p-2">Range</th><th className="p-2">Price</th><th className="p-2">Status</th><th/></tr></thead><tbody>{services.map(s=><tr key={s.id} className="border-t"><td className="p-2"><div className="font-medium">{s.name}</div><div className="text-xs opacity-60">{s.service_key}</div></td><td className="p-2 text-center">{s.platform}</td><td className="p-2 text-center">{s.mode}</td><td className="p-2 text-center">{s.min_quantity}–{s.max_quantity}</td><td className="p-2 text-center">{s.unit_price_minor} {s.currency}</td><td className="p-2 text-center">{s.active?'Active':'Disabled'}</td><td className="p-2 text-right"><button onClick={()=>toggle(s.id)} className="rounded border px-3 py-1">{s.active?'Disable':'Enable'}</button></td></tr>)}</tbody></table></div>}</section>
 <section><h2 className="mb-3 text-lg font-semibold">Provider Mappings</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="p-2 text-left">Provider</th><th className="p-2">Service</th><th className="p-2">Provider ID</th><th className="p-2">Capabilities</th><th className="p-2">Status</th><th/></tr></thead><tbody>{maps.map(m=><tr key={m.id} className="border-t"><td className="p-2">{m.provider||'Provider #'+m.provider_id}</td><td className="p-2">{m.service_key}</td><td className="p-2">{m.provider_service_id||'—'}</td><td className="p-2">{m.capabilities.join(', ')}</td><td className="p-2">{m.enabled?'Enabled':'Disabled'}</td><td className="p-2 text-right"><button onClick={()=>toggleMap(m.id)} className="rounded border px-3 py-1">{m.enabled?'Disable':'Enable'}</button></td></tr>)}</tbody></table></div></section>
 </div>
}