import React from 'react';
import { router } from '@inertiajs/react';

type Service={id:number;category?:{name:string};service_key:string;name:string;platform:string;operation:string;mode:'provider_api'|'manual';min_quantity:number;max_quantity:number;unit_price_minor:string;currency:string;active:boolean};
type Mapping={id:number;provider_id:number;provider?:string;service_key:string;provider_service_id?:string;capabilities:string[];enabled:boolean};
type Provider={id:number;display_name:string;identifier:string;enabled:boolean;paused:boolean;verification_status:string;integration_status:string;priority:number};

export default function SmmAdmin({services,mappings,providers}:{services:{data:Service[]};mappings:Mapping[];providers:Provider[]}){
 const items=services?.data??[]; const maps=mappings??[]; const [providerId,setProviderId]=React.useState(''); const [serviceKey,setServiceKey]=React.useState(items[0]?.service_key??''); const [providerServiceId,setProviderServiceId]=React.useState(''); const caps=['smm_order','smm_status','smm_requery']; const [saving,setSaving]=React.useState(false);
 const saveMapping=async()=>{if(!providerId||!serviceKey||caps.length===0)return;setSaving(true);try{const r=await fetch('/admin/smm/mappings',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]')?.getAttribute('content')||''},body:JSON.stringify({api_provider_id:Number(providerId),service_key:serviceKey,provider_service_id:providerServiceId||null,capabilities:caps,enabled:true})});if(r.ok){setProviderServiceId('');router.reload({only:['services','mappings','providers']});}}finally{setSaving(false)}};
 const editMapping=async(m:Mapping)=>{const id=window.prompt('Provider service ID',m.provider_service_id||'');if(id===null)return;await fetch('/admin/smm/mappings/'+m.id,{method:'PATCH',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]')?.getAttribute('content')||''},body:JSON.stringify({provider_service_id:id,capabilities:m.capabilities})});router.reload({only:['services','mappings','providers']});};
 const toggle=async(id:number)=>{await fetch('/admin/smm/services/'+id+'/toggle',{method:'POST',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]')?.getAttribute('content')||''}});router.reload({only:['services','mappings']})};
 const toggleMap=async(id:number)=>{await fetch('/admin/smm/mappings/'+id+'/toggle',{method:'POST',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]')?.getAttribute('content')||''}});router.reload({only:['services','mappings']})};
 return <div className="space-y-6 p-6"><div><h1 className="text-2xl font-bold">SMM Services</h1><p className="text-sm opacity-70">Manage service catalogue and Core provider mappings.</p></div>
 <section><h2 className="mb-3 text-lg font-semibold">Service Catalogue</h2>{<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="p-2 text-left">Service</th><th className="p-2">Platform</th><th className="p-2">Mode</th><th className="p-2">Range</th><th className="p-2">Price</th><th className="p-2">Status</th><th/></tr></thead><tbody>{items.map(s=><tr key={s.id} className="border-t"><td className="p-2"><div className="font-medium">{s.name}</div><div className="text-xs opacity-60">{s.service_key}</div></td><td className="p-2 text-center">{s.platform}</td><td className="p-2 text-center">{s.mode}</td><td className="p-2 text-center">{s.min_quantity}–{s.max_quantity}</td><td className="p-2 text-center">{s.unit_price_minor} {s.currency}</td><td className="p-2 text-center">{s.active?'Active':'Disabled'}</td><td className="p-2 text-right"><button onClick={()=>toggle(s.id)} className="rounded border px-3 py-1">{s.active?'Disable':'Enable'}</button></td></tr>)}</tbody></table></div>}</section>
 <section><h2 className="mb-3 text-lg font-semibold">Add Provider Mapping</h2><div className="grid gap-3 rounded border p-4 md:grid-cols-4"><select className="rounded border p-2" value={providerId} onChange={e=>setProviderId(e.target.value)}><option value="">Select provider</option>{providers?.map(p=><option key={p.id} value={p.id}>{p.display_name} ({p.identifier})</option>)}</select><select className="rounded border p-2" value={serviceKey} onChange={e=>setServiceKey(e.target.value)}><option value="">Select service</option>{items.map(s=><option key={s.id} value={s.service_key}>{s.name}</option>)}</select><input className="rounded border p-2" placeholder="Provider service ID" value={providerServiceId} onChange={e=>setProviderServiceId(e.target.value)}/><button disabled={saving} onClick={saveMapping} className="rounded border px-3 py-2">{saving?'Saving…':'Save Mapping'}</button></div></section>
 <section><h2 className="mb-3 text-lg font-semibold">Provider Mappings</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="p-2 text-left">Provider</th><th className="p-2">Service</th><th className="p-2">Provider ID</th><th className="p-2">Capabilities</th><th className="p-2">Status</th><th/></tr></thead><tbody>{maps.map(m=><tr key={m.id} className="border-t"><td className="p-2">{m.provider||'Provider #'+m.provider_id}</td><td className="p-2">{m.service_key}</td><td className="p-2">{m.provider_service_id||'—'}</td><td className="p-2">{m.capabilities.join(', ')}</td><td className="p-2">{m.enabled?'Enabled':'Disabled'}</td><td className="p-2 text-right"><button onClick={()=>editMapping(m)} className="mr-2 rounded border px-3 py-1">Edit</button><button onClick={()=>toggleMap(m.id)} className="rounded border px-3 py-1">{m.enabled?'Disable':'Enable'}</button></td></tr>)}</tbody></table></div></section>
 </div>
}