import React from 'react';
import { router } from '@inertiajs/react';
type Service={id:number;service_key:string;name:string;platform:string;operation:string;mode:string;min_quantity:number;max_quantity:number;unit_price_minor:string;currency:string;active:boolean};
type Mapping={id:number;provider_id:number;provider?:string;service_key:string;provider_service_id?:string;capabilities:string[];enabled:boolean};
type Provider={id:number;display_name:string;identifier:string};
export default function SmmAdmin({services,mappings,providers}:{services:{data:Service[]};mappings:Mapping[];providers:Provider[]}){
 const items=services?.data??[], maps=mappings??[]; const [providerId,setProviderId]=React.useState(''); const [serviceKey,setServiceKey]=React.useState(items[0]?.service_key??''); const [providerServiceId,setProviderServiceId]=React.useState(''); const [saving,setSaving]=React.useState(false);
 const csrf=()=>document.querySelector('meta[name="csrf-token"]')?.getAttribute('content')||'';
 const saveMapping=async()=>{if(!providerId||!serviceKey)return;setSaving(true);try{const r=await fetch('/admin/smm/mappings',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrf()},body:JSON.stringify({api_provider_id:Number(providerId),service_key:serviceKey,provider_service_id:providerServiceId||null,capabilities:['smm_order','smm_status','smm_requery'],enabled:true})});if(r.ok){setProviderServiceId('');router.reload({only:['services','mappings','providers']});}}finally{setSaving(false);}};
 const toggle=async(id:number)=>{await fetch('/admin/smm/services/'+id+'/toggle',{method:'POST',headers:{'X-CSRF-TOKEN':csrf()}});router.reload({only:['services','mappings']});};
 const toggleMap=async(id:number)=>{await fetch('/admin/smm/mappings/'+id+'/toggle',{method:'POST',headers:{'X-CSRF-TOKEN':csrf()}});router.reload({only:['services','mappings']});};
 return <div className="space-y-6 p-6"><h1 className="text-2xl font-bold">SMM Services</h1><section><h2 className="mb-3 text-lg font-semibold">Service Catalogue</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="p-2 text-left">Service</th><th>Platform</th><th>Mode</th><th>Range</th><th>Price</th><th>Status</th><th /></tr></thead><tbody>{items.map(s=><tr key={s.id} className="border-t"><td className="p-2">{s.name}<div className="text-xs opacity-60">{s.service_key}</div></td><td>{s.platform}</td><td>{s.mode}</td><td>{s.min_quantity}–{s.max_quantity}</td><td>{s.unit_price_minor} {s.currency}</td><td>{s.active?'Active':'Disabled'}</td><td><button onClick={()=>toggle(s.id)} className="rounded border px-3 py-1">{s.active?'Disable':'Enable'}</button></td></tr>)}</tbody></table></div></section><section><h2 className="mb-3 text-lg font-semibold">Add Provider Mapping</h2><div className="grid gap-3 rounded border p-4 md:grid-cols-4"><select className="rounded border p-2" value={providerId} onChange={e=>setProviderId(e.target.value)}><option value="">Select provider</option>{providers?.map(p=><option key={p.id} value={p.id}>{p.display_name} ({p.identifier})</option>)}</select><select className="rounded border p-2" value={serviceKey} onChange={e=>setServiceKey(e.target.value)}><option value="">Select service</option>{items.map(s=><option key={s.id} value={s.service_key}>{s.name}</option>)}</select><input className="rounded border p-2" placeholder="Provider service ID" value={providerServiceId} onChange={e=>setProviderServiceId(e.target.value)}/><button disabled={saving} onClick={saveMapping} className="rounded border px-3 py-2">{saving?'Saving…':'Save Mapping'}</button></div></section><section><h2 className="mb-3 text-lg font-semibold">Provider Mappings</h2><div className="overflow-x-auto"><table className="w-full text-sm"><tbody>{maps.map(m=><tr key={m.id} className="border-t"><td className="p-2">{m.provider||'Provider #'+m.provider_id}</td><td>{m.service_key}</td><td>{m.provider_service_id||'—'}</td><td>{m.capabilities.join(', ')}</td><td>{m.enabled?'Enabled':'Disabled'}</td><td><button onClick={()=>toggleMap(m.id)} className="rounded border px-3 py-1">{m.enabled?'Disable':'Enable'}</button></td></tr>)}</tbody></table></div></section></div>;
}
