import React,{FormEvent,useState}from'react';
import{Head,router}from'@inertiajs/react';

type Page<T>={data:T[];current_page:number;last_page:number;total:number;links?:{url:string|null;label:string;active:boolean}[]};
type Account={id:number;platform:string;title:string;username?:string;country_code?:string;account_age_days?:number;followers?:number;niche?:string;fulfillment_mode:string;provider_reference?:string;price:string;currency:string;status:string};
type NumberItem={id:number;country_code:string;country_name:string;service_key?:string;phone_number:string;fulfillment_mode:string;provider_reference?:string;price:string;currency:string;status:string;expires_at?:string};
type Order={id:number;reference:string;order_type:string;status:string;amount:string;currency:string;provider_reference?:string;provider_id?:string;user?:{id:number;name?:string;email?:string};expires_at?:string;delivered_at?:string};

const input='w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900';
const btn='rounded-lg px-3 py-2 text-sm font-semibold';
function post(url:string,data:any){router.post(url,data,{preserveScroll:true});}
function patch(url:string,data:any){router.patch(url,data,{preserveScroll:true});}

export default function SocialServices({accounts,numbers,orders}:{accounts:Page<Account>;numbers:Page<NumberItem>;orders:Page<Order>}){
 const[t,setT]=useState<'overview'|'accounts'|'numbers'|'orders'>('overview');
 const[q,setQ]=useState(''); const[status,setStatus]=useState('');
 const search=()=>router.get('/admin/social-services',{q,status:status||undefined},{preserveState:true,preserveScroll:true});
 const[account,setAccount]=useState({platform:'',title:'',username:'',country_code:'',account_age_days:'',followers:'',niche:'',fulfillment_mode:'manual',provider_reference:'',price:'',currency:'NGN',status:'available'});
 const[num,setNum]=useState({country_code:'',country_name:'',service_key:'',phone_number:'',fulfillment_mode:'manual',provider_reference:'',price:'',currency:'NGN',status:'available',expires_at:''});
 const[sms,setSms]=useState<Record<number,string>>({}); const[detail,setDetail]=useState<any>(null); const[edit,setEdit]=useState<any>(null); const[error,setError]=useState('');
 const openOrder=async(id:number)=>{try{const r=await fetch('/admin/social-services/orders/'+id,{headers:{Accept:'application/json', 'X-Requested-With':'XMLHttpRequest'}});const j=await r.json();setDetail(j.data)}};
 const submitAccount=(e:FormEvent)=>{e.preventDefault();post('/admin/social-services/accounts',{...account,account_age_days:account.account_age_days||null,followers:account.followers||null});};
 const submitNumber=(e:FormEvent)=>{e.preventDefault();post('/admin/social-services/numbers',{...num,expires_at:num.expires_at||null});};
 const saveEdit=(e:FormEvent)=>{e.preventDefault();if(!edit)return;setError('');const url=edit.kind==='account'?'/admin/social-services/accounts/'+edit.id:'/admin/social-services/numbers/'+edit.id;router.patch(url,edit.data,{preserveScroll:true,onError:(x)=>setError(Object.values(x).flat().join(' ')||'Unable to save changes.'),onSuccess:()=>setEdit(null)});};
 return <><Head title="Social Services Administration"/><main className="space-y-6 p-4 md:p-6">
  <header className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between"><div><h1 className="text-2xl font-bold">Social Accounts & Verification Numbers</h1><p className="text-sm text-slate-500">Admin-supplied inventory only. No seller registration or user listings.</p></div><div className="grid grid-cols-3 gap-2 text-center text-xs"><Stat label="Accounts" value={accounts.total}/><Stat label="Numbers" value={numbers.total}/><Stat label="Orders" value={orders.total}/></div></header>
  <div className="flex flex-col gap-2 md:flex-row"><input className={input} placeholder="Search platform, country, service, order or provider reference" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')search()}}/><select className={input+' md:max-w-xs'} value={status} onChange={e=>{setStatus(e.target.value);router.get('/admin/social-services',{q,status:e.target.value||undefined},{preserveState:true,preserveScroll:true})}}><option value="">All statuses</option>{['available','reserved','sold','disabled','pending_payment','paid','processing','fulfilled','failed','expired','cancelled'].map(s=><option key={s}>{s}</option>)}</select><button className={btn+' bg-slate-900 text-white'} onClick={search}>Search</button></div>
  <nav className="flex flex-wrap gap-2">{(['overview','accounts','numbers','orders'] as const).map(x=><button key={x} onClick={()=>setT(x)} className={btn+' '+(t===x?'bg-slate-900 text-white':'bg-slate-100 dark:bg-slate-800')}>{x[0].toUpperCase()+x.slice(1)}</button>)}</nav>
  {t==='overview'&&<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Panel title="Account inventory"><p>{accounts.total} admin-supplied account records.</p><button className={btn+' mt-3 bg-slate-900 text-white'} onClick={()=>setT('accounts')}>Manage accounts</button></Panel><Panel title="Verification numbers"><p>{numbers.total} numbers with controlled lifecycle and expiry.</p><button className={btn+' mt-3 bg-slate-900 text-white'} onClick={()=>setT('numbers')}>Manage numbers</button></Panel><Panel title="Orders"><p>Review payment, fulfillment, provider and expiry states.</p><button className={btn+' mt-3 bg-slate-900 text-white'} onClick={()=>setT('orders')}>Manage orders</button></Panel><Panel title="Security"><p>SMS is restricted to the owning purchased-number order and expired numbers cannot receive new messages.</p></Panel></div>}
  {edit&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-5 shadow-xl dark:bg-slate-950"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Edit {edit.kind==='account'?'account':'number'}</h2><button className={btn+' bg-slate-100 dark:bg-slate-800'} onClick={()=>setEdit(null)}>Cancel</button></div>{error&&<div className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}<form onSubmit={saveEdit} className="mt-4 grid gap-3 md:grid-cols-2">{Object.entries(edit.data).filter(([k])=>!['id','phone_hash','metadata','description'].includes(k)).map(([k,v])=><input key={k} className={input} placeholder={k.replaceAll('_',' ')} value={String(v??'')} onChange={e=>setEdit({...edit,data:{...edit.data,[k]:e.target.value}})}/>) }<button className={btn+' bg-slate-900 text-white'}>Save changes</button></form></div></div>}
  {t==='accounts'&&<section className="space-y-4"><Panel title="Add account inventory"><form onSubmit={submitAccount} className="grid gap-3 md:grid-cols-3">{(['platform','title','username','country_code','account_age_days','followers','niche','provider_reference','price','currency'] as const).map(k=><input key={k} className={input} placeholder={k.replaceAll('_',' ')} value={(account as any)[k]} onChange={e=>setAccount({...account,[k]:e.target.value})}/>) }<select className={input} value={account.fulfillment_mode} onChange={e=>setAccount({...account,fulfillment_mode:e.target.value})}><option value="manual">Manual</option><option value="api">API</option><option value="api_or_manual">API + Manual fallback</option></select><select className={input} value={account.status} onChange={e=>setAccount({...account,status:e.target.value})}><option>available</option><option>disabled</option></select><button className={btn+' bg-slate-900 text-white'}>Add account</button></form></Panel><InventoryTable type="account" items={accounts.data}/><Pager page={accounts}/></section>}
  {t==='numbers'&&<section className="space-y-4"><Panel title="Add foreign verification number"><form onSubmit={submitNumber} className="grid gap-3 md:grid-cols-3">{(['country_code','country_name','service_key','phone_number','provider_reference','price','currency','expires_at'] as const).map(k=><input key={k} className={input} placeholder={k.replaceAll('_',' ')} type={k==='expires_at'?'datetime-local':'text'} value={(num as any)[k]} onChange={e=>setNum({...num,[k]:e.target.value})}/>) }<select className={input} value={num.fulfillment_mode} onChange={e=>setNum({...num,fulfillment_mode:e.target.value})}><option value="manual">Manual</option><option value="api">API</option><option value="api_or_manual">API + Manual fallback</option></select><select className={input} value={num.status} onChange={e=>setNum({...num,status:e.target.value})}><option>available</option><option>disabled</option></select><button className={btn+' bg-slate-900 text-white'}>Add number</button></form></Panel><InventoryTable type="number" items={numbers.data}/><Pager page={numbers}/></section>}
  {detail&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-5 shadow-xl dark:bg-slate-950"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Order {detail.reference}</h2><button className={btn+' bg-slate-100 dark:bg-slate-800'} onClick={()=>setDetail(null)}>Close</button></div><div className="mt-4 grid gap-3 md:grid-cols-3"><Panel title="Status"><p>{detail.status}</p></Panel><Panel title="Type"><p>{detail.order_type}</p></Panel><Panel title="Amount"><p>{detail.currency} {detail.amount}</p></Panel><Panel title="Provider"><p>{detail.provider_id||'-'}<br/>{detail.provider_reference||'-'}</p></Panel><Panel title="Expiry"><p>{detail.expires_at||'-'}</p></Panel><Panel title="Delivered"><p>{detail.delivered_at||'-'}</p></Panel></div>{detail.order_type==='number'&&<section className="mt-5"><h3 className="mb-2 font-semibold">SMS history</h3><div className="space-y-2">{(detail.sms||[]).map((m:any)=><div key={m.id} className="rounded-lg border p-3"><div className="text-xs text-slate-500">{m.received_at||'-'} · {m.sender||'Unknown sender'} · {m.provider_message_id||'No provider ID'}</div><div className="mt-1 whitespace-pre-wrap">{m.message}</div></div>)}{!(detail.sms||[]).length&&<p className="text-sm text-slate-500">No SMS records.</p>}</div></section>}</div></div>}
  {t==='orders'&&<section className="overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-800"><table className="min-w-full text-sm"><thead className="bg-slate-50 dark:bg-slate-900"><tr>{['Reference','User','Type','Amount','Status','Provider','Actions'].map(h=><th className="px-3 py-3 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{orders.data.map(o=><tr className="border-t dark:border-slate-800" key={o.id}><td className="px-3 py-3 font-mono">{o.reference}</td><td className="px-3 py-3">{o.user?.name||o.user?.email||o.user?.id||'-'}</td><td className="px-3 py-3">{o.order_type}</td><td className="px-3 py-3">{o.currency} {o.amount}</td><td className="px-3 py-3"><select className={input} value={o.status} onChange={e=>patch('/admin/social-services/orders/'+o.id+'/status',{status:e.target.value})}>{['pending_payment','paid','processing','fulfilled','failed','expired','cancelled'].map(s=><option key={s}>{s}</option>)}</select></td><td className="px-3 py-3">{o.provider_id||'-'} / {o.provider_reference||'-'}</td><td className="px-3 py-3 space-y-2"><button className={btn+' bg-slate-100 dark:bg-slate-800'} onClick={()=>openOrder(o.id)}>Details</button><button className={btn+' bg-slate-900 text-white'} onClick={()=>post('/admin/social-services/orders/'+o.id+'/fulfill',{})}>Fulfill</button>{o.order_type==='number'&&<><input className={input} placeholder="Manual SMS" value={sms[o.id]||''} onChange={e=>setSms({...sms,[o.id]:e.target.value})}/><button className={btn+' bg-slate-100 dark:bg-slate-800'} onClick={()=>{if(sms[o.id]){post('/admin/social-services/orders/'+o.id+'/sms',{message:sms[o.id]});setSms({...sms,[o.id]:''})}}}>Add SMS</button></>}</td></tr>)}</tbody></table></section>}
 </main></>
}
function Stat({label,value}:{label:string;value:any}){return <div className="rounded-lg border p-2"><div className="font-semibold">{value}</div><div className="text-slate-500">{label}</div></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-xl border border-slate-200 p-4 dark:border-slate-800"><h2 className="mb-2 font-semibold">{title}</h2>{children}</div>}
function InventoryTable({type,items}:{type:'account'|'number';items:any[]}){return <div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-800"><table className="min-w-full text-sm"><thead><tr>{['ID','Item','Price','Mode','Status','Provider','Action'].map(h=><th key={h} className="px-3 py-3 text-left">{h}</th>)}</tr></thead><tbody>{items.map(i=><tr key={i.id} className="border-t dark:border-slate-800"><td className="px-3 py-3">{i.id}</td><td className="px-3 py-3">{type==='account'?i.platform+' · '+i.title:i.country_name+' · '+i.service_key+' · '+i.phone_number}</td><td className="px-3 py-3">{i.currency} {i.price}</td><td className="px-3 py-3">{i.fulfillment_mode}</td><td className="px-3 py-3">{i.status}</td><td className="px-3 py-3">{i.provider_reference||'-'}</td><td className="px-3 py-3"><div className="flex flex-wrap gap-2"><button className={btn+' bg-slate-100 dark:bg-slate-800'} onClick={()=>setEdit({kind:type,id:i.id,data:{...i}})}>Edit</button><select className="rounded border px-2 py-1" value={i.status} onChange={e=>patch('/admin/social-services/'+type+'s/'+i.id,{status:e.target.value})}>{['available','reserved','sold','disabled'].map(s=><option key={s}>{s}</option>)}</select></div></td></tr>)}</tbody></table></div>}

function Pager({page}:{page:Page<any>}){if(!page.links||page.last_page<=1)return null;return <div className="flex flex-wrap gap-2">{page.links.map((l,i)=><button key={i} disabled={!l.url||l.active} onClick={()=>l.url&&router.get(l.url,{}, {preserveState:true,preserveScroll:true})} className={btn+' '+(l.active?'bg-slate-900 text-white':'bg-slate-100 dark:bg-slate-800 disabled:opacity-40')}>{l.label.replace(/&laquo;|&raquo;/g,x=>x==='&laquo;'?'‹':'›')}</button>)}</div>}
