import { Head, Link, useForm } from '@inertiajs/react';
import type { FormEvent } from 'react';

export default function Register({ referral = '', platform, registrationVerification }: { referral?: string; platform?: { platform_name?: string }; registrationVerification?: { enabled?: boolean; channels?: string[] } }) {
  const channels = registrationVerification?.channels || ['email'];
  const form = useForm({ name: '', username: '', email: '', phone: '', referral_code: referral, password: '', password_confirmation: '', pin: '', pin_confirmation: '', terms: false, verification_channel: channels[0] || 'email' });
  const submit = (e: FormEvent) => { e.preventDefault(); form.post('/register'); };

  return <main className="flex min-h-screen items-center justify-center bg-slate-100 p-6">
    <Head title={`Create account · ${platform?.platform_name || 'SEMIZZY ONE'}`} />
    <form onSubmit={submit} className="w-full max-w-lg rounded-3xl bg-white p-7 shadow-xl">
      <p className="text-sm font-semibold text-indigo-700">{platform?.platform_name || 'SEMIZZY ONE'}</p><h1 className="mt-1 text-3xl font-black text-slate-900">Create your account</h1>
      <p className="mt-2 text-sm text-slate-600">Choose a username you can use to sign in. You can also join through a referral link or code.</p>
      <div className="mt-6 grid gap-4 sm:grid-cols-2">
        <label className="sm:col-span-2"><span className="text-sm font-semibold">Full name</span><input autoComplete="name" required className="mt-1 w-full rounded-xl border p-3" value={form.data.name} onChange={e => form.setData('name', e.target.value)} />{form.errors.name && <p className="mt-1 text-sm text-red-600">{form.errors.name}</p>}</label>
        <label><span className="text-sm font-semibold">Username</span><input required autoComplete="username" minLength={3} maxLength={40} className="mt-1 w-full rounded-xl border p-3" placeholder="e.g. user123" value={form.data.username} onChange={e => form.setData('username', e.target.value)} />{form.errors.username && <p className="mt-1 text-sm text-red-600">{form.errors.username}</p>}</label>
        <label><span className="text-sm font-semibold">Email address</span><input required autoComplete="email" className="mt-1 w-full rounded-xl border p-3" type="email" value={form.data.email} onChange={e => form.setData('email', e.target.value)} />{form.errors.email && <p className="mt-1 text-sm text-red-600">{form.errors.email}</p>}</label>
        <label><span className="text-sm font-semibold">Phone number</span><input required autoComplete="tel" inputMode="tel" className="mt-1 w-full rounded-xl border p-3" placeholder="08012345678" value={form.data.phone} onChange={e => form.setData('phone', e.target.value)} />{form.errors.phone && <p className="mt-1 text-sm text-red-600">{form.errors.phone}</p>}</label>
        <label><span className="text-sm font-semibold">Referral code / link</span><input autoComplete="off" className="mt-1 w-full rounded-xl border p-3" placeholder="Optional" value={form.data.referral_code} onChange={e => form.setData('referral_code', e.target.value)} />{form.errors.referral_code && <p className="mt-1 text-sm text-red-600">{form.errors.referral_code}</p>}</label>
        <label><span className="text-sm font-semibold">Password</span><input required autoComplete="new-password" className="mt-1 w-full rounded-xl border p-3" type="password" value={form.data.password} onChange={e => form.setData('password', e.target.value)} />{form.errors.password && <p className="mt-1 text-sm text-red-600">{form.errors.password}</p>}</label>
        <label><span className="text-sm font-semibold">Confirm password</span><input required autoComplete="new-password" className="mt-1 w-full rounded-xl border p-3" type="password" value={form.data.password_confirmation} onChange={e => form.setData('password_confirmation', e.target.value)} />{form.errors.password_confirmation && <p className="mt-1 text-sm text-red-600">{form.errors.password_confirmation}</p>}</label>
        <label><span className="text-sm font-semibold">Transaction PIN</span><input required inputMode="numeric" autoComplete="new-password" maxLength={4} className="mt-1 w-full rounded-xl border p-3" type="password" placeholder="4-digit PIN" value={form.data.pin} onChange={e => form.setData('pin', e.target.value.replace(/\D/g, '').slice(0,4))} />{form.errors.pin && <p className="mt-1 text-sm text-red-600">{form.errors.pin}</p>}</label>
        <label><span className="text-sm font-semibold">Confirm PIN</span><input required inputMode="numeric" autoComplete="new-password" maxLength={4} className="mt-1 w-full rounded-xl border p-3" type="password" placeholder="Repeat 4-digit PIN" value={form.data.pin_confirmation} onChange={e => form.setData('pin_confirmation', e.target.value.replace(/\D/g, '').slice(0,4))} />{form.errors.pin_confirmation && <p className="mt-1 text-sm text-red-600">{form.errors.pin_confirmation}</p>}</label>
      </div>
      {registrationVerification?.enabled && <div className="mt-5 rounded-2xl border bg-slate-50 p-4"><p className="text-sm font-black">Registration verification</p><p className="mt-1 text-xs text-slate-600">Choose where your 6-digit verification code should be sent.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{channels.map(channel => <label key={channel} className="flex cursor-pointer items-center gap-2 rounded-xl border bg-white p-3 text-sm font-semibold"><input type="radio" name="verification_channel" checked={form.data.verification_channel===channel} onChange={()=>form.setData('verification_channel',channel)} />{channel==='email'?'Email OTP':channel==='sms'?'SMS OTP':'Email OTP'}</label>)}</div>{form.errors.verification_channel && <p className="mt-1 text-sm text-red-600">{form.errors.verification_channel}</p>}</div>}
      <label className="mt-5 flex items-start gap-3 text-sm text-slate-600"><input required type="checkbox" checked={form.data.terms} onChange={e => form.setData('terms', e.target.checked)} className="mt-1" /><span>I agree to the platform terms and confirm the information I provide is accurate.</span></label>
      {form.errors.terms && <p className="mt-1 text-sm text-red-600">{form.errors.terms}</p>}
      <button type="submit" disabled={form.processing} className="mt-6 w-full rounded-xl bg-slate-900 p-3 font-semibold text-white disabled:opacity-50">{form.processing ? 'Creating account…' : 'Create account'}</button>
      <p className="mt-5 text-center text-sm text-slate-600">Already have an account? <Link href="/login" className="font-bold text-indigo-700 hover:underline">Sign in</Link></p>
    </form>
  </main>;
}
